export const TAROT_CARDS = [
  { id: '0', name: 'The Fool', tr: 'Mecnun', arcana: 'major' },
  { id: '1', name: 'The Magician', tr: 'Büyücü', arcana: 'major' },
  { id: '2', name: 'The High Priestess', tr: 'Azize', arcana: 'major' },
  { id: '3', name: 'The Empress', tr: 'İmparatoriçe', arcana: 'major' },
  { id: '4', name: 'The Emperor', tr: 'İmparator', arcana: 'major' },
  { id: '5', name: 'The Hierophant', tr: 'Aziz', arcana: 'major' },
  { id: '6', name: 'The Lovers', tr: 'Aşıklar', arcana: 'major' },
  { id: '7', name: 'The Chariot', tr: 'Araba', arcana: 'major' },
  { id: '8', name: 'Strength', tr: 'Güç', arcana: 'major' },
  { id: '9', name: 'The Hermit', tr: 'Ermiş', arcana: 'major' },
  { id: '10', name: 'Wheel of Fortune', tr: 'Kader Çarkı', arcana: 'major' },
  { id: '11', name: 'Justice', tr: 'Adalet', arcana: 'major' },
  { id: '12', name: 'The Hanged Man', tr: 'Asılan Adam', arcana: 'major' },
  { id: '13', name: 'Death', tr: 'Ölüm', arcana: 'major' },
  { id: '14', name: 'Temperance', tr: 'Denge', arcana: 'major' },
  { id: '15', name: 'The Devil', tr: 'Şeytan', arcana: 'major' },
  { id: '16', name: 'The Tower', tr: 'Yıkılan Kule', arcana: 'major' },
  { id: '17', name: 'The Star', tr: 'Yıldız', arcana: 'major' },
  { id: '18', name: 'The Moon', tr: 'Ay', arcana: 'major' },
  { id: '19', name: 'The Sun', tr: 'Güneş', arcana: 'major' },
  { id: '20', name: 'Judgement', tr: 'Mahkeme', arcana: 'major' },
  { id: '21', name: 'The World', tr: 'Dünya', arcana: 'major' },
];
