-- =============================================================
-- 015_ui_contact_seed.sql
-- İletişim sayfası UI metinleri (TR/EN/DE).
-- Section JSON formatı: useUiSection('ui_contact', locale) tarafından okunur.
-- =============================================================

INSERT INTO site_settings (id, `key`, locale, value) VALUES
(
  '01000000-0000-4000-8000-00000000004a',
  'ui_contact',
  'tr',
  JSON_OBJECT(
    'ui_contact_subprefix',          'GoldMoodAstro',
    'ui_contact_sublabel',           'İletişim',
    'ui_contact_title_left',         'Bize Ulaşın',
    'ui_contact_tagline',            'Sorularınız ve seans rezervasyon talepleriniz için mesaj gönderin. Ekibimiz kısa süre içinde size dönüş yapacaktır.',
    'ui_contact_form_title',         'Mesaj gönder',
    'ui_contact_first_name',         'Ad*',
    'ui_contact_last_name',          'Soyad',
    'ui_contact_phone',              'Telefon*',
    'ui_contact_email',              'E-posta*',
    'ui_contact_subject_label',      'Konu*',
    'ui_contact_message_label',      'Mesaj*',
    'ui_contact_message_placeholder','Mesajınızı yazın...',
    'ui_contact_select_label',       'Konu',
    'ui_contact_service_cooling_towers', 'Randevu talebi',
    'ui_contact_service_maintenance',    'Soru / bilgi',
    'ui_contact_service_modernization',  'İşbirliği',
    'ui_contact_service_other',          'Diğer',
    'ui_contact_terms_prefix',       'Kabul ediyorum:',
    'ui_contact_terms',              'Gizlilik Politikası',
    'ui_contact_conditions',         'Kullanım Koşulları',
    'ui_contact_submit',             'Gönder',
    'ui_contact_sending',            'Gönderiliyor...',
    'ui_contact_success',            'Teşekkürler! Mesajınız iletildi.',
    'ui_contact_error_generic',      'Gönderilemedi. Lütfen tekrar deneyin.',
    'ui_contact_error_required',     'Bu alan zorunludur.',
    'ui_contact_error_email',        'Geçerli bir e-posta adresi girin.',
    'ui_contact_error_phone',        'Geçerli bir telefon numarası girin.',
    'ui_contact_error_message',      'En az 10 karakterlik bir mesaj yazın.',
    'ui_contact_subject_base',       'İletişim Mesajı',
    'ui_contact_address_label',      'Adres',
    'ui_contact_map_title',          'Konum',
    'ui_contact_info_title',         'İletişim bilgileri',
    'ui_contact_info_note_title',    'Not',
    'ui_contact_page_title',         'İletişim',
    'ui_contact_meta_title',         'İletişim | GoldMoodAstro',
    'ui_contact_meta_description',   'GoldMoodAstro ile iletişime geçin: danışmanlık seansları ve sorularınız için bize ulaşın.'
  )
),
(
  '01000000-0000-4000-8000-00000000004b',
  'ui_contact',
  'en',
  JSON_OBJECT(
    'ui_contact_subprefix',          'GoldMoodAstro',
    'ui_contact_sublabel',           'Contact',
    'ui_contact_title_left',         'Get in Touch',
    'ui_contact_tagline',            'For questions and session booking requests, send a message. Our team will get back to you shortly.',
    'ui_contact_form_title',         'Send a message',
    'ui_contact_first_name',         'First name*',
    'ui_contact_last_name',          'Last name',
    'ui_contact_phone',              'Phone*',
    'ui_contact_email',              'Email*',
    'ui_contact_subject_label',      'Subject*',
    'ui_contact_message_label',      'Message*',
    'ui_contact_message_placeholder','Write your message...',
    'ui_contact_select_label',       'Topic',
    'ui_contact_service_cooling_towers', 'Appointment request',
    'ui_contact_service_maintenance',    'Question',
    'ui_contact_service_modernization',  'Collaboration',
    'ui_contact_service_other',          'Other',
    'ui_contact_terms_prefix',       'I agree to the:',
    'ui_contact_terms',              'Privacy Policy',
    'ui_contact_conditions',         'Terms',
    'ui_contact_submit',             'Send',
    'ui_contact_sending',            'Sending...',
    'ui_contact_success',            'Thanks! Your message has been sent.',
    'ui_contact_error_generic',      'Failed to send. Please try again.',
    'ui_contact_error_required',     'This field is required.',
    'ui_contact_error_email',        'Please enter a valid email address.',
    'ui_contact_error_phone',        'Please enter a valid phone number.',
    'ui_contact_error_message',      'Please write a message (at least 10 characters).',
    'ui_contact_subject_base',       'Contact Message',
    'ui_contact_address_label',      'Address',
    'ui_contact_map_title',          'Location',
    'ui_contact_info_title',         'Contact info',
    'ui_contact_info_note_title',    'Note',
    'ui_contact_page_title',         'Contact',
    'ui_contact_meta_title',         'Contact | GoldMoodAstro',
    'ui_contact_meta_description',   'Contact GoldMoodAstro: reach us with questions about our consultation services.'
  )
),
(
  '01000000-0000-4000-8000-00000000004c',
  'ui_contact',
  'de',
  JSON_OBJECT(
    'ui_contact_subprefix',          'GoldMoodAstro',
    'ui_contact_sublabel',           'Kontakt',
    'ui_contact_title_left',         'Nehmen Sie Kontakt auf',
    'ui_contact_tagline',            'Senden Sie uns für Fragen und Beratungstermine eine Nachricht. Unser Team meldet sich in Kürze bei Ihnen.',
    'ui_contact_form_title',         'Nachricht senden',
    'ui_contact_first_name',         'Vorname*',
    'ui_contact_last_name',          'Nachname',
    'ui_contact_phone',              'Telefon*',
    'ui_contact_email',              'E-Mail*',
    'ui_contact_subject_label',      'Betreff*',
    'ui_contact_message_label',      'Nachricht*',
    'ui_contact_message_placeholder','Schreiben Sie Ihre Nachricht...',
    'ui_contact_select_label',       'Thema',
    'ui_contact_service_cooling_towers', 'Terminanfrage',
    'ui_contact_service_maintenance',    'Frage',
    'ui_contact_service_modernization',  'Kooperation',
    'ui_contact_service_other',          'Sonstiges',
    'ui_contact_terms_prefix',       'Ich akzeptiere:',
    'ui_contact_terms',              'Datenschutzrichtlinie',
    'ui_contact_conditions',         'AGB',
    'ui_contact_submit',             'Senden',
    'ui_contact_sending',            'Wird gesendet...',
    'ui_contact_success',            'Danke! Ihre Nachricht wurde gesendet.',
    'ui_contact_error_generic',      'Senden fehlgeschlagen. Bitte erneut versuchen.',
    'ui_contact_error_required',     'Dieses Feld ist erforderlich.',
    'ui_contact_error_email',        'Bitte eine gültige E-Mail-Adresse eingeben.',
    'ui_contact_error_phone',        'Bitte eine gültige Telefonnummer eingeben.',
    'ui_contact_error_message',      'Bitte mindestens 10 Zeichen schreiben.',
    'ui_contact_subject_base',       'Kontaktnachricht',
    'ui_contact_address_label',      'Adresse',
    'ui_contact_map_title',          'Standort',
    'ui_contact_info_title',         'Kontaktdaten',
    'ui_contact_info_note_title',    'Hinweis',
    'ui_contact_page_title',         'Kontakt',
    'ui_contact_meta_title',         'Kontakt | GoldMoodAstro',
    'ui_contact_meta_description',   'Kontaktieren Sie GoldMoodAstro: Anfragen und Fragen zu unseren Beratungsangeboten.'
  )
)
ON DUPLICATE KEY UPDATE value = VALUES(value);
