-- =============================================================
-- 016_ui_auth_seed.sql
-- Auth (login / register) UI metinleri (TR / EN / DE).
-- useUiSection('ui_auth', locale) tarafından okunur.
-- =============================================================

INSERT INTO site_settings (id, `key`, locale, value) VALUES
(
  '01000000-0000-4000-8000-00000000005a',
  'ui_auth',
  'tr',
  JSON_OBJECT(
    -- Login
    'login_title',                  'Giriş Yap',
    'login_lead',                   'Hesabınıza giriş yapın veya yeni bir hesap oluşturun.',
    'login_register_link',          'Hesap oluştur',
    'login_email_label',            'E-posta',
    'login_email_placeholder',      'ornek@goldmoodastro.com',
    'login_password_label',         'Şifre',
    'login_password_placeholder',   'Şifreniz',
    'login_remember_me',            'Beni hatırla',
    'login_forgot_password',        'Şifremi unuttum?',
    'login_loading',                'Giriş yapılıyor...',
    'login_submit',                 'Giriş Yap',
    'login_or',                     'veya',
    'login_google_loading',         'Google ile yönlendiriliyor...',
    'login_google_button',          'Google ile devam et',
    'login_no_account',             'Hesabınız yok mu?',
    'login_register_cta',           'Buradan kayıt olun',
    'login_error_required',         'E-posta ve şifre zorunludur.',
    'login_error_google_generic',   'Google girişi başlatılırken bir hata oluştu.',
    -- Register
    'register_title',               'Kayıt Ol',
    'register_lead_has_account',    'Zaten hesabınız var mı?',
    'register_login_link',          'Giriş yap',
    'register_fullname_label',      'Ad Soyad',
    'register_fullname_placeholder','Adınız ve soyadınız',
    'register_phone_label',         'Telefon',
    'register_phone_placeholder',   '+90 5xx xxx xx xx',
    'register_email_label',         'E-posta',
    'register_email_placeholder',   'ornek@goldmoodastro.com',
    'register_password_label',      'Şifre',
    'register_password_placeholder','Şifre',
    'register_password_again_label','Tekrar',
    'register_password_again_placeholder','Şifreyi tekrar girin',
    'register_loading',             'Hesap oluşturuluyor...',
    'register_submit',              'Kayıt Ol',
    'register_or',                  'veya',
    'register_google_loading',      'Google ile yönlendiriliyor...',
    'register_google_button',       'Google ile devam et',
    'register_error_required',      'E-posta ve şifre zorunludur.',
    'register_error_password_length','Şifre en az 6 karakter olmalıdır.',
    'register_error_password_mismatch','Şifreler eşleşmiyor.',
    'register_error_google_generic','Google ile kayıt başlatılırken bir hata oluştu.'
  )
),
(
  '01000000-0000-4000-8000-00000000005b',
  'ui_auth',
  'en',
  JSON_OBJECT(
    'login_title',                  'Sign In',
    'login_lead',                   'Sign in to your account or create a new one.',
    'login_register_link',          'Create an account',
    'login_email_label',            'Email',
    'login_email_placeholder',      'example@goldmoodastro.com',
    'login_password_label',         'Password',
    'login_password_placeholder',   'Your password',
    'login_remember_me',            'Remember me',
    'login_forgot_password',        'Forgot password?',
    'login_loading',                'Signing in...',
    'login_submit',                 'Sign In',
    'login_or',                     'or',
    'login_google_loading',         'Redirecting to Google...',
    'login_google_button',          'Continue with Google',
    'login_no_account',             'Don''t have an account?',
    'login_register_cta',           'Sign up here',
    'login_error_required',         'Email and password are required.',
    'login_error_google_generic',   'An error occurred while starting Google login.',
    'register_title',               'Sign Up',
    'register_lead_has_account',    'Already have an account?',
    'register_login_link',          'Sign in',
    'register_fullname_label',      'Full Name',
    'register_fullname_placeholder','Your full name',
    'register_phone_label',         'Phone',
    'register_phone_placeholder',   '+90 5xx xxx xx xx',
    'register_email_label',         'Email',
    'register_email_placeholder',   'example@goldmoodastro.com',
    'register_password_label',      'Password',
    'register_password_placeholder','Password',
    'register_password_again_label','Again',
    'register_password_again_placeholder','Repeat',
    'register_loading',             'Creating account...',
    'register_submit',              'Sign Up',
    'register_or',                  'or',
    'register_google_loading',      'Redirecting to Google...',
    'register_google_button',       'Continue with Google',
    'register_error_required',      'Email and password are required.',
    'register_error_password_length','Password must be at least 6 characters.',
    'register_error_password_mismatch','Passwords do not match.',
    'register_error_google_generic','An error occurred while starting Google signup.'
  )
),
(
  '01000000-0000-4000-8000-00000000005c',
  'ui_auth',
  'de',
  JSON_OBJECT(
    'login_title',                  'Anmelden',
    'login_lead',                   'Melden Sie sich an oder erstellen Sie ein neues Konto.',
    'login_register_link',          'Konto erstellen',
    'login_email_label',            'E-Mail',
    'login_email_placeholder',      'beispiel@goldmoodastro.com',
    'login_password_label',         'Passwort',
    'login_password_placeholder',   'Ihr Passwort',
    'login_remember_me',            'Angemeldet bleiben',
    'login_forgot_password',        'Passwort vergessen?',
    'login_loading',                'Anmeldung läuft...',
    'login_submit',                 'Anmelden',
    'login_or',                     'oder',
    'login_google_loading',         'Weiterleitung zu Google...',
    'login_google_button',          'Mit Google fortfahren',
    'login_no_account',             'Noch kein Konto?',
    'login_register_cta',           'Hier registrieren',
    'login_error_required',         'E-Mail und Passwort sind erforderlich.',
    'login_error_google_generic',   'Beim Starten der Google-Anmeldung ist ein Fehler aufgetreten.',
    'register_title',               'Registrieren',
    'register_lead_has_account',    'Sie haben bereits ein Konto?',
    'register_login_link',          'Anmelden',
    'register_fullname_label',      'Vollständiger Name',
    'register_fullname_placeholder','Ihr vollständiger Name',
    'register_phone_label',         'Telefon',
    'register_phone_placeholder',   '+49 ...',
    'register_email_label',         'E-Mail',
    'register_email_placeholder',   'beispiel@goldmoodastro.com',
    'register_password_label',      'Passwort',
    'register_password_placeholder','Passwort',
    'register_password_again_label','Wiederholen',
    'register_password_again_placeholder','Passwort wiederholen',
    'register_loading',             'Konto wird erstellt...',
    'register_submit',              'Registrieren',
    'register_or',                  'oder',
    'register_google_loading',      'Weiterleitung zu Google...',
    'register_google_button',       'Mit Google fortfahren',
    'register_error_required',      'E-Mail und Passwort sind erforderlich.',
    'register_error_password_length','Passwort muss mindestens 6 Zeichen lang sein.',
    'register_error_password_mismatch','Passwörter stimmen nicht überein.',
    'register_error_google_generic','Beim Starten der Google-Registrierung ist ein Fehler aufgetreten.'
  )
)
ON DUPLICATE KEY UPDATE value = VALUES(value);
