-- 016e_ui_home_sections_seed.sql
-- HeroNew/ConsultantsSection/TransparencySection/WelcomeBannerSection i18n (tr/en/de)
INSERT INTO site_settings (id, `key`, locale, value) VALUES
('4839e2d6-0da0-e6b4-9cac-5602544775e5', 'ui_home_hero_eyebrow', '*', '{"label": {"tr": "Ruhsal Rehberlik", "en": "Spiritual Guidance", "de": "Spirituelle Begleitung"}}'),
('26df1f28-6de9-e656-bb91-ef2b3e98840c', 'ui_home_hero_headline_1', '*', '{"label": {"tr": "Modern astroloji ile", "en": "Modern astrology", "de": "Moderne Astrologie"}}'),
('b64dedbc-bc4c-d1a5-c35f-b182b32469bb', 'ui_home_hero_headline_2', '*', '{"label": {"tr": "yıldızlarla buluşun", "en": "meets the stars", "de": "trifft die Sterne"}}'),
('6950279c-690e-f86b-d3cf-cd04e7c9e0aa', 'ui_home_hero_scroll_hint', '*', '{"label": {"tr": "Aşağı Kaydır", "en": "Scroll Down", "de": "Nach unten scrollen"}}'),
('22592d2e-5d92-f62a-4282-6d97dfe3262b', 'ui_home_consultants_featured_title', '*', '{"label": {"tr": "Öne Çıkan Danışmanlar", "en": "Featured Consultants", "de": "Empfohlene Berater"}}'),
('49b7a8bf-4d1c-2690-4695-1736656a8058', 'ui_home_consultants_featured_subtitle', '*', '{"label": {"tr": "En yüksek puana ve seans sayısına sahip uzmanlar", "en": "Experts with the highest ratings and session counts", "de": "Experten mit den höchsten Bewertungen und Sitzungszahlen"}}'),
('6fa805bd-7291-2b5e-b6a6-bd9fd21b6cf8', 'ui_home_consultants_popular_title', '*', '{"label": {"tr": "Popüler Danışmanlar", "en": "Popular Consultants", "de": "Beliebte Berater"}}'),
('105d5501-5cc0-a408-cc8b-a79f94b434f9', 'ui_home_consultants_popular_subtitle', '*', '{"label": {"tr": "En çok seans tamamlamış deneyimli uzmanlar", "en": "Experienced experts with the most completed sessions", "de": "Erfahrene Experten mit den meisten abgeschlossenen Sitzungen"}}'),
('56cc9f18-4b40-3591-34af-8cccdb0e381e', 'ui_home_consultants_new_title', '*', '{"label": {"tr": "Yeni Danışmanlar", "en": "New Consultants", "de": "Neue Berater"}}'),
('901d169e-2fdd-1808-4b89-7dbeec62c982', 'ui_home_consultants_new_subtitle', '*', '{"label": {"tr": "Platforma yeni katılan astrologlar", "en": "Astrologers who recently joined the platform", "de": "Astrologen, die kürzlich der Plattform beigetreten sind"}}'),
('b56080c1-24ce-2af8-85bb-8597147a1a68', 'ui_home_consultants_online_title', '*', '{"label": {"tr": "Çevrimiçi Danışmanlar", "en": "Online Consultants", "de": "Berater online"}}'),
('f95b86f3-4fb4-5130-768a-9e3611596419', 'ui_home_consultants_online_subtitle', '*', '{"label": {"tr": "Şu anda müsait, görüşmeye hazır", "en": "Available now, ready to connect", "de": "Jetzt verfügbar, bereit für ein Gespräch"}}'),
('c0912219-e1de-f6a2-641b-c2f6c867e1dd', 'ui_home_welcome_title', '*', '{"label": {"tr": "GOLDMOODASTRO''YA HOŞ GELDİNİZ", "en": "WELCOME TO GOLDMOODASTRO", "de": "WILLKOMMEN BEI GOLDMOODASTRO"}}'),
('2e232323-ea01-caf7-cf25-651496a11127', 'ui_home_welcome_subtitle', '*', '{"label": {"tr": "Yıldızların <em>rehberliğinde</em> modern astroloji.", "en": "Modern astrology <em>guided</em> by the stars.", "de": "Moderne Astrologie <em>geführt</em> von den Sternen."}}'),
('a9f9ba05-e259-cbf4-d1b2-c627842d66b4', 'ui_home_welcome_cta', '*', '{"label": {"tr": "DANIŞMANLARI KEŞFET", "en": "DISCOVER CONSULTANTS", "de": "BERATER ENTDECKEN"}}'),
('ee2a2a60-8ef6-9afc-ed43-9ac30db334ac', 'ui_home_transparency_label', '*', '{"label": {"tr": "Üyelik", "en": "Membership", "de": "Mitgliedschaft"}}'),
('533c1901-75b7-9fd5-e673-5e80b95023c6', 'ui_home_transparency_title_1', '*', '{"label": {"tr": "Şeffaf fiyatlandırma,", "en": "Transparent pricing,", "de": "Transparente Preise,"}}'),
('469369df-8b10-5bdb-e263-0da223bb4acd', 'ui_home_transparency_title_2', '*', '{"label": {"tr": "gizli koşul yok.", "en": "no hidden terms.", "de": "keine versteckten Bedingungen."}}'),
('9f22e793-4f5c-778f-b380-0c0a37e98cb4', 'ui_home_transparency_free_badge', '*', '{"label": {"tr": "Ücretsiz", "en": "Free", "de": "Kostenlos"}}'),
('38e37c9d-a3fc-949f-aaba-0b32c714763a', 'ui_home_transparency_free_name', '*', '{"label": {"tr": "Misafir", "en": "Guest", "de": "Gast"}}'),
('8058316d-ec9d-062e-6a03-a481d754d49d', 'ui_home_transparency_per_month', '*', '{"label": {"tr": "/ ay", "en": "/ mo", "de": "/ Mon."}}'),
('f0852b92-1f1a-c85c-dfa2-ff38a303f3c8', 'ui_home_transparency_free_tagline', '*', '{"label": {"tr": "Yıldızlarla tanışın, hiçbir taahhüt yok.", "en": "Meet the stars, no commitment.", "de": "Lernen Sie die Sterne kennen, ohne Verpflichtung."}}'),
('aa70f99c-2f1c-c14d-4cb0-ec799ca7c0e6', 'ui_home_transparency_free_feature_1', '*', '{"label": {"tr": "Temel doğum haritası görünümü", "en": "Basic birth chart view", "de": "Grundlegende Geburtshoroskop-Ansicht"}}'),
('8742d389-6828-a444-985a-a57bc39cabea', 'ui_home_transparency_free_feature_2', '*', '{"label": {"tr": "Kısa günlük yorum", "en": "Short daily reading", "de": "Kurze tägliche Deutung"}}'),
('f70209b4-ee16-aa36-c676-650cfb6cdc89', 'ui_home_transparency_free_feature_3', '*', '{"label": {"tr": "Burç uyumu (özet)", "en": "Sign compatibility (summary)", "de": "Sternzeichen-Kompatibilität (Zusammenfassung)"}}'),
('d864be61-ac8b-0b86-2099-59bb197ae983', 'ui_home_transparency_free_cta', '*', '{"label": {"tr": "Ücretsiz Başla", "en": "Start for Free", "de": "Kostenlos starten"}}'),
('f4a0aaf9-f49e-2016-f28d-7b41f54d9444', 'ui_home_transparency_recommended_badge', '*', '{"label": {"tr": "Önerilen", "en": "Recommended", "de": "Empfohlen"}}'),
('a14f3c9a-d97a-dd61-1b79-ae698f7913a4', 'ui_home_transparency_monthly_name', '*', '{"label": {"tr": "Premium Aylık", "en": "Premium Monthly", "de": "Premium Monatlich"}}'),
('59494755-73e9-b735-b402-3d1c903ebb95', 'ui_home_transparency_monthly_tagline', '*', '{"label": {"tr": "Sınırsız derinlik, esnek ödeme.", "en": "Limitless depth, flexible payment.", "de": "Grenzenlose Tiefe, flexible Zahlung."}}'),
('b8feb865-6e61-3abb-ec8c-f2bbe620aa35', 'ui_home_transparency_monthly_feature_1', '*', '{"label": {"tr": "Detaylı doğum haritası analizi", "en": "Detailed birth chart analysis", "de": "Detaillierte Geburtshoroskop-Analyse"}}'),
('8eb6487a-0cd2-5fa7-4710-4c9812cd42f6', 'ui_home_transparency_monthly_feature_2', '*', '{"label": {"tr": "Günlük · haftalık · aylık öngörü", "en": "Daily · weekly · monthly forecast", "de": "Tägliche · wöchentliche · monatliche Vorhersage"}}'),
('ea757c47-6f1b-95d7-1c53-6633b5bc01e0', 'ui_home_transparency_monthly_feature_3', '*', '{"label": {"tr": "Sinastri & kompozit haritalar", "en": "Synastry & composite charts", "de": "Synastrie- & Komposithoroskope"}}'),
('62275f09-7f65-cae8-360d-502428b50405', 'ui_home_transparency_monthly_feature_4', '*', '{"label": {"tr": "Tarot açılımı (Kelt Haçı dahil)", "en": "Tarot reading (inc. Celtic Cross)", "de": "Tarot-Legung (inkl. Keltisches Kreuz)"}}'),
('599c6d1b-0bce-b62e-9112-11828ce1fbf0', 'ui_home_transparency_monthly_cta', '*', '{"label": {"tr": "Hemen Seç", "en": "Select Now", "de": "Jetzt auswählen"}}'),
('a964106e-e624-0b44-459f-6b7a372aec1f', 'ui_home_transparency_best_value_badge', '*', '{"label": {"tr": "En Avantajlı", "en": "Best Value", "de": "Bestes Angebot"}}'),
('ddf6b446-8e65-4be2-cde9-b632e359fb7f', 'ui_home_transparency_yearly_name', '*', '{"label": {"tr": "Premium Yıllık", "en": "Premium Yearly", "de": "Premium Jährlich"}}'),
('5c79a215-b5fa-9df9-e8d4-357140282936', 'ui_home_transparency_per_year', '*', '{"label": {"tr": "/ yıl", "en": "/ yr", "de": "/ Jahr"}}'),
('bd22e435-d32a-ef1f-b1c8-e5b9b2e527b0', 'ui_home_transparency_yearly_tagline', '*', '{"label": {"tr": "2 ay ücretsiz. Kesintisiz deneyim.", "en": "2 months free. Uninterrupted experience.", "de": "2 Monate gratis. Ununterbrochenes Erlebnis."}}'),
('505ca8e9-59c3-a4e2-5972-7d1182c1cf91', 'ui_home_transparency_yearly_feature_1', '*', '{"label": {"tr": "Aylık plandaki tüm özellikler", "en": "All features in Monthly", "de": "Alle Funktionen des Monatsplans"}}'),
('550486a7-7ce0-b84a-4205-0ae330184c03', 'ui_home_transparency_yearly_feature_2', '*', '{"label": {"tr": "Astrolog seanslarında %20 indirim", "en": "20% discount for astrologer sessions", "de": "20% Rabatt auf Astrologen-Sitzungen"}}'),
('ebdb341a-d1f5-298a-63b5-fbb6cd08c152', 'ui_home_transparency_yearly_feature_3', '*', '{"label": {"tr": "VIP öncelikli destek", "en": "VIP priority support", "de": "VIP-Prioritätssupport"}}'),
('a7571abe-75db-5acb-e11d-45da5852e1c0', 'ui_home_transparency_yearly_feature_4', '*', '{"label": {"tr": "Kapsamlı yıllık genel bakış", "en": "Comprehensive year-ahead overview", "de": "Umfassender Ausblick auf das kommende Jahr"}}'),
('4a19e8bf-4b52-c038-b1f9-876a2e13c98c', 'ui_home_transparency_yearly_cta', '*', '{"label": {"tr": "Ön Kayıt", "en": "Pre-Register", "de": "Vorregistrieren"}}'),
('e339a466-7f4d-ad02-02b7-47bd326a4efc', 'ui_home_transparency_guarantee_title', '*', '{"label": {"tr": "Şeffaflık Garantisi", "en": "Transparency Guarantee", "de": "Transparenzgarantie"}}'),
('ae618075-de7c-f577-92e1-a5e4613ca6ba', 'ui_home_transparency_guarantee_desc', '*', '{"label": {"tr": "Ücretsiz deneme, kredi kartı istemeden başlar. Premium''a geçişi manuel olarak siz onaylarsınız — kimse haberiniz olmadan sizden ücret almaz. İptal etmek yalnızca bir tık uzağınızda.", "en": "Free trial starts without asking for a credit card. You manually approve the transition to Premium — no one charges you without your knowledge. Canceling is just a click away.", "de": "Die kostenlose Testphase beginnt ohne Kreditkartenabfrage. Sie bestätigen den Wechsel zu Premium manuell — niemand belastet Sie ohne Ihr Wissen. Die Kündigung ist nur einen Klick entfernt."}}')
ON DUPLICATE KEY UPDATE value = VALUES(value);
