-- =============================================================
-- 017_seo_pages_seed.sql
-- Sayfa-bazlı SEO ayarları kataloğu (FULL — 2026-04-30 gerçek içerik)
--
-- Tek bir site_settings satırı (`seo_pages`, locale='tr'/'en'/'de') altında
-- tüm sayfalar için { title, description, og_image, no_index } alanları tutulur.
--
-- Admin panel "SEO Ayarları" sekmesinden her sayfa için inline düzenlenir.
-- Frontend `generateMetadata()` ile bu key'i okuyup uygular
-- (`buildPageMetadata({ locale, pageKey, pathname, fallback })`).
--
-- ─── Sayfa key kataloğu ────────────────────────────────────────────────────
-- TEMEL: home, birth-chart, consultants, consultant-detail, pricing, daily,
--        blog, blog-post, about, contact, faqs
-- BURÇLAR: burclar, burclar-sign, burclar-bugun, burclar-haftalik,
--          burclar-aylik, burclar-ask, burclar-kariyer, burclar-saglik,
--          burclar-uyumlulik, burclar-pair-uyumu, burclar-transit
-- DOĞUM HARİTASI: yukselen-burc-hesaplayici, big-three
-- HİBRİT FEATURE'LAR: yildizname, yildizname-result, tarot, tarot-reading,
--                    kahve-fali, kahve-fali-result, ruya-tabiri, ruya-tabiri-result,
--                    sinastri, sinastri-result
--
-- 2026-04-30 — T31 GEO/SEO çalışması: tüm placeholder'lar GoldMoodAstro
-- markası için gerçek değerlerle dolduruldu (TR/EN/DE). OG görselleri
-- admin panelden yüklenebilir; bu seed boş bıraktığı OG'leri Antigravity
-- + müşteri ortak çalışmasıyla zamanla doldurulacak.
-- =============================================================

-- TR ──────────────────────────────────────────────────────────────────────
INSERT INTO site_settings (id, `key`, locale, value) VALUES
('01000000-0000-4000-8000-000000000040', 'seo_pages', 'tr', '{
  "home":                       { "title": "GoldMoodAstro — Profesyonel Astroloji ve Tarot Danışmanlığı", "description": "Türkiye''nin onaylı astrolog, tarot uzmanı ve numerologlarıyla canlı görüşme. Doğum haritası, sinastri, günlük yorum ve kişiye özel rehberlik.", "og_image": "", "no_index": false },
  "birth-chart":                { "title": "Doğum Haritası Hesaplama ve Yorumlama", "description": "Swiss Ephemeris hassasiyetinde doğum haritası analizi. Gezegen pozisyonları, evler, açılar ve uzman astrolog yorumu — hemen başlayın.", "og_image": "", "no_index": false },
  "consultants":                { "title": "Onaylı Astrolog ve Danışman Listesi", "description": "Astroloji, tarot, numeroloji ve spiritüel rehberlik alanında onaylı uzmanlar. Uzmanlık, dil, fiyat ve müsaitlik filtreleyin; canlı görüşme alın.", "og_image": "", "no_index": false },
  "consultant-detail":          { "title": "Danışman Profili ve Randevu", "description": "Danışman profili: uzmanlık, deneyim, dil, hizmet paketleri, müşteri yorumları ve müsaitlik. Anlık veya planlı randevu alın.", "og_image": "", "no_index": false },
  "pricing":                    { "title": "Fiyatlar ve Hizmet Paketleri", "description": "Ücretsiz ön görüşme, 15dk tanışma, 30/60/90dk derinlemesine seans seçenekleri. Şeffaf fiyatlandırma, gizli ücret yok.", "og_image": "", "no_index": false },
  "daily":                      { "title": "Günlük Burç Yorumları — Tüm Burçlar", "description": "12 burç için bugünün aşk, kariyer, sağlık ve genel yorumu. Profesyonel astrologlar tarafından gözden geçirilen günlük rehber.", "og_image": "", "no_index": false },
  "blog":                       { "title": "Astroloji ve Spiritüel Rehberlik Blogu", "description": "Astroloji, tarot, numeroloji ve kişisel gelişim üzerine derinlikli yazılar. Uzman danışmanlardan ipuçları, rehberler ve analizler.", "og_image": "", "no_index": false },
  "blog-post":                  { "title": "GoldMoodAstro Blog Yazısı", "description": "Astroloji ve spiritüel rehberlik üzerine uzman yazıları.", "og_image": "", "no_index": false },
  "about":                      { "title": "Hakkımızda — GoldMoodAstro", "description": "GoldMoodAstro''nun hikayesi, misyonu ve onaylı danışman ekibi. Türkiye''nin güvenilir astroloji ve spiritüel rehberlik platformu.", "og_image": "", "no_index": false },
  "contact":                    { "title": "İletişim ve Destek", "description": "GoldMoodAstro ile iletişime geçin. Sorularınız, danışman başvuruları ve kurumsal işbirlikleri için bizimle bağlantı kurun.", "og_image": "", "no_index": false },
  "faqs":                       { "title": "Sıkça Sorulan Sorular (SSS)", "description": "GoldMoodAstro hakkında en çok merak edilenler: nasıl çalışır, ödeme, gizlilik, danışman seçimi, randevu süreci ve daha fazlası.", "og_image": "", "no_index": false },
  "burclar":                    { "title": "Burçlar — 12 Burç Özellikleri ve Yorumları", "description": "Koç''tan Balık''a 12 burcun özellikleri, uyumu, günlük/haftalık/aylık yorumları. Burcunu öğren, derinlemesine analizini al.", "og_image": "", "no_index": false },
  "burclar-sign":               { "title": "Burç Özellikleri, Yorumları ve Uyumluluk", "description": "Bu burcun karakter özellikleri, güçlü ve zayıf yönleri, ünlüleri, uyumluluk haritası ve uzman astrolog yorumları.", "og_image": "", "no_index": false },
  "burclar-bugun":              { "title": "Bugünün Burç Yorumu", "description": "Bu burç için bugünün aşk, kariyer, sağlık ve genel yorumu. Günü en iyi nasıl değerlendireceğinin profesyonel rehberi.", "og_image": "", "no_index": false },
  "burclar-haftalik":           { "title": "Haftalık Burç Yorumu", "description": "Bu burç için bu haftanın detaylı astrolojik analizi. Aşk, kariyer, finans ve sağlık alanlarında haftalık rehber.", "og_image": "", "no_index": false },
  "burclar-aylik":              { "title": "Aylık Burç Yorumu", "description": "Bu burç için bu ayın gezegen geçişleri, dolunay ve yeni ay etkileri, ay boyunca odaklanılması gereken alanlar.", "og_image": "", "no_index": false },
  "burclar-ask":                { "title": "Aşk Burç Yorumu — İlişki Rehberi", "description": "Bu burcun aşk hayatında bu dönem ne bekliyor? İlişki dinamikleri, partner uyumu, romantik fırsatlar ve uzman tavsiyeleri.", "og_image": "", "no_index": false },
  "burclar-kariyer":            { "title": "Kariyer Burç Yorumu — İş Hayatı Rehberi", "description": "Bu burcun kariyer hayatında dikkat etmesi gerekenler, terfi fırsatları, finansal hareketler ve mesleki rehber.", "og_image": "", "no_index": false },
  "burclar-saglik":             { "title": "Sağlık Burç Yorumu — Beden ve Zihin", "description": "Bu burç için bedensel ve ruhsal sağlık tavsiyeleri. Astroloji penceresinden iyi hissetmek için pratik öneriler.", "og_image": "", "no_index": false },
  "burclar-uyumlulik":          { "title": "Burç Uyumluluk Haritası", "description": "Bu burç hangi burçlarla uyumlu? Aşk, dostluk ve iş ilişkilerinde uyum analizi, çift dinamikleri ve astrologdan tavsiyeler.", "og_image": "", "no_index": false },
  "burclar-meditasyon":         { "title": "Burç Meditasyonu ve Affirmasyonları", "description": "Bu burç için kısa sesli meditasyon, günlük affirmasyonlar ve element odaklı sakinleşme pratiği. Ruhsal denge ve içsel huzur için astroloji.", "og_image": "", "no_index": false },
  "burclar-pair-uyumu":         { "title": "İkili Burç Uyumu Analizi", "description": "İki burç arasındaki astrolojik uyum: sevgili, partner, arkadaş veya iş ortağı. Detaylı element, modalite ve gezegen analizi.", "og_image": "", "no_index": false },
  "burclar-transit":            { "title": "Aylık Gezegen Geçişleri ve Transit Analizi", "description": "Bu ayın gezegen geçişleri, dolunay/yeni ay etkileri ve burçlara genel etkisi. Astrolojik takvim ve uzman yorumları.", "og_image": "", "no_index": false },
  "yukselen-burc-hesaplayici":  { "title": "Yükselen Burç Hesaplayıcı — Anında Sonuç", "description": "Doğum tarihi, saati ve şehir ile yükselen burcunuzu hesaplayın. Yükselen burç anlamı, etkisi ve yorumu hemen.", "og_image": "", "no_index": false },
  "big-three":                  { "title": "Big Three — Güneş, Ay ve Yükselen Burcunuz", "description": "Astrolojinin üç temel direği: güneş burcu (kim olduğun), ay burcu (nasıl hissettiğin), yükselen burç (nasıl göründüğün).", "og_image": "", "no_index": false },
  "yildizname":                 { "title": "Yıldızname — Ebced ile Geleceğin Sırrı", "description": "Klasik Osmanlı astrolojisi yıldızname ile isim ve doğum tarihinden derin analiz. Ebced hesabı ve uzman yorumu.", "og_image": "", "no_index": false },
  "yildizname-result":          { "title": "Yıldızname Sonucunuz", "description": "Kişiye özel yıldızname analizi: karakter, geçmiş, gelecek ve önemli hayat dönüşümleri.", "og_image": "", "no_index": false },
  "tarot":                      { "title": "Tarot Falı — Klasik Rider-Waite ve Daha Fazlası", "description": "Tek kart, üçlü açılım veya Kelt Haçı ile tarot falı. AI destekli sembol yorumu + uzman astrolog danışmanlığı.", "og_image": "", "no_index": false },
  "tarot-reading":              { "title": "Tarot Açılımınızın Yorumu", "description": "Sizin için açılan kartların detaylı analizi. Geçmiş, şimdi ve geleceğe dair sembolik mesajlar.", "og_image": "", "no_index": false },
  "kahve-fali":                 { "title": "Kahve Falı — Geleneksel Türk Kahve Falı Online", "description": "Kahve fincanı fotoğrafınızı yükleyin, AI ve uzman desteğiyle geleneksel kahve falı yorumunuzu alın. Hızlı ve özel.", "og_image": "", "no_index": false },
  "kahve-fali-result":          { "title": "Kahve Falı Sonucunuz", "description": "Fincanınızda görülen sembollerin detaylı yorumu — aşk, kariyer, sağlık ve hayat yolu mesajları.", "og_image": "", "no_index": false },
  "ruya-tabiri":                { "title": "Rüya Tabiri — Rüyanızın Anlamı", "description": "Rüyanızı yazın, İslami ve psikolojik perspektifle yorumunu alın. Sembollerin derin anlamı, uyarılar ve müjdeler.", "og_image": "", "no_index": false },
  "ruya-tabiri-result":         { "title": "Rüya Tabiriniz", "description": "Rüyanızda gördüğünüz sembollerin yorumu, hayatınıza dair olası mesajlar ve rehberlik.", "og_image": "", "no_index": false },
  "sinastri":                   { "title": "Sinastri — İlişki Uyumu Astroloji Analizi", "description": "Sevgili, partner veya arkadaşınızla astrolojik uyumunuzu keşfedin. İki haritanın detaylı kıyaslaması ve uzman yorumu.", "og_image": "", "no_index": false },
  "sinastri-result":            { "title": "Sinastri Analiziniz", "description": "İki haritanın detaylı uyum raporu: aşk, iletişim, çatışma noktaları ve birlikte gelişim alanları.", "og_image": "", "no_index": false }
}'),
-- EN ──────────────────────────────────────────────────────────────────────
('01000000-0000-4000-8000-000000000041', 'seo_pages', 'en', '{
  "home":                       { "title": "GoldMoodAstro — Professional Astrology & Tarot Consultations", "description": "Türkiye''s verified astrologers, tarot readers and numerologists. Live audio/video sessions, birth charts, synastry, daily readings and personal guidance.", "og_image": "", "no_index": false },
  "birth-chart":                { "title": "Birth Chart Calculator & Interpretation", "description": "Swiss Ephemeris-precision natal chart analysis. Planet positions, houses, aspects and expert astrologer interpretation — start now.", "og_image": "", "no_index": false },
  "consultants":                { "title": "Verified Astrologers & Spiritual Consultants", "description": "Verified experts in astrology, tarot, numerology and spiritual guidance. Filter by expertise, language, price and availability; book live sessions.", "og_image": "", "no_index": false },
  "consultant-detail":          { "title": "Consultant Profile & Booking", "description": "Consultant profile: expertise, experience, languages, service packages, client reviews and availability. Book instant or scheduled sessions.", "og_image": "", "no_index": false },
  "pricing":                    { "title": "Pricing & Service Packages", "description": "Free intro chats, 15-minute introductions, 30/60/90-minute deep sessions. Transparent pricing — no hidden fees.", "og_image": "", "no_index": false },
  "daily":                      { "title": "Daily Horoscopes — All 12 Zodiac Signs", "description": "Today''s love, career, health and general reading for all 12 zodiac signs. Daily guidance reviewed by professional astrologers.", "og_image": "", "no_index": false },
  "blog":                       { "title": "Astrology & Spiritual Guidance Blog", "description": "In-depth articles on astrology, tarot, numerology and personal growth. Tips, guides and analyses from expert consultants.", "og_image": "", "no_index": false },
  "blog-post":                  { "title": "GoldMoodAstro Blog Article", "description": "Expert articles on astrology and spiritual guidance.", "og_image": "", "no_index": false },
  "about":                      { "title": "About — GoldMoodAstro", "description": "GoldMoodAstro''s story, mission and verified consultant team. Türkiye''s trusted astrology and spiritual guidance platform.", "og_image": "", "no_index": false },
  "contact":                    { "title": "Contact & Support", "description": "Get in touch with GoldMoodAstro. Questions, consultant applications and corporate partnerships — connect with us.", "og_image": "", "no_index": false },
  "faqs":                       { "title": "Frequently Asked Questions (FAQ)", "description": "Most asked about GoldMoodAstro: how it works, payment, privacy, choosing a consultant, booking process and more.", "og_image": "", "no_index": false },
  "burclar":                    { "title": "Zodiac Signs — All 12 Signs Profile & Readings", "description": "From Aries to Pisces — characteristics, compatibility, daily/weekly/monthly horoscopes. Discover your sign, get a deep analysis.", "og_image": "", "no_index": false },
  "burclar-sign":               { "title": "Zodiac Sign Profile, Horoscope & Compatibility", "description": "This sign''s personality traits, strengths and weaknesses, famous people, compatibility map and expert astrologer commentary.", "og_image": "", "no_index": false },
  "burclar-bugun":              { "title": "Today''s Horoscope", "description": "Today''s love, career, health and general reading for this sign. Professional guidance for making the most of your day.", "og_image": "", "no_index": false },
  "burclar-haftalik":           { "title": "Weekly Horoscope", "description": "Detailed astrological analysis for this sign''s week ahead. Love, career, finance and health weekly guidance.", "og_image": "", "no_index": false },
  "burclar-aylik":              { "title": "Monthly Horoscope", "description": "Planet transits, full moon and new moon effects, key focus areas for this sign''s month.", "og_image": "", "no_index": false },
  "burclar-ask":                { "title": "Love Horoscope — Relationship Guide", "description": "What awaits this sign in love? Relationship dynamics, partner compatibility, romantic opportunities and expert advice.", "og_image": "", "no_index": false },
  "burclar-kariyer":            { "title": "Career Horoscope — Work Life Guide", "description": "Career considerations, promotion opportunities, financial movements and professional guidance for this sign.", "og_image": "", "no_index": false },
  "burclar-saglik":             { "title": "Health Horoscope — Body and Mind", "description": "Physical and emotional health tips for this sign. Practical recommendations for well-being from an astrology lens.", "og_image": "", "no_index": false },
  "burclar-uyumlulik":          { "title": "Zodiac Compatibility Map", "description": "Which signs are compatible with this one? Love, friendship and work compatibility analysis with astrologer recommendations.", "og_image": "", "no_index": false },
  "burclar-meditasyon":         { "title": "Zodiac Meditation & Affirmations", "description": "Short audio meditation, daily affirmations and element-focused calming practice for this zodiac sign. Spiritual balance through astrology.", "og_image": "", "no_index": false },
  "burclar-pair-uyumu":         { "title": "Pairwise Zodiac Compatibility", "description": "Astrological compatibility between two signs: lovers, partners, friends or business partners. Detailed element, modality and planet analysis.", "og_image": "", "no_index": false },
  "burclar-transit":            { "title": "Monthly Planet Transits & Astrological Forecast", "description": "This month''s planet transits, full/new moon effects and overall impact on all signs. Astrological calendar and expert commentary.", "og_image": "", "no_index": false },
  "yukselen-burc-hesaplayici":  { "title": "Rising Sign Calculator — Instant Result", "description": "Calculate your rising sign with date, time and city of birth. Meaning, influence and interpretation of your rising sign — instantly.", "og_image": "", "no_index": false },
  "big-three":                  { "title": "Big Three — Sun, Moon and Rising Sign", "description": "The three pillars of astrology: sun sign (who you are), moon sign (how you feel), rising sign (how you appear).", "og_image": "", "no_index": false },
  "yildizname":                 { "title": "Yildizname — Ottoman Astrology with Ebjed", "description": "Classical Ottoman astrology yildizname with deep analysis from name and birth date. Ebjed calculation and expert interpretation.", "og_image": "", "no_index": false },
  "yildizname-result":          { "title": "Your Yildizname Reading", "description": "Personal yildizname analysis: character, past, future and key life transformations.", "og_image": "", "no_index": false },
  "tarot":                      { "title": "Tarot Reading — Rider-Waite & More", "description": "Single card, three-card or Celtic Cross tarot reading. AI-assisted symbol interpretation + expert astrologer consultation.", "og_image": "", "no_index": false },
  "tarot-reading":              { "title": "Your Tarot Spread Reading", "description": "Detailed analysis of the cards drawn for you. Symbolic messages about past, present and future.", "og_image": "", "no_index": false },
  "kahve-fali":                 { "title": "Coffee Reading — Traditional Turkish Coffee Fortune Online", "description": "Upload your coffee cup photo, receive traditional Turkish coffee reading with AI and expert support. Fast and personal.", "og_image": "", "no_index": false },
  "kahve-fali-result":          { "title": "Your Coffee Reading", "description": "Detailed interpretation of symbols seen in your cup — love, career, health and life path messages.", "og_image": "", "no_index": false },
  "ruya-tabiri":                { "title": "Dream Interpretation — Meaning of Your Dream", "description": "Write down your dream, get its interpretation from Islamic and psychological perspectives. Deep meaning of symbols, warnings and good news.", "og_image": "", "no_index": false },
  "ruya-tabiri-result":         { "title": "Your Dream Interpretation", "description": "Interpretation of symbols in your dream and possible messages for your life.", "og_image": "", "no_index": false },
  "sinastri":                   { "title": "Synastry — Relationship Compatibility Astrology", "description": "Discover astrological compatibility with your partner, lover or friend. Detailed comparison of two charts with expert interpretation.", "og_image": "", "no_index": false },
  "sinastri-result":            { "title": "Your Synastry Analysis", "description": "Detailed compatibility report of two charts: love, communication, points of friction and shared growth areas.", "og_image": "", "no_index": false }
}'),
-- DE ──────────────────────────────────────────────────────────────────────
('01000000-0000-4000-8000-000000000042', 'seo_pages', 'de', '{
  "home":                       { "title": "GoldMoodAstro — Professionelle Astrologie- und Tarot-Beratung", "description": "Verifizierte Astrologen, Tarotleser und Numerologen aus der Türkei. Live-Sitzungen, Geburtshoroskope, Synastrie, Tageshoroskope und persönliche Beratung.", "og_image": "", "no_index": false },
  "birth-chart":                { "title": "Geburtshoroskop berechnen und deuten", "description": "Geburtshoroskop-Analyse mit Swiss Ephemeris-Präzision. Planetenpositionen, Häuser, Aspekte und Experteninterpretation — jetzt starten.", "og_image": "", "no_index": false },
  "consultants":                { "title": "Verifizierte Astrologen & spirituelle Berater", "description": "Verifizierte Experten in Astrologie, Tarot, Numerologie und spiritueller Beratung. Filtere nach Fachgebiet, Sprache, Preis; buche Live-Sitzungen.", "og_image": "", "no_index": false },
  "consultant-detail":          { "title": "Berater-Profil & Buchung", "description": "Beraterprofil: Fachgebiet, Erfahrung, Sprachen, Servicepakete, Kundenbewertungen und Verfügbarkeit. Sofortige oder geplante Termine buchen.", "og_image": "", "no_index": false },
  "pricing":                    { "title": "Preise & Service-Pakete", "description": "Kostenlose Vorgespräche, 15-Minuten-Einführungen, 30/60/90-Minuten-Tiefensitzungen. Transparente Preise — keine versteckten Gebühren.", "og_image": "", "no_index": false },
  "daily":                      { "title": "Tageshoroskope — Alle 12 Sternzeichen", "description": "Heutige Liebe, Karriere, Gesundheit und allgemeine Deutung für alle 12 Sternzeichen. Tägliche Beratung von Profi-Astrologen geprüft.", "og_image": "", "no_index": false },
  "blog":                       { "title": "Astrologie & spirituelle Beratung Blog", "description": "Tiefgehende Artikel zu Astrologie, Tarot, Numerologie und persönlichem Wachstum. Tipps, Anleitungen und Analysen von Experten.", "og_image": "", "no_index": false },
  "blog-post":                  { "title": "GoldMoodAstro Blog-Artikel", "description": "Experten-Artikel zu Astrologie und spiritueller Beratung.", "og_image": "", "no_index": false },
  "about":                      { "title": "Über uns — GoldMoodAstro", "description": "Die Geschichte, Mission und das verifizierte Beraterteam von GoldMoodAstro. Die vertrauenswürdige Astrologie-Plattform der Türkei.", "og_image": "", "no_index": false },
  "contact":                    { "title": "Kontakt & Support", "description": "Nimm Kontakt mit GoldMoodAstro auf. Fragen, Berater-Bewerbungen und Geschäftspartnerschaften — verbinde dich mit uns.", "og_image": "", "no_index": false },
  "faqs":                       { "title": "Häufig gestellte Fragen (FAQ)", "description": "Häufigste Fragen zu GoldMoodAstro: Funktionsweise, Zahlung, Datenschutz, Beraterauswahl, Buchungsprozess und mehr.", "og_image": "", "no_index": false },
  "burclar":                    { "title": "Sternzeichen — Profile & Deutungen aller 12 Zeichen", "description": "Vom Widder bis zur Fische — Eigenschaften, Kompatibilität, Tages-/Wochen-/Monatshoroskope. Entdecke dein Zeichen, hol dir eine tiefe Analyse.", "og_image": "", "no_index": false },
  "burclar-sign":               { "title": "Sternzeichen-Profil, Horoskop & Kompatibilität", "description": "Persönlichkeitsmerkmale dieses Zeichens, Stärken und Schwächen, berühmte Personen, Kompatibilitätskarte und Astrologen-Kommentar.", "og_image": "", "no_index": false },
  "burclar-bugun":              { "title": "Tageshoroskop", "description": "Heutige Liebe, Karriere, Gesundheit und allgemeine Deutung für dieses Zeichen. Profi-Beratung, um den Tag bestmöglich zu nutzen.", "og_image": "", "no_index": false },
  "burclar-haftalik":           { "title": "Wochenhoroskop", "description": "Detaillierte astrologische Analyse für die kommende Woche dieses Zeichens. Liebe, Karriere, Finanzen und Gesundheit.", "og_image": "", "no_index": false },
  "burclar-aylik":              { "title": "Monatshoroskop", "description": "Planeten-Transite, Vollmond- und Neumond-Effekte, wichtige Fokusbereiche für den Monat dieses Zeichens.", "og_image": "", "no_index": false },
  "burclar-ask":                { "title": "Liebes-Horoskop — Beziehungsratgeber", "description": "Was erwartet dieses Zeichen in der Liebe? Beziehungsdynamiken, Partnerkompatibilität, romantische Chancen und Expertenrat.", "og_image": "", "no_index": false },
  "burclar-kariyer":            { "title": "Karriere-Horoskop — Berufsleben Ratgeber", "description": "Karriereüberlegungen, Beförderungschancen, Finanzbewegungen und beruflicher Leitfaden für dieses Zeichen.", "og_image": "", "no_index": false },
  "burclar-saglik":             { "title": "Gesundheits-Horoskop — Körper und Geist", "description": "Tipps für körperliche und emotionale Gesundheit dieses Zeichens. Praktische Empfehlungen aus astrologischer Sicht.", "og_image": "", "no_index": false },
  "burclar-uyumlulik":          { "title": "Sternzeichen-Kompatibilitätskarte", "description": "Mit welchen Zeichen ist dieses Zeichen kompatibel? Analyse für Liebe, Freundschaft und Arbeit mit Astrologen-Empfehlungen.", "og_image": "", "no_index": false },
  "burclar-meditasyon":         { "title": "Sternzeichen-Meditation & Affirmationen", "description": "Kurze Audio-Meditation, tägliche Affirmationen und elementbezogene Beruhigungspraxis für dieses Sternzeichen. Spirituelles Gleichgewicht durch Astrologie.", "og_image": "", "no_index": false },
  "burclar-pair-uyumu":         { "title": "Paarweise Sternzeichen-Kompatibilität", "description": "Astrologische Kompatibilität zwischen zwei Zeichen: Liebende, Partner, Freunde oder Geschäftspartner. Detaillierte Element-, Modalitäts- und Planetenanalyse.", "og_image": "", "no_index": false },
  "burclar-transit":            { "title": "Monatliche Planeten-Transite & astrologische Vorhersage", "description": "Planeten-Transite dieses Monats, Voll-/Neumondeffekte und Auswirkungen auf alle Zeichen. Astrologischer Kalender und Expertenkommentar.", "og_image": "", "no_index": false },
  "yukselen-burc-hesaplayici":  { "title": "Aszendent-Rechner — Sofortiges Ergebnis", "description": "Berechne deinen Aszendenten mit Geburtsdatum, -zeit und -ort. Bedeutung, Einfluss und Deutung deines Aszendenten — sofort.", "og_image": "", "no_index": false },
  "big-three":                  { "title": "Big Three — Sonne, Mond und Aszendent", "description": "Die drei Säulen der Astrologie: Sonnenzeichen (wer du bist), Mondzeichen (wie du fühlst), Aszendent (wie du wirkst).", "og_image": "", "no_index": false },
  "yildizname":                 { "title": "Yildizname — Osmanische Astrologie mit Ebjed", "description": "Klassische osmanische Astrologie Yildizname mit tiefer Analyse aus Name und Geburtsdatum. Ebjed-Berechnung und Experteninterpretation.", "og_image": "", "no_index": false },
  "yildizname-result":          { "title": "Deine Yildizname-Lesung", "description": "Persönliche Yildizname-Analyse: Charakter, Vergangenheit, Zukunft und wichtige Lebensumwandlungen.", "og_image": "", "no_index": false },
  "tarot":                      { "title": "Tarot-Lesung — Rider-Waite & mehr", "description": "Einzelkarte, Dreikarte oder Keltisches Kreuz Tarot-Lesung. KI-gestützte Symbolinterpretation + Expertenberatung.", "og_image": "", "no_index": false },
  "tarot-reading":              { "title": "Deine Tarot-Auslegung", "description": "Detaillierte Analyse der für dich gezogenen Karten. Symbolische Botschaften über Vergangenheit, Gegenwart und Zukunft.", "og_image": "", "no_index": false },
  "kahve-fali":                 { "title": "Kaffeesatz-Lesung — Traditionelle Türkische Online", "description": "Lade dein Kaffeesatz-Foto hoch, erhalte traditionelle türkische Kaffeesatzlesung mit KI- und Expertenunterstützung.", "og_image": "", "no_index": false },
  "kahve-fali-result":          { "title": "Deine Kaffeesatz-Lesung", "description": "Detaillierte Interpretation der Symbole in deiner Tasse — Liebe, Karriere, Gesundheit und Lebensweg-Botschaften.", "og_image": "", "no_index": false },
  "ruya-tabiri":                { "title": "Traumdeutung — Bedeutung deines Traums", "description": "Schreibe deinen Traum auf, erhalte seine Deutung aus islamischen und psychologischen Perspektiven. Tiefe Bedeutung von Symbolen, Warnungen und gute Nachrichten.", "og_image": "", "no_index": false },
  "ruya-tabiri-result":         { "title": "Deine Traumdeutung", "description": "Deutung der Symbole in deinem Traum und mögliche Botschaften für dein Leben.", "og_image": "", "no_index": false },
  "sinastri":                   { "title": "Synastrie — Beziehungs-Kompatibilität Astrologie", "description": "Entdecke die astrologische Kompatibilität mit Partner, Geliebten oder Freund. Detaillierter Vergleich zweier Horoskope mit Experteninterpretation.", "og_image": "", "no_index": false },
  "sinastri-result":            { "title": "Deine Synastrie-Analyse", "description": "Detaillierter Kompatibilitätsbericht zweier Horoskope: Liebe, Kommunikation, Reibungspunkte und gemeinsame Wachstumsbereiche.", "og_image": "", "no_index": false }
}')
ON DUPLICATE KEY UPDATE value = VALUES(value);
