-- =============================================================
-- FILE: 018_ui_admin_config_seed.sql
-- Admin panel branding (ui_admin_config) + brand_media tab'in
-- bekledigi eksik media key'leri.
--
-- ui_admin_config:
--   admin_panel/src/app/(main)/admin/(admin)/site-settings/tabs/branding-settings-tab.tsx
--   tab'i bu key altindaki `branding` alt-objesini okur/yazar.
--   SaaS musteri admin paneli icindeki marka kimligini buradan yonetir.
--
-- Media key'leri:
--   admin_panel/.../tabs/brand-media-tab.tsx
--   public site (frontend/mobile) icin. JSON format: {"url":"..."}
--   site_logo_dark + site_favicon zaten 010'da bos string olarak var,
--   burada JSON format'a guncelliyoruz.
-- =============================================================

INSERT INTO site_settings (id, `key`, locale, value) VALUES
-- Admin panel branding (default'lar -- GoldMoodAstro tema)
('01800000-0000-4000-8000-000000000001', 'ui_admin_config', '*',
 '{"branding":{"app_name":"GoldMoodAstro Admin","app_copyright":"GoldMoodAstro","html_lang":"tr","theme_color":"#C9A961","favicon_16":"/favicon/favicon-16.svg","favicon_32":"/favicon/favicon-32.svg","apple_touch_icon":"/favicon/apple-touch-icon.svg","meta":{"title":"GoldMoodAstro Admin","description":"GoldMoodAstro yonetim paneli","og_url":"https://admin.goldmoodastro.com","og_title":"GoldMoodAstro Admin","og_description":"GoldMoodAstro yonetim paneli","og_image":"","twitter_card":"summary_large_image"}}}'),

-- Public site media (brand-media-tab.tsx eksik key'leri)
('01800000-0000-4000-8000-000000000002', 'site_logo',                '*', '{"url":""}'),
('01800000-0000-4000-8000-000000000003', 'site_logo_light',          '*', '{"url":""}'),
('01800000-0000-4000-8000-000000000004', 'site_og_default_image',    '*', '{"url":""}'),
('01800000-0000-4000-8000-000000000005', 'site_appointment_cover',   '*', '{"url":""}'),

-- 010'daki bos string'leri JSON format'a normalize et
('01800000-0000-4000-8000-000000000006', 'site_logo_dark',           '*', '{"url":""}'),
('01800000-0000-4000-8000-000000000007', 'site_favicon',             '*', '{"url":""}'),

-- Admin Page Meta (ui_admin_pages) -- Sayfa basliklari ve aciklamalari (404 hatasi cozumu)
-- Admin Page Meta (ui_admin_pages) -- Sayfa basliklari ve aciklamalari (404 hatasi cozumu)
('01800000-0000-4000-8000-000000000100', 'ui_admin_pages', '*', '{"dashboard":{"title":"Panel","description":"Sistem genel özeti"},"consultants":{"title":"Danışmanlar","description":"Danışman yönetimi"},"users":{"title":"Kullanıcılar","description":"Kullanıcı yönetimi"},"bookings":{"title":"Randevular","description":"Randevu takvimi"},"orders":{"title":"Siparişler","description":"Sipariş yönetimi"},"site_settings":{"title":"Ayarlar","description":"Sistem konfigürasyonu"},"reviews":{"title":"Yorumlar","description":"Müşteri yorumları"},"mail":{"title":"E-Posta","description":"E-posta gönderimi"},"email_templates":{"title":"Şablonlar","description":"E-posta şablonları"},"notifications":{"title":"Bildirimler","description":"Push bildirimler"},"storage":{"title":"Dosyalar","description":"Medya kütüphanesi"},"db":{"title":"Veritabanı","description":"Yedekleme ve import"},"audit":{"title":"Denetim","description":"Sistem logları"},"availability":{"title":"Saatler","description":"Çalışma saatleri"},"support":{"title":"Destek","description":"Destek talepleri"},"chat":{"title":"Chat","description":"AI ve sohbet"},"wallet":{"title":"Cüzdan","description":"Finansal yönetim"},"payment_settings":{"title":"Ödeme","description":"Pos ayarları"},"announcements":{"title":"Duyurular","description":"Sistem duyuruları"},"subscriptions":{"title":"Abonelikler","description":"Abone yönetimi"},"subscription_plans":{"title":"Planlar","description":"Üyelik paketleri"},"cache":{"title":"Cache","description":"Önbellek temizleme"},"llm_prompts":{"title":"Prompts","description":"AI prompt ayarları"},"astrology_kb":{"title":"Bilgi Bankası","description":"Astroloji verileri"},"banners":{"title":"Bannerlar","description":"Slider yönetimi"},"campaigns":{"title":"Kampanyalar","description":"Pazarlama yönetimi"},"navigation":{"title":"Menü","description":"Menü ve Footer"},"home_layout":{"title":"Anasayfa","description":"Sayfa düzeni"}}'),
('01800000-0000-4000-8000-000000000101', 'ui_admin_pages', 'tr', '{"dashboard":{"title":"Panel","description":"Sistem genel özeti"},"consultants":{"title":"Danışmanlar","description":"Danışman yönetimi"},"users":{"title":"Kullanıcılar","description":"Kullanıcı yönetimi"},"bookings":{"title":"Randevular","description":"Randevu takvimi"},"orders":{"title":"Siparişler","description":"Sipariş yönetimi"},"site_settings":{"title":"Ayarlar","description":"Sistem konfigürasyonu"},"reviews":{"title":"Yorumlar","description":"Müşteri yorumları"},"mail":{"title":"E-Posta","description":"E-posta gönderimi"},"email_templates":{"title":"Şablonlar","description":"E-posta şablonları"},"notifications":{"title":"Bildirimler","description":"Push bildirimler"},"storage":{"title":"Dosyalar","description":"Medya kütüphanesi"},"db":{"title":"Veritabanı","description":"Yedekleme ve import"},"audit":{"title":"Denetim","description":"Sistem logları"},"availability":{"title":"Saatler","description":"Çalışma saatleri"},"support":{"title":"Destek","description":"Destek talepleri"},"chat":{"title":"Chat","description":"AI ve sohbet"},"wallet":{"title":"Cüzdan","description":"Finansal yönetim"},"payment_settings":{"title":"Ödeme","description":"Pos ayarları"},"announcements":{"title":"Duyurular","description":"Sistem duyuruları"},"subscriptions":{"title":"Abonelikler","description":"Abone yönetimi"},"subscription_plans":{"title":"Planlar","description":"Üyelik paketleri"},"cache":{"title":"Cache","description":"Önbellek temizleme"},"llm_prompts":{"title":"Prompts","description":"AI prompt ayarları"},"astrology_kb":{"title":"Bilgi Bankası","description":"Astroloji verileri"},"banners":{"title":"Bannerlar","description":"Slider yönetimi"},"campaigns":{"title":"Kampanyalar","description":"Pazarlama yönetimi"},"navigation":{"title":"Menü","description":"Menü ve Footer"},"home_layout":{"title":"Anasayfa","description":"Sayfa düzeni"}}'),
('01800000-0000-4000-8000-000000000102', 'ui_admin_pages', 'en', '{"dashboard":{"title":"Dashboard","description":"System overview"},"consultants":{"title":"Consultants","description":"Manage consultants"},"users":{"title":"Users","description":"Manage users"},"bookings":{"title":"Bookings","description":"Booking calendar"},"orders":{"title":"Orders","description":"Order management"},"site_settings":{"title":"Settings","description":"System configuration"},"reviews":{"title":"Reviews","description":"Customer reviews"},"mail":{"title":"Mail","description":"Send emails"},"email_templates":{"title":"Templates","description":"Email templates"},"notifications":{"title":"Notifications","description":"Push notifications"},"storage":{"title":"Files","description":"Media library"},"db":{"title":"Database","description":"Backup and import"},"audit":{"title":"Audit","description":"System logs"},"availability":{"title":"Hours","description":"Work hours"},"support":{"title":"Support","description":"Support tickets"},"chat":{"title":"Chat","description":"AI and chat"},"wallet":{"title":"Wallet","description":"Financial management"},"payment_settings":{"title":"Payment","description":"POS settings"},"announcements":{"title":"Announcements","description":"System announcements"},"subscriptions":{"title":"Subscriptions","description":"Subscriber management"},"subscription_plans":{"title":"Plans","description":"Membership plans"},"cache":{"title":"Cache","description":"Clear cache"},"llm_prompts":{"title":"Prompts","description":"AI prompt settings"},"astrology_kb":{"title":"Knowledge Base","description":"Astrology data"},"banners":{"title":"Banners","description":"Slider management"},"campaigns":{"title":"Campaigns","description":"Marketing management"},"navigation":{"title":"Menu","description":"Menu and Footer"},"home_layout":{"title":"Home","description":"Page layout"}}'),
('01800000-0000-4000-8000-000000000103', 'ui_admin_pages', 'de', '{"dashboard":{"title":"Dashboard","description":"Systemübersicht"},"consultants":{"title":"Berater","description":"Berater verwalten"},"users":{"title":"Benutzer","description":"Benutzer verwalten"},"bookings":{"title":"Buchungen","description":"Buchungskalender"},"orders":{"title":"Bestellungen","description":"Bestellverwaltung"},"site_settings":{"title":"Einstellungen","description":"Systemkonfiguration"},"reviews":{"title":"Bewertungen","description":"Kundenbewertungen"},"mail":{"title":"E-Mail","description":"E-Mails senden"},"email_templates":{"title":"Vorlagen","description":"E-Mail-Vorlagen"},"notifications":{"title":"Benachrichtigungen","description":"Push-Benachrichtigungen"},"storage":{"title":"Dateien","description":"Medienbibliothek"},"db":{"title":"Datenbank","description":"Backup und Import"},"audit":{"title":"Audit","description":"Systemprotokolle"},"availability":{"title":"Stunden","description":"Arbeitszeiten"},"support":{"title":"Support","description":"Support-Tickets"},"chat":{"title":"Chat","description":"KI und Chat"},"wallet":{"title":"Brieftasche","description":"Finanzmanagement"},"payment_settings":{"title":"Zahlung","description":"POS-Einstellungen"},"announcements":{"title":"Ankündigungen","description":"Systemankündigungen"},"subscriptions":{"title":"Abonnements","description":"Abonnentenverwaltung"},"subscription_plans":{"title":"Pläne","description":"Mitgliedschaftspläne"},"cache":{"title":"Cache","description":"Cache leeren"},"llm_prompts":{"title":"Prompts","description":"KI-Prompt-Einstellungen"},"astrology_kb":{"title":"Wissensdatenbank","description":"Astrologie-Daten"},"banners":{"title":"Banner","description":"Slider-Verwaltung"},"campaigns":{"title":"Kampagnen","description":"Marketing-Management"},"navigation":{"title":"Menü","description":"Menü und Footer"},"home_layout":{"title":"Startseite","description":"Seitenlayout"}}'),

-- Missing shared keys for admin panel initial load
('01800000-0000-4000-8000-000000000201', 'app-locales', '*', '["tr","en","de"]'),
('01800000-0000-4000-8000-000000000202', 'default-locale', '*', 'tr'),

-- UI Header Translations
('01800000-0000-4000-8000-000000000301', 'ui_header', 'tr', '{"ui_header_cta":"DANIŞMAN BUL","ui_header_login":"Giriş Yap","ui_header_register":"Kayıt Ol","ui_header_dashboard":"Panelim"}'),
('01800000-0000-4000-8000-000000000302', 'ui_header', 'en', '{"ui_header_cta":"FIND EXPERT","ui_header_login":"Sign In","ui_header_register":"Sign Up","ui_header_dashboard":"My Dashboard"}'),
('01800000-0000-4000-8000-000000000303', 'ui_header', 'de', '{"ui_header_cta":"BERATER FINDEN","ui_header_login":"Anmelden","ui_header_register":"Registrieren","ui_header_dashboard":"Mein Dashboard"}'),

-- UI Footer Translations
('01800000-0000-4000-8000-000000000401', 'ui_footer', 'tr', '{"ui_footer_about":"Hakkımızda","ui_footer_contact":"İletişim","ui_footer_privacy":"Gizlilik Politikası","ui_footer_terms":"Kullanım Şartları"}'),
('01800000-0000-4000-8000-000000000402', 'ui_footer', 'en', '{"ui_footer_about":"About Us","ui_footer_contact":"Contact","ui_footer_privacy":"Privacy Policy","ui_footer_terms":"Terms of Service"}'),
('01800000-0000-4000-8000-000000000403', 'ui_footer', 'de', '{"ui_footer_about":"Über uns","ui_footer_contact":"Kontakt","ui_footer_privacy":"Datenschutz","ui_footer_terms":"Nutzungsbedingungen"}')
ON DUPLICATE KEY UPDATE value = VALUES(value);
