CREATE TABLE IF NOT EXISTS consultants (
  id CHAR(36) PRIMARY KEY,
  user_id CHAR(36) NOT NULL UNIQUE,
  slug VARCHAR(100) UNIQUE,
  bio TEXT,
  expertise JSON,
  languages JSON,
  meeting_platforms JSON,
  social_links JSON,
  bank_name VARCHAR(120) NULL,
  bank_iban VARCHAR(64) NULL,
  bank_account_holder VARCHAR(160) NULL,
  account_type ENUM('individual','company') NULL,
  identity_number VARCHAR(11) NULL,
  tax_number VARCHAR(11) NULL,
  tax_office VARCHAR(120) NULL,
  company_name VARCHAR(200) NULL,
  billing_address TEXT NULL,
  kyc_status ENUM('none','pending','approved','rejected') DEFAULT 'none',
  kyc_submitted_at DATETIME(3) NULL,
  kyc_reviewed_at DATETIME(3) NULL,
  kyc_rejection_reason TEXT NULL,
  kyc_documents JSON NULL,
  agreement_accepted_at DATETIME(3) NULL,
  commission_change_announcement_sent_at DATETIME(3) NULL DEFAULT NULL,
  session_price DECIMAL(10,2) NOT NULL,
  session_duration INT NOT NULL DEFAULT 30,
  supports_video TINYINT DEFAULT 0,
  video_session_price DECIMAL(10,2),
  currency CHAR(3) DEFAULT 'TRY',
  approval_status ENUM('pending','approved','rejected') DEFAULT 'pending',
  rejection_reason TEXT,
  is_available TINYINT DEFAULT 1,
  rating_avg DECIMAL(3,2) DEFAULT 0.00,
  rating_count INT DEFAULT 0,
  total_sessions INT DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY consultants_approval_idx (approval_status),
  KEY consultants_slug_idx (slug),
  CONSTRAINT fk_consultants_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
