CREATE TABLE IF NOT EXISTS geocode_cache (
  id CHAR(36) PRIMARY KEY,
  q VARCHAR(255) NOT NULL,
  lat DECIMAL(9,6) NOT NULL,
  lng DECIMAL(9,6) NOT NULL,
  label VARCHAR(500) NOT NULL,
  ttl DATETIME NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY geocode_cache_q_uq (q),
  INDEX geocode_cache_ttl_idx (ttl)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
