CREATE TABLE IF NOT EXISTS services_i18n (
  id CHAR(36) PRIMARY KEY,
  service_id CHAR(36) NOT NULL,
  locale VARCHAR(8) NOT NULL,
  name VARCHAR(255) NOT NULL,
  slug VARCHAR(255),
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  UNIQUE KEY services_i18n_service_locale_uq (service_id, locale)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS bookings (
  id CHAR(36) PRIMARY KEY,
  user_id CHAR(36) NOT NULL,
  name VARCHAR(120) NOT NULL,
  email VARCHAR(190) NOT NULL,
  phone VARCHAR(32) NOT NULL,
  locale VARCHAR(10) NOT NULL DEFAULT 'tr',
  customer_message TEXT,
  consultant_id CHAR(36) NOT NULL,
  order_id CHAR(36),
  service_id CHAR(36),
  resource_id CHAR(36) NOT NULL,
  slot_id CHAR(36),
  appointment_date VARCHAR(10) NOT NULL,
  appointment_time VARCHAR(5),
  session_duration TINYINT NOT NULL DEFAULT 30,
  session_price VARCHAR(12) NOT NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'pending_payment',
  is_read TINYINT UNSIGNED NOT NULL DEFAULT 0,
  customer_note TEXT,
  admin_note TEXT,
  decision_note TEXT,
  decided_by VARCHAR(120),
  email_last_sent_at DATETIME(3),
  email_last_template_key VARCHAR(120),
  email_last_to VARCHAR(190),
  email_last_subject VARCHAR(255),
  email_last_error TEXT,
  reminder_24h_sent TINYINT NOT NULL DEFAULT 0,
  reminder_2h_sent TINYINT NOT NULL DEFAULT 0,
  reminder_15m_sent TINYINT NOT NULL DEFAULT 0,
  decided_at DATETIME(3),
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  KEY bookings_user_idx (user_id),
  KEY bookings_consultant_idx (consultant_id),
  KEY bookings_resource_idx (resource_id),
  KEY bookings_service_idx (service_id),
  KEY bookings_slot_idx (slot_id),
  KEY bookings_status_idx (status),
  KEY bookings_date_idx (appointment_date),
  KEY bookings_resource_date_idx (resource_id, appointment_date, appointment_time),
  CONSTRAINT fk_bookings_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_bookings_consultant FOREIGN KEY (consultant_id) REFERENCES consultants(id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_bookings_resource FOREIGN KEY (resource_id) REFERENCES resources(id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_bookings_slot FOREIGN KEY (slot_id) REFERENCES resource_slots(id) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
