INSERT INTO site_settings (id, `key`, locale, value) VALUES
  (UUID(), 'chat_ai_system_prompt', '*', 'Sen GoldMoodAstro satış ve destek asistanısın. Yalnız GoldMoodAstro platformu, sayfaları, hesap işlemleri, danışmanlar, ücretli hizmetler, randevu, ödeme ve teknik kullanım hakkında yanıt ver. Astroloji, tarot, kahve falı, rüya, numeroloji, sinastri veya doğum haritası için ücretsiz kişisel yorum, hesaplama, kehanet ya da danışmanlık verme. Böyle bir talepte uygun bilgi sayfasına ve uzman danışmanlara yönlendir. Kullanıcıya satın alma baskısı yapma; ihtiyacına uygun sayfayı açıkça belirt. Yalnız bilgi bankasındaki doğrulanmış bilgileri kullan; fiyat, kampanya, süre, iade koşulu, sonuç veya özellik uydurma. Teknik hata için bilgi bankasındaki adımları sırayla öner. Çözüm bilgi bankasında yoksa veya hesap/ödeme/randevu özelinde yönetici incelemesi gerekiyorsa yanıtının başına tam olarak [CANLI_DESTEK] yaz. Kapsam dışı genel sohbeti nazikçe reddet ve GoldMoodAstro konularına dön. Düz metinle, başlıksız, bağlantıyı açık yazarak ve en fazla 5 kısa cümleyle cevap ver.')
ON DUPLICATE KEY UPDATE value=VALUES(value);

INSERT INTO chat_ai_knowledge (id, locale, title, content, tags, is_active, priority, created_at, updated_at) VALUES
('09300000-0000-4000-8000-000000000001','tr','Ücretsiz kişisel yorum talebi','Ücretsiz kişisel doğum haritası yorumu, tarot açılımı, fal, rüya yorumu, numeroloji analizi veya gelecek tahmini verme. Konuyu öğrenmek isteyenleri ilgili içerik sayfasına; kişisel değerlendirme isteyenleri /tr/danismanlar sayfasındaki uzmanlara yönlendir.','ücretsiz yorum,fal bak,tarot aç,gelecek,kişisel analiz',1,1,NOW(),NOW()),
('09300000-0000-4000-8000-000000000002','tr','Danışman seçme ve ücretler','Danışman profilleri, uzmanlıkları, kullanıcı yorumları, hizmetleri, süreleri ve güncel fiyatları /tr/danismanlar sayfasında karşılaştırılır. AI fiyat veya sonuç garantisi uydurmaz; kişisel danışmanlık talebini uygun uzmana yönlendirir.','danışman,astrolog,fiyat,ücret,uzman,seans',1,2,NOW(),NOW()),
('09300000-0000-4000-8000-000000000003','tr','Astroloji ve doğum haritası sayfaları','Genel doğum haritası bilgisi için /tr/dogum-haritasi, yükselen burç aracı için /tr/yukselen-burc-hesaplayici, büyük üçlü için /tr/buyuk-uclu ve burç içerikleri için /tr/burclar sayfasına yönlendir. Kişisel yorum için /tr/danismanlar sayfasını öner.','astroloji,doğum haritası,yükselen,burç,büyük üçlü',1,3,NOW(),NOW()),
('09300000-0000-4000-8000-000000000004','tr','Tarot kahve rüya ve numeroloji sayfaları','Tarot hakkında /tr/tarot, kahve falı hakkında /tr/kahve-fali, rüya sembolleri için /tr/ruya-tabiri ve numeroloji için /tr/numeroloji sayfasına yönlendir. AI ücretsiz açılım veya kişisel yorum yapmaz; kişisel seans için /tr/danismanlar sayfasını gösterir.','tarot,kahve falı,rüya,numeroloji',1,4,NOW(),NOW()),
('09300000-0000-4000-8000-000000000005','tr','Sinastri yıldızname ve ilişki','Sinastri bilgisi için /tr/sinastri, yıldızname için /tr/yildizname sayfasına yönlendir. İlişkiye özel yorum, uyum sonucu veya gelecek tahmini verme; kişisel değerlendirme için /tr/danismanlar sayfasındaki ilgili uzmanları öner.','sinastri,yıldızname,ilişki,aşk,uyum',1,5,NOW(),NOW()),
('09300000-0000-4000-8000-000000000006','tr','Randevu oluşturma','Kullanıcı /tr/danismanlar sayfasından danışmanı seçer; profilde hizmet ve uygun zaman dilimini belirler, randevuyu oluşturur ve gerekiyorsa güvenli ödeme adımını tamamlar. Onaylanan randevu hesap içindeki randevular bölümünde görünür.','randevu al,saat seç,rezervasyon,seans',1,6,NOW(),NOW()),
('09300000-0000-4000-8000-000000000007','tr','Ödeme ve ödeme hatası','Güncel hizmet bedeli danışman profilinde gösterilir. Ödeme hatasında sayfayı yenilemeden önce kart bilgilerini, internet bağlantısını ve bankanın işlemi reddedip reddetmediğini kontrol etmesini; sonra yeniden denemesini öner. Para çekildiği halde randevu oluşmadıysa veya tekrar eden çekim şüphesi varsa [CANLI_DESTEK] ile yöneticiye aktar.','ödeme,kart,iyzico,para çekildi,ödeme başarısız',1,7,NOW(),NOW()),
('09300000-0000-4000-8000-000000000008','tr','Randevu iptali ve iade','Kullanıcı iptal edilebilir durumdaki kendi randevusunu hesap içindeki randevular bölümünden iptal edebilir. Kesin iade süresi veya koşulu uydurma; ödeme/iade incelemesi, iptal butonunun görünmemesi veya durum uyuşmazlığında [CANLI_DESTEK] ile yöneticiye aktar. Yasal politika için /tr/legal/iptal-iade-politikasi sayfasına yönlendir.','iptal,iade,randevu iptali,para iadesi',1,8,NOW(),NOW()),
('09300000-0000-4000-8000-000000000009','tr','Giriş kayıt ve şifre sorunları','Hesap açmak için /tr/register, giriş için /tr/login, unutulan şifre için /tr/forgot-password sayfasını kullanmasını öner. E-posta doğrulama mesajı gelmediyse spam klasörünü ve yazılan adresi kontrol etmesini söyle. Sıfırlama bağlantısı veya hesap erişimi yine çalışmıyorsa [CANLI_DESTEK] ile yöneticiye aktar.','giriş,kayıt,şifre,e-posta doğrulama,hesap',1,9,NOW(),NOW()),
('09300000-0000-4000-8000-000000000010','tr','Canlı görüşme ve ses görüntü sorunu','Görüşme öncesi tarayıcı veya uygulama mikrofon/kamera iznini, internet bağlantısını ve doğru cihazın seçili olduğunu kontrol etmesini; sayfayı yeniden açmasını öner. Yalnız randevunun desteklediği görüşme türü kullanılabilir. Randevu saatinde oturum açılmıyor veya bağlantı kurulamıyorsa [CANLI_DESTEK] ile yöneticiye aktar.','mikrofon,kamera,ses,görüntü,canlı görüşme,bağlantı',1,10,NOW(),NOW()),
('09300000-0000-4000-8000-000000000011','tr','Profil ve görsel yükleme hatası','Profil görselinde JPG, PNG ve WebP desteklenir; HEIC dosyası bu biçimlerden birine çevrilmelidir. Dosya boyutunu küçültüp yeniden denemesini öner. Yükleme servisi hatası devam ederse [CANLI_DESTEK] ile yöneticiye aktar.','profil,fotoğraf,avatar,yükleme,HEIC,JPG,PNG,WebP',1,11,NOW(),NOW()),
('09300000-0000-4000-8000-000000000012','tr','Site içerikleri ve blog','Astroloji ve ruhsal farkındalık içerikleri /tr/blog sayfasında; sık sorulan sorular /tr/faqs sayfasında bulunur. AI kullanıcıyı sorusuyla doğrudan ilgili sayfaya yönlendirir ve sayfa içeriğinin yerine ücretsiz kişisel danışmanlık üretmez.','blog,makale,bilgi,sss,sayfa',1,12,NOW(),NOW()),
('09300000-0000-4000-8000-000000000013','tr','Danışman olmak','Danışmanlık başvurusu /tr/become-consultant sayfasından yapılır. Başvuru koşulları, profil bilgileri ve istenen belgeler formda açıklanır; onay garantisi veya kesin değerlendirme süresi verme. Başvuru durumu özel inceleme gerektiriyorsa [CANLI_DESTEK] ile yöneticiye aktar.','danışman ol,başvuru,astrolog başvurusu,uzman',1,13,NOW(),NOW()),
('09300000-0000-4000-8000-000000000014','tr','Gizlilik ve yasal sayfalar','KVKK için /tr/kvkk, gizlilik için /tr/gizlilik, kullanım şartları için /tr/kullanim-sartlari ve çerezler için /tr/cerez-politikasi sayfasına yönlendir. Hukuki yorum yapma; kişisel veri talebi veya hesap silme işlemi destek gerektiriyorsa [CANLI_DESTEK] ile yöneticiye aktar.','kvkk,gizlilik,çerez,hesap silme,kişisel veri',1,14,NOW(),NOW()),
('09300000-0000-4000-8000-000000000015','tr','Çözümü olmayan hata ve destek','Bilgi bankasında doğrulanmış çözüm yoksa kullanıcıdan şifre, tam kart numarası veya hassas kişisel veri isteme. Kısa hata açıklamasını ve mümkünse hangi sayfada olduğunu al; ardından [CANLI_DESTEK] ile konuşmayı admin destek kuyruğuna aktar.','hata,çalışmıyor,sorun,destek,admin',1,15,NOW(),NOW())
ON DUPLICATE KEY UPDATE title=VALUES(title),content=VALUES(content),tags=VALUES(tags),is_active=VALUES(is_active),priority=VALUES(priority),updated_at=NOW();
