CREATE TABLE IF NOT EXISTS llm_usage_imports (
  id CHAR(36) NOT NULL PRIMARY KEY,
  import_key VARCHAR(255) NOT NULL UNIQUE,
  usage_date_utc DATE NOT NULL,
  provider VARCHAR(32) NOT NULL DEFAULT 'anthropic',
  model VARCHAR(128) NOT NULL,
  api_key_label VARCHAR(128) NOT NULL,
  workspace VARCHAR(128) NOT NULL,
  usage_type VARCHAR(32) NOT NULL,
  context_window VARCHAR(32) NULL,
  input_tokens BIGINT UNSIGNED NOT NULL DEFAULT 0,
  cache_write_5m_tokens BIGINT UNSIGNED NOT NULL DEFAULT 0,
  cache_write_1h_tokens BIGINT UNSIGNED NOT NULL DEFAULT 0,
  cache_read_tokens BIGINT UNSIGNED NOT NULL DEFAULT 0,
  output_tokens BIGINT UNSIGNED NOT NULL DEFAULT 0,
  web_search_count BIGINT UNSIGNED NOT NULL DEFAULT 0,
  inference_geo VARCHAR(64) NULL,
  speed VARCHAR(64) NULL,
  net_cost_usd DECIMAL(14,8) NOT NULL DEFAULT 0,
  vat_rate DECIMAL(6,4) NOT NULL DEFAULT 0.1900,
  gross_cost_usd DECIMAL(14,8) NOT NULL DEFAULT 0,
  source_file VARCHAR(255) NOT NULL,
  imported_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  INDEX idx_llm_import_usage_date (usage_date_utc),
  INDEX idx_llm_import_model (model)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
