-- =============================================================
-- 097b_astrology_kb_context_i18n_seed.sql
-- LLM-context astrology_kb girdilerinin EN + DE çevirileri.
--
-- Kaynak (locale='tr'):
--   - 097_astrology_kb_schema.sql   → planet_sign (12), aspect (5), sign_house (1)
--   - 0971_astrology_kb_wikipedia_tr_seed.sql → misc (12)
--
-- ATLANANLAR: kind='sign' ve kind='sign_section' (zaten tr/en/de tam).
--
-- Notlar:
-- - kind, key1, key2, key3 anahtarları AYNEN korunur; sadece locale + metin çevrilir.
-- - id'ler deterministik: en → 8x1..., de → 8x2... prefix ile benzersiz.
-- - UNIQUE KEY (kind, key1, key2, key3, locale) → locale farkı çakışmayı önler.
-- - astrology_kb.locale kolonu zaten mevcut (şema değişikliği yok).
-- =============================================================

INSERT INTO astrology_kb (
  id, kind, key1, key2, key3, locale, title, content, short_summary,
  tone, source, author, is_active, reviewed_by, reviewed_at
) VALUES

-- ═══════════════════════════════════════════════════════════
-- EN — planet_sign (Sun in each sign)
-- ═══════════════════════════════════════════════════════════
('81000000-0000-4000-8000-000000000001','planet_sign','sun','aries',NULL,'en','Sun in Aries','Courage, the energy of new beginnings, and the urge to forge your own path come naturally to you. Overthinking before you leap frustrates you; action is your greatest teacher. Your leadership streak is plainly visible — even when no one tells you to, you instinctively step forward and take the lead.','Bold, full of beginner''s energy, a natural-born leader.','warm',NULL,NULL,1,NULL,NULL),
('81000000-0000-4000-8000-000000000002','planet_sign','sun','taurus',NULL,'en','Sun in Taurus','Stability, tangible beauty, and your own pace are sacred to you. You regard those who rush with suspicion and refuse to abandon your own rhythm. Love, money, nature — whatever is real to you through your five senses becomes the ground your life is built on.','Steady, sensual, moving at your own rhythm.','warm',NULL,NULL,1,NULL,NULL),
('81000000-0000-4000-8000-000000000003','planet_sign','sun','gemini',NULL,'en','Sun in Gemini','Curiosity, words, and connection are your three pillars. You can learn any subject, but being locked into a single one stifles you. Your life needs variety, flexibility, and a constant stream of new questions; monotony extinguishes your spirit.','Curious, versatile, and communication-loving.','warm',NULL,NULL,1,NULL,NULL),
('81000000-0000-4000-8000-000000000004','planet_sign','sun','cancer',NULL,'en','Sun in Cancer','Emotional memory, family, and belonging keep you grounded. You may hide what you feel, but you never forget it. You are at your strongest when you are building a home — physical or emotional — with the people you love.','Strong emotional memory, protective, belonging-oriented.','warm',NULL,NULL,1,NULL,NULL),
('81000000-0000-4000-8000-000000000005','planet_sign','sun','leo',NULL,'en','Sun in Leo','There is a part of you meant to shine — the feeling that the stage is yours is not without reason. You want to be noticed not out of vanity, but because you have earned it. Your generous heart, once you learn to trust it, is your greatest strength.','Generous, wanting to be seen, radiating warm light.','warm',NULL,NULL,1,NULL,NULL),
('81000000-0000-4000-8000-000000000006','planet_sign','sun','virgo',NULL,'en','Sun in Virgo','A love of detail, service, and the drive toward perfection. You cannot rest until a task is done properly; this is not tedium but an inner calling. Your criticism turns on yourself first — which is why you may seem harsh to others.','A love of detail, work ethic, constant improvement.','warm',NULL,NULL,1,NULL,NULL),
('81000000-0000-4000-8000-000000000007','planet_sign','sun','libra',NULL,'en','Sun in Libra','Balance, aesthetics, and relationship — the three beats of your heart. Even when you are alone, you see through someone else''s eyes. Seeing both sides when you decide makes you fair; but it can also make you seem indecisive.','Relational, aesthetically sensitive, seeking balance.','warm',NULL,NULL,1,NULL,NULL),
('81000000-0000-4000-8000-000000000008','planet_sign','sun','scorpio',NULL,'en','Sun in Scorpio','You are not satisfied with the surface — truth lies beneath everything, and that is where you go. You bond intensely and live intensely. Destruction and rebirth are the rhythm of your life; when you accept it rather than resist it, you transform.','Deep, transformative, intensely bonding.','warm',NULL,NULL,1,NULL,NULL),
('81000000-0000-4000-8000-000000000009','planet_sign','sun','sagittarius',NULL,'en','Sun in Sagittarius','Horizons, meaning, and freedom call to you. You do not stay long with anyone who confines you; whether in body or mind, you always travel far and push against limits. Philosophy, travel, learning — that is where you grow.','Broad-minded, freedom-loving, seeking meaning.','warm',NULL,NULL,1,NULL,NULL),
('81000000-0000-4000-8000-000000000010','planet_sign','sun','capricorn',NULL,'en','Sun in Capricorn','Discipline, responsibility, and the long view — your seriousness is not a luxury but part of who you are. You seem mature from a young age; as you grow older you lighten up and discover how to have fun. You walk toward your goal stubbornly, unafraid of arriving late.','Disciplined, goal-oriented, playing the long game.','warm',NULL,NULL,1,NULL,NULL),
('81000000-0000-4000-8000-000000000011','planet_sign','sun','aquarius',NULL,'en','Sun in Aquarius','Questioning what is taken for granted comes naturally to you wherever you stand out as different. You care about community, yet you do not speak the language of the crowd. You read the future from the present — which is why you are sometimes misunderstood.','Original, questioning, future-facing.','warm',NULL,NULL,1,NULL,NULL),
('81000000-0000-4000-8000-000000000012','planet_sign','sun','pisces',NULL,'en','Sun in Pisces','Your boundaries are permeable — you take in both beauty and heaviness. You are creative, intuitive, and compassionate. To avoid losing yourself, you need to learn to set physical boundaries from time to time.','Intuitive, compassionate, creative, permeable.','warm',NULL,NULL,1,NULL,NULL),

-- ═══════════════════════════════════════════════════════════
-- EN — aspect
-- ═══════════════════════════════════════════════════════════
('81000000-0000-4000-8000-000000000020','aspect','sun','moon','trine','en','Sun ↔ Moon (harmonious aspect / trine)','Your inner "what I ought to do" and "what I want to feel" usually face the same direction. Being yourself does not cost you much effort; your rational decisions generally align with your emotional needs.','Your thoughts and feelings are in harmony.','warm',NULL,NULL,1,NULL,NULL),
('81000000-0000-4000-8000-000000000021','aspect','sun','moon','square','en','Sun ↔ Moon (tension aspect / square)','Two voices inside you are constantly negotiating: "I should do this" versus "but I don''t feel it." This tension may seem exhausting, yet it is the engine of a deep self-awareness — you are learning to take both your mind and your heart into account.','Able to transform the tension between mind and heart.','warm',NULL,NULL,1,NULL,NULL),
('81000000-0000-4000-8000-000000000022','aspect','mars','saturn','square','en','Mars ↔ Saturn (tension aspect / square)','Your "act now" impulse and your "think, make a plan" voice are in constant conflict. This clash protects you from hasty decisions but can sometimes paralyze you. In time, you learn to find your own balance between action and patience.','The tension between action and patience.','professional',NULL,NULL,1,NULL,NULL),
('81000000-0000-4000-8000-000000000023','aspect','venus','jupiter','sextile','en','Venus ↔ Jupiter (harmonious aspect / sextile)','Expressing love comes naturally to you. You are generous and give freely to those you love; giving without expecting return nourishes your soul. You are inclined to notice the beautiful moments of life — this is not coincidence but a talent.','Generous, seeing the beauty in life.','warm',NULL,NULL,1,NULL,NULL),
('81000000-0000-4000-8000-000000000024','aspect','sun','pluto','conjunction','en','Sun ⊕ Pluto (conjunction)','Your identity is intertwined with an intense transformative force. Collapses and rebirths are ordinary in your life; you emerge from each crisis as a different self. Power dynamics both attract you and, whether you like it or not, put you to the test.','An identity defined through transformation.','direct',NULL,NULL,1,NULL,NULL),

-- ═══════════════════════════════════════════════════════════
-- EN — sign_house
-- ═══════════════════════════════════════════════════════════
('81000000-0000-4000-8000-000000000040','sign_house','scorpio','8',NULL,'en','Scorpio in the 8th House','The 8th house is the house of transformation, shared resources, and the hidden. With Scorpio here, these themes grow even more intense: deep relationships, inheritance, and rising out of crisis are your natural soil. Staying on the surface unsettles you; you have an inner drive to see what is real.','A field of deep transformation.','professional',NULL,NULL,1,NULL,NULL),

-- ═══════════════════════════════════════════════════════════
-- EN — misc (Wikipedia editorial context notes)
-- ═══════════════════════════════════════════════════════════
('81100000-0000-4000-8000-000000000001','misc','wiki_astrology','overview',NULL,'en','Wikipedia Import — Overview of astrology','Astrology is treated as a historical interpretive tradition that draws meaningful connections between celestial bodies and human character, behavioral patterns, and life events. In modern product language this topic should not be presented as definitive judgment or scientific prediction; it should be used within a symbolic, cultural, and self-awareness-focused frame.','A general note positioning astrology as a cultural and symbolic interpretive tradition.','neutral','https://en.wikipedia.org/wiki/Astrology','Wikipedia contributors, CC BY-SA 4.0',0,NULL,NULL),
('81100000-0000-4000-8000-000000000002','misc','wiki_astrology','science_caution',NULL,'en','Wikipedia Import — Scientific language caveat','When preparing astrology content, claims of scientific certainty should be avoided. Interpretations offered to the user should be written not as repeatable experimental results, but as guidance texts explained in the language of symbols, archetypes, and self-awareness.','A note on avoiding claims of scientific certainty in astrology interpretations.','professional','https://en.wikipedia.org/wiki/Astrology','Wikipedia contributors, CC BY-SA 4.0',0,NULL,NULL),
('81100000-0000-4000-8000-000000000003','misc','wiki_astrology','barnum_effect',NULL,'en','Wikipedia Import — Note on the Barnum effect','The perception of general and flattering statements as personally specific is a significant psychological risk in the astrology experience. LLM outputs should therefore reduce overly vague, one-size-fits-all sentences and build a more responsible language using specific details drawn from the user''s birth data, question context, and past interactions.','A Barnum-effect caveat for reducing generic, catch-all interpretations.','professional','https://en.wikipedia.org/wiki/Astrology','Wikipedia contributors, CC BY-SA 4.0',0,NULL,NULL),
('81100000-0000-4000-8000-000000000004','misc','wiki_zodiac','geometry',NULL,'en','Wikipedia Import — Zodiac geometry','In describing the zodiac, it can be recalled that the 360-degree celestial circle is symbolically divided into twelve equal parts. Each segment is treated as a 30-degree span; this approach describes the astrological symbolic order rather than constellation boundaries.','The division of the zodiac into twelve equal symbolic segments.','neutral','https://en.wikipedia.org/wiki/Zodiac','Wikipedia contributors, CC BY-SA 4.0',0,NULL,NULL),
('81100000-0000-4000-8000-000000000005','misc','wiki_zodiac','constellations',NULL,'en','Wikipedia Import — Zodiac and constellations','The zodiac belt is related to the astronomical constellations; however, the sign symbols used in astrology are not directly the same as the modern constellation boundaries. When this distinction is made plainly in content, both the SEO text and user trust are strengthened.','The distinction between sign symbols and astronomical constellation boundaries.','neutral','https://en.wikipedia.org/wiki/Zodiac','Wikipedia contributors, CC BY-SA 4.0',0,NULL,NULL),
('81100000-0000-4000-8000-000000000006','misc','wiki_zodiac','ecliptic',NULL,'en','Wikipedia Import — Ecliptic context','In sign and zodiac texts, the ecliptic context associated with the Sun''s apparent annual path across the sky can be used as a brief background. This information helps sign pages convey the idea of celestial coordinates and cycles rather than a mere "personality label."','A brief background linking the concept of the ecliptic to sign descriptions.','neutral','https://en.wikipedia.org/wiki/Astrological_sign','Wikipedia contributors, CC BY-SA 4.0',0,NULL,NULL),
('81100000-0000-4000-8000-000000000007','misc','wiki_signs','elements',NULL,'en','Wikipedia Import — Describing the elements','The fire, earth, air, and water elements can be used in sign content to explain basic temperament. Texts should avoid stereotyping; the element should be presented not as destiny on its own, but as a language of tendency read together with the other placements in the birth chart.','A note relating the elements to the whole chart without stereotyping.','warm','https://en.wikipedia.org/wiki/Astrological_sign','Wikipedia contributors, CC BY-SA 4.0',0,NULL,NULL),
('81100000-0000-4000-8000-000000000008','misc','wiki_signs','modalities',NULL,'en','Wikipedia Import — Describing the modalities','The cardinal, fixed, and mutable modalities are a good editorial layer for explaining a sign''s mode of action. In profile texts, modality should be explained with plain examples through the rhythms of initiating, sustaining, and adapting.','A note explaining the modalities through the language of mode of action and rhythm.','warm','https://en.wikipedia.org/wiki/Astrological_sign','Wikipedia contributors, CC BY-SA 4.0',0,NULL,NULL),
('81100000-0000-4000-8000-000000000009','misc','wiki_birth_chart','chart_context',NULL,'en','Wikipedia Import — Birth chart context','When transitioning from sign pages to the birth chart, the user should be told clearly that the Sun sign alone does not explain the whole personality. A more layered picture emerges together with the Moon, ascendant, planets, houses, and aspects.','A CTA note transitioning from the Sun sign to the whole birth chart.','professional','https://en.wikipedia.org/wiki/Astrological_sign','Wikipedia contributors, CC BY-SA 4.0',0,NULL,NULL),
('81100000-0000-4000-8000-000000000010','misc','wiki_astrology','traditions',NULL,'en','Wikipedia Import — Astrological traditions','Astrology has various traditions, genres, and fields of practice across different cultures. In GoldMoodAstro content, this diversity should be conveyed in the language of "schools of interpretation" and "symbolic approaches" rather than a single absolute system narrative.','A note conveying different astrological traditions in a pluralistic way.','neutral','https://en.wikipedia.org/wiki/Astrology','Wikipedia contributors, CC BY-SA 4.0',0,NULL,NULL),
('81100000-0000-4000-8000-000000000011','misc','wiki_astrology','responsible_copy',NULL,'en','Wikipedia Import — Responsible copy standard','Astrology texts should stay away from frightening, fatalistic, or definitive-outcome statements. The safest frame in the user experience is a guidance tone that emphasizes probability, awareness, the language of emotion, and the space for choice.','A product-language standard avoiding fatalistic and frightening statements.','professional','https://en.wikipedia.org/wiki/Astrology','Wikipedia contributors, CC BY-SA 4.0',0,NULL,NULL),
('81100000-0000-4000-8000-000000000012','misc','wiki_zodiac','editorial_seo',NULL,'en','Wikipedia Import — SEO editorial bridge','When linking the sign, zodiac, and birth chart pages, the basic concept should be explained first, then move on to more personal and detailed interpretation. This structure both satisfies search intent and naturally carries the user toward the birth chart product.','An SEO content flow going from the basic concept to the personal chart.','professional','https://en.wikipedia.org/wiki/Zodiac','Wikipedia contributors, CC BY-SA 4.0',0,NULL,NULL),

-- ═══════════════════════════════════════════════════════════
-- DE — planet_sign (Sonne im jeweiligen Zeichen)
-- ═══════════════════════════════════════════════════════════
('82000000-0000-4000-8000-000000000001','planet_sign','sun','aries',NULL,'de','Sonne im Widder','Mut, die Energie des Neuanfangs und der Drang, deinen eigenen Weg zu gehen, sind dir angeboren. Lange nachzudenken, bevor du losläufst, langweilt dich; Handeln ist dein größter Lehrer. Deine Führungsader ist klar sichtbar — auch wenn niemand es sagt, gehst du intuitiv voran und übernimmst die Führung.','Mutig, voller Aufbruchsenergie, ein geborener Anführer.','warm',NULL,NULL,1,NULL,NULL),
('82000000-0000-4000-8000-000000000002','planet_sign','sun','taurus',NULL,'de','Sonne im Stier','Beständigkeit, greifbare Schönheit und dein eigenes Tempo sind dir heilig. Wer hetzt, dem begegnest du mit Misstrauen, und du gibst deinen eigenen Rhythmus nicht auf. Liebe, Geld, Natur — was auch immer durch deine fünf Sinne wirklich für dich ist, bildet das Fundament deines Lebens.','Beständig, sinnlich, im eigenen Rhythmus voranschreitend.','warm',NULL,NULL,1,NULL,NULL),
('82000000-0000-4000-8000-000000000003','planet_sign','sun','gemini',NULL,'de','Sonne in den Zwillingen','Neugier, Worte und Verbindung — deine drei Säulen. Du kannst jedes Thema lernen, aber dich auf ein einziges festzulegen, erdrückt dich. Dein Leben braucht Vielfalt, Flexibilität und ständig neue Fragen; Eintönigkeit erstickt deinen Geist.','Neugierig, vielseitig, kommunikationsfreudig.','warm',NULL,NULL,1,NULL,NULL),
('82000000-0000-4000-8000-000000000004','planet_sign','sun','cancer',NULL,'de','Sonne im Krebs','Emotionales Gedächtnis, Familie und Zugehörigkeit geben dir Halt. Du kannst verbergen, was du fühlst, aber du vergisst es nie. Am stärksten bist du, wenn du mit deinen Liebsten ein Zuhause — ob physisch oder emotional — aufbaust.','Starkes emotionales Gedächtnis, beschützend, auf Zugehörigkeit ausgerichtet.','warm',NULL,NULL,1,NULL,NULL),
('82000000-0000-4000-8000-000000000005','planet_sign','sun','leo',NULL,'de','Sonne im Löwen','In dir gibt es einen Teil, der leuchten muss — das Gefühl, dass die Bühne dir gehört, kommt nicht von ungefähr. Du willst nicht aus Eitelkeit wahrgenommen werden, sondern weil du es verdient hast. Dein großzügiges Herz ist, sobald du ihm vertrauen lernst, deine größte Stärke.','Großzügig, gesehen werden wollend, mit warmem Leuchten.','warm',NULL,NULL,1,NULL,NULL),
('82000000-0000-4000-8000-000000000006','planet_sign','sun','virgo',NULL,'de','Sonne in der Jungfrau','Liebe zum Detail, Dienst und das Streben nach Vervollkommnung. Du kommst nicht zur Ruhe, bevor eine Aufgabe ordentlich erledigt ist; das ist keine Pedanterie, sondern eine innere Berufung. Deine Kritik richtet sich zuerst gegen dich selbst — deshalb kannst du auf andere hart wirken.','Liebe zum Detail, Arbeitsethik, stetige Verbesserung.','warm',NULL,NULL,1,NULL,NULL),
('82000000-0000-4000-8000-000000000007','planet_sign','sun','libra',NULL,'de','Sonne in der Waage','Gleichgewicht, Ästhetik und Beziehung — die drei Schläge deines Herzens. Selbst wenn du allein bist, blickst du durch die Augen eines anderen. Bei Entscheidungen beide Seiten zu sehen, macht dich gerecht; doch lässt es dich manchmal auch unentschlossen erscheinen.','Beziehungsorientiert, ästhetisch empfindsam, nach Ausgleich strebend.','warm',NULL,NULL,1,NULL,NULL),
('82000000-0000-4000-8000-000000000008','planet_sign','sun','scorpio',NULL,'de','Sonne im Skorpion','Mit der Oberfläche gibst du dich nicht zufrieden — die Wahrheit liegt unter allem, und dorthin gehst du. Du bindest dich intensiv und lebst intensiv. Zerstörung und Wiedergeburt sind der Rhythmus deines Lebens; wenn du ihn annimmst statt ihn abzulehnen, verwandelst du dich.','Tiefgründig, verwandelnd, intensiv bindend.','warm',NULL,NULL,1,NULL,NULL),
('82000000-0000-4000-8000-000000000009','planet_sign','sun','sagittarius',NULL,'de','Sonne im Schützen','Horizonte, Sinn und Freiheit rufen dich. Bei niemandem, der dich einengt, bleibst du lange; ob mit dem Körper oder dem Geist, du reist stets in die Ferne und lotest Grenzen aus. Philosophie, Reisen, Bildung — dort wächst du.','Weitblickend, freiheitsliebend, nach Sinn suchend.','warm',NULL,NULL,1,NULL,NULL),
('82000000-0000-4000-8000-000000000010','planet_sign','sun','capricorn',NULL,'de','Sonne im Steinbock','Disziplin, Verantwortung und der lange Atem — deine Ernsthaftigkeit ist kein Luxus, sondern Teil deiner Persönlichkeit. Schon in jungen Jahren wirkst du reif; mit dem Alter wirst du leichter und entdeckst das Vergnügen. Du gehst hartnäckig auf dein Ziel zu und fürchtest dich nicht davor, spät zu kommen.','Diszipliniert, zielorientiert, langfristig denkend.','warm',NULL,NULL,1,NULL,NULL),
('82000000-0000-4000-8000-000000000011','planet_sign','sun','aquarius',NULL,'de','Sonne im Wassermann','Das Selbstverständliche zu hinterfragen, ist dir überall dort angeboren, wo du dich als anders abhebst. Die Gemeinschaft liegt dir am Herzen, doch du sprichst nicht die Sprache der Masse. Du liest die Zukunft aus der Gegenwart — deshalb wirst du manchmal missverstanden.','Originell, hinterfragend, in die Zukunft blickend.','warm',NULL,NULL,1,NULL,NULL),
('82000000-0000-4000-8000-000000000012','planet_sign','sun','pisces',NULL,'de','Sonne in den Fischen','Deine Grenzen sind durchlässig — du nimmst sowohl die Schönheit als auch die Schwere in dich auf. Du bist kreativ, intuitiv und mitfühlend. Um dich nicht selbst zu verlieren, musst du lernen, hin und wieder physische Grenzen zu setzen.','Intuitiv, mitfühlend, kreativ, durchlässig.','warm',NULL,NULL,1,NULL,NULL),

-- ═══════════════════════════════════════════════════════════
-- DE — aspect
-- ═══════════════════════════════════════════════════════════
('82000000-0000-4000-8000-000000000020','aspect','sun','moon','trine','de','Sonne ↔ Mond (harmonischer Aspekt / Trigon)','Dein inneres „das sollte ich tun" und „das möchte ich fühlen" blicken meist in dieselbe Richtung. Du selbst zu sein, fällt dir nicht schwer; deine rationalen Entscheidungen decken sich in der Regel mit deinen emotionalen Bedürfnissen.','Dein Denken und dein Fühlen sind im Einklang.','warm',NULL,NULL,1,NULL,NULL),
('82000000-0000-4000-8000-000000000021','aspect','sun','moon','square','de','Sonne ↔ Mond (Spannungsaspekt / Quadrat)','In dir verhandeln ständig zwei Stimmen: „ich müsste dies tun" gegen „aber ich fühle das nicht". Diese Spannung mag ermüdend wirken, doch sie ist der Motor eines tiefen Selbstbewusstseins — du lernst, sowohl deinen Verstand als auch dein Herz einzubeziehen.','Fähig, die Spannung zwischen Verstand und Herz zu verwandeln.','warm',NULL,NULL,1,NULL,NULL),
('82000000-0000-4000-8000-000000000022','aspect','mars','saturn','square','de','Mars ↔ Saturn (Spannungsaspekt / Quadrat)','Dein Impuls „sofort handeln" und deine Stimme „denk nach, mach einen Plan" liegen in ständigem Widerstreit. Dieser Konflikt bewahrt dich vor voreiligen Entscheidungen, kann dich aber manchmal lähmen. Mit der Zeit lernst du, dein eigenes Gleichgewicht zwischen Handeln und Geduld zu finden.','Die Spannung zwischen Handeln und Geduld.','professional',NULL,NULL,1,NULL,NULL),
('82000000-0000-4000-8000-000000000023','aspect','venus','jupiter','sextile','de','Venus ↔ Jupiter (harmonischer Aspekt / Sextil)','Liebe auszudrücken fällt dir leicht. Du bist großzügig und gibst deinen Liebsten reichlich; geben, ohne eine Gegenleistung zu erwarten, nährt deine Seele. Du neigst dazu, die schönen Momente des Lebens zu bemerken — das ist kein Zufall, sondern eine Gabe.','Großzügig, die Schönheit des Lebens sehend.','warm',NULL,NULL,1,NULL,NULL),
('82000000-0000-4000-8000-000000000024','aspect','sun','pluto','conjunction','de','Sonne ⊕ Pluto (Konjunktion)','Deine Identität ist mit einer intensiven, verwandelnden Kraft verwoben. Zusammenbrüche und Wiedergeburten sind in deinem Leben gewöhnlich; aus jeder Krise gehst du als ein anderes Selbst hervor. Machtdynamiken ziehen dich an und stellen dich, ob du willst oder nicht, auf die Probe.','Eine durch Wandlung definierte Identität.','direct',NULL,NULL,1,NULL,NULL),

-- ═══════════════════════════════════════════════════════════
-- DE — sign_house
-- ═══════════════════════════════════════════════════════════
('82000000-0000-4000-8000-000000000040','sign_house','scorpio','8',NULL,'de','Skorpion im 8. Haus','Das 8. Haus ist das Haus der Verwandlung, der gemeinsamen Ressourcen und des Verborgenen. Mit dem Skorpion hier werden diese Themen noch intensiver: tiefe Beziehungen, Erbe und das Herauskommen aus Krisen sind dein natürlicher Boden. An der Oberfläche zu bleiben, verunsichert dich; du hast einen inneren Drang, das Wirkliche zu sehen.','Ein Feld tiefer Verwandlung.','professional',NULL,NULL,1,NULL,NULL),

-- ═══════════════════════════════════════════════════════════
-- DE — misc (redaktionelle Kontextnotizen aus Wikipedia)
-- ═══════════════════════════════════════════════════════════
('82100000-0000-4000-8000-000000000001','misc','wiki_astrology','overview',NULL,'de','Wikipedia-Import — Überblick über die Astrologie','Astrologie wird als eine historische Deutungstradition behandelt, die Bedeutungsbeziehungen zwischen Himmelskörpern und menschlichem Charakter, Verhaltensmustern und Lebensereignissen herstellt. In der modernen Produktsprache sollte dieses Thema nicht als endgültiges Urteil oder wissenschaftliche Vorhersage dargestellt werden, sondern in einem symbolischen, kulturellen und auf Selbstwahrnehmung ausgerichteten Rahmen verwendet werden.','Eine allgemeine Notiz, die die Astrologie als kulturelle und symbolische Deutungstradition verortet.','neutral','https://de.wikipedia.org/wiki/Astrologie','Wikipedia contributors, CC BY-SA 4.0',0,NULL,NULL),
('82100000-0000-4000-8000-000000000002','misc','wiki_astrology','science_caution',NULL,'de','Wikipedia-Import — Hinweis zur wissenschaftlichen Sprache','Bei der Erstellung von Astrologie-Inhalten sollte der Anspruch wissenschaftlicher Gewissheit vermieden werden. Die dem Nutzer angebotenen Deutungen sollten nicht wie wiederholbare experimentelle Ergebnisse geschrieben werden, sondern als Leittexte, die in der Sprache von Symbolen, Archetypen und Selbstwahrnehmung erklärt werden.','Ein Hinweis, in Astrologie-Deutungen auf den Anspruch wissenschaftlicher Gewissheit zu verzichten.','professional','https://de.wikipedia.org/wiki/Astrologie','Wikipedia contributors, CC BY-SA 4.0',0,NULL,NULL),
('82100000-0000-4000-8000-000000000003','misc','wiki_astrology','barnum_effect',NULL,'de','Wikipedia-Import — Notiz zum Barnum-Effekt','Dass allgemeine und schmeichelhafte Aussagen als persönlich zutreffend wahrgenommen werden, ist ein bedeutendes psychologisches Risiko in der Astrologie-Erfahrung. LLM-Ausgaben sollten daher übermäßig vage, für jeden gültige Sätze reduzieren und mit spezifischen Details aus den Geburtsdaten des Nutzers, dem Fragenkontext und vergangenen Interaktionen eine verantwortungsvollere Sprache aufbauen.','Ein Barnum-Effekt-Hinweis zur Reduzierung allgemeingültiger Deutungen.','professional','https://de.wikipedia.org/wiki/Astrologie','Wikipedia contributors, CC BY-SA 4.0',0,NULL,NULL),
('82100000-0000-4000-8000-000000000004','misc','wiki_zodiac','geometry',NULL,'de','Wikipedia-Import — Geometrie des Tierkreises','Bei der Beschreibung des Tierkreises kann daran erinnert werden, dass der 360-Grad-Himmelskreis symbolisch in zwölf gleiche Teile geteilt wird. Jeder Abschnitt wird als ein Bereich von 30 Grad behandelt; dieser Ansatz beschreibt die astrologische Symbolordnung eher als die Grenzen der Sternbilder.','Die Teilung des Tierkreises in zwölf gleiche symbolische Abschnitte.','neutral','https://de.wikipedia.org/wiki/Tierkreiszeichen','Wikipedia contributors, CC BY-SA 4.0',0,NULL,NULL),
('82100000-0000-4000-8000-000000000005','misc','wiki_zodiac','constellations',NULL,'de','Wikipedia-Import — Tierkreis und Sternbilder','Der Tierkreisgürtel steht in Beziehung zu den astronomischen Sternbildern; die in der Astrologie verwendeten Tierkreiszeichen sind jedoch nicht direkt dasselbe wie die modernen Sternbildgrenzen. Wenn diese Unterscheidung in den Inhalten schlicht getroffen wird, werden sowohl der SEO-Text als auch das Vertrauen der Nutzer gestärkt.','Die Unterscheidung zwischen Tierkreiszeichen und astronomischen Sternbildgrenzen.','neutral','https://de.wikipedia.org/wiki/Tierkreiszeichen','Wikipedia contributors, CC BY-SA 4.0',0,NULL,NULL),
('82100000-0000-4000-8000-000000000006','misc','wiki_zodiac','ecliptic',NULL,'de','Wikipedia-Import — Kontext der Ekliptik','In Zeichen- und Tierkreistexten kann der Kontext der Ekliptik, der mit der scheinbaren jährlichen Bahn der Sonne am Himmel verbunden ist, als kurzer Hintergrund verwendet werden. Diese Information hilft den Zeichenseiten, statt eines bloßen „Persönlichkeitsetiketts" die Idee von Himmelskoordinaten und Zyklen zu vermitteln.','Ein kurzer Hintergrund, der das Konzept der Ekliptik mit den Zeichenbeschreibungen verknüpft.','neutral','https://de.wikipedia.org/wiki/Sternzeichen','Wikipedia contributors, CC BY-SA 4.0',0,NULL,NULL),
('82100000-0000-4000-8000-000000000007','misc','wiki_signs','elements',NULL,'de','Wikipedia-Import — Beschreibung der Elemente','Die Elemente Feuer, Erde, Luft und Wasser können in Zeicheninhalten verwendet werden, um das grundlegende Temperament zu erklären. Die Texte sollten Stereotypisierung vermeiden; das Element sollte nicht für sich allein wie ein Schicksal dargestellt werden, sondern als eine Sprache der Tendenz, die zusammen mit den anderen Stellungen im Geburtshoroskop gelesen wird.','Eine Notiz, die die Elemente ohne Stereotype mit dem gesamten Horoskop verknüpft.','warm','https://de.wikipedia.org/wiki/Sternzeichen','Wikipedia contributors, CC BY-SA 4.0',0,NULL,NULL),
('82100000-0000-4000-8000-000000000008','misc','wiki_signs','modalities',NULL,'de','Wikipedia-Import — Beschreibung der Modalitäten','Die kardinalen, fixen und veränderlichen Modalitäten sind eine gute redaktionelle Ebene, um die Handlungsweise eines Zeichens zu erklären. In Profiltexten sollte die Modalität mit schlichten Beispielen anhand der Rhythmen des Beginnens, des Aufrechterhaltens und des Anpassens erklärt werden.','Eine Notiz, die die Modalitäten in der Sprache von Handlungsweise und Rhythmus erklärt.','warm','https://de.wikipedia.org/wiki/Sternzeichen','Wikipedia contributors, CC BY-SA 4.0',0,NULL,NULL),
('82100000-0000-4000-8000-000000000009','misc','wiki_birth_chart','chart_context',NULL,'de','Wikipedia-Import — Kontext des Geburtshoroskops','Beim Übergang von den Zeichenseiten zum Geburtshoroskop sollte dem Nutzer klar gesagt werden, dass das Sonnenzeichen allein nicht die ganze Persönlichkeit erklärt. Zusammen mit dem Mond, dem Aszendenten, den Planeten, den Häusern und den Aspekten entsteht ein vielschichtigeres Bild.','Eine CTA-Notiz für den Übergang vom Sonnenzeichen zum gesamten Geburtshoroskop.','professional','https://de.wikipedia.org/wiki/Sternzeichen','Wikipedia contributors, CC BY-SA 4.0',0,NULL,NULL),
('82100000-0000-4000-8000-000000000010','misc','wiki_astrology','traditions',NULL,'de','Wikipedia-Import — Astrologische Traditionen','Die Astrologie hat in verschiedenen Kulturen unterschiedliche Traditionen, Gattungen und Anwendungsbereiche. In den Inhalten von GoldMoodAstro sollte diese Vielfalt in der Sprache von „Deutungsschulen" und „symbolischen Ansätzen" vermittelt werden statt in der Erzählung eines einzigen absoluten Systems.','Eine Notiz, die verschiedene astrologische Traditionen pluralistisch vermittelt.','neutral','https://de.wikipedia.org/wiki/Astrologie','Wikipedia contributors, CC BY-SA 4.0',0,NULL,NULL),
('82100000-0000-4000-8000-000000000011','misc','wiki_astrology','responsible_copy',NULL,'de','Wikipedia-Import — Standard für verantwortungsvolle Texte','Astrologie-Texte sollten sich von beängstigenden, fatalistischen oder ein sicheres Ergebnis versprechenden Aussagen fernhalten. Der sicherste Rahmen im Nutzererlebnis ist ein beratender Ton, der Wahrscheinlichkeit, Bewusstsein, die Sprache der Gefühle und den Raum für Entscheidungen betont.','Ein Produktsprach-Standard, der fatalistische und beängstigende Aussagen vermeidet.','professional','https://de.wikipedia.org/wiki/Astrologie','Wikipedia contributors, CC BY-SA 4.0',0,NULL,NULL),
('82100000-0000-4000-8000-000000000012','misc','wiki_zodiac','editorial_seo',NULL,'de','Wikipedia-Import — Redaktionelle SEO-Brücke','Beim Verknüpfen der Zeichen-, Tierkreis- und Geburtshoroskop-Seiten sollte zuerst das Grundkonzept erklärt und dann zu einer persönlicheren und detaillierteren Deutung übergegangen werden. Diese Struktur erfüllt sowohl die Suchabsicht als auch führt sie den Nutzer auf natürliche Weise zum Geburtshoroskop-Produkt.','Ein SEO-Inhaltsfluss, der vom Grundkonzept zum persönlichen Horoskop führt.','professional','https://de.wikipedia.org/wiki/Tierkreiszeichen','Wikipedia contributors, CC BY-SA 4.0',0,NULL,NULL)

ON DUPLICATE KEY UPDATE
  title = VALUES(title),
  content = VALUES(content),
  short_summary = VALUES(short_summary);
