DELETE FROM astrology_kb
WHERE kind IN ('sign', 'sign_section')
  AND locale IN ('tr', 'en', 'de');

INSERT INTO astrology_kb (
  id, kind, key1, key2, key3, locale, title, content, short_summary, tone, source, author, image_url, is_active
)
SELECT
  UUID(),
  'sign',
  s.sign_key,
  NULL,
  NULL,
  l.locale,
  CASE l.locale
    WHEN 'tr' THEN CONCAT(s.label_tr, ' Burcu Rehberi')
    WHEN 'de' THEN CONCAT(s.label_de, ' Sternzeichen Leitfaden')
    ELSE CONCAT(s.label_en, ' Zodiac Guide')
  END,
  CASE l.locale
    WHEN 'tr' THEN CONCAT(
      s.label_tr, ' burcu ', s.date_tr, ' tarihleri arasında doğanların temel arketipini anlatır. ', s.element_tr, ' elementi, ', s.modality_tr, ' nitelik ve ', s.ruler_tr, ' yönetimi bu burca özel bir ritim verir. GoldMoodAstro yaklaşımında ', s.label_tr, ' yalnızca kısa bir burç etiketi değil, kişinin karar alma biçimini, ilişki kurma tarzını, iş hayatındaki motivasyonunu ve ruhsal bakım ihtiyacını anlamaya yarayan geniş bir sembolik dildir. Bu rehber, günlük yorumdan daha kalıcı bir profil sunar ve danışman görüşmelerinde kişisel doğum haritasına geçmeden önce sağlam bir başlangıç noktası oluşturur. ',
      s.core_tr, ' Bu enerji dışarıdan bakıldığında bazen tek bir davranış gibi görünür, fakat arka planda güven, yön, ifade, aidiyet ve anlam ihtiyacı birlikte çalışır. ', s.label_tr, ' insanı en iyi halinde kendi iç sesini fark eder, tepkilerini bilinçli seçer ve güçlü yanlarını başkaları üzerinde baskı kurmak için değil, hayatına canlılık katmak için kullanır. ',
      'İlişkilerde ', s.label_tr, ' için en besleyici bağ, dürüst iletişim ve duygusal netlik taşıyan bağdır. Sevgi dilinde ', s.love_tr, ' öne çıkar. Karşı tarafın onu kalıba sokmadan dinlemesi, ilişkideki güveni büyütür. Gölge tarafta ', s.shadow_tr, ' görülebilir. Bu gölge fark edildiğinde suçlanacak bir kusur olmaktan çıkar ve daha olgun bir yakınlık kurmanın pusulasına dönüşür. ',
      'Kariyer ve üretim alanında ', s.label_tr, ' motivasyonunu ', s.career_tr, ' üzerinden toplar. Doğru ortamda hızlı öğrenir, kendi becerisini görünür kılar ve somut sonuç üretir. Tekrara sıkıştığında ya da değerleriyle uyumsuz bir tempoya zorlandığında enerjisi dağılabilir. Bu yüzden hedefleri küçük aşamalara bölmek, bedensel ritmi takip etmek ve takdir ihtiyacını sağlıklı yollarla ifade etmek önemlidir. ',
      'Ruhsal ve gündelik bakım açısından ', s.label_tr, ' için temel soru şudur: Bugün kendimi hangi alanda daha sahici duyuyorum? Nefes çalışması, kısa günlük tutma, ay döngülerini takip etme, doğum haritasındaki Ay ve yükselen burçla birlikte okuma yapmak profilin derinleşmesini sağlar. ', s.wellness_tr, ' Bu uygulamalar mistik bir kaçıştan çok, kişinin davranışlarını fark ederek seçim alanını genişletmesine yardım eder. ',
      'Uyum başlığında ', s.label_tr, ' tek başına iyi ya da zor eşleşmeler listesine indirgenmemelidir. Elementler arası akış, Venüs ve Mars yerleşimleri, yedinci ev, Ay burcu ve kişilerin ilişki geçmişi birlikte okunmalıdır. Aynı elementten burçlar çoğu zaman doğal bir tanışıklık hissi verirken, farklı elementler gelişim alanı açabilir. Örneğin ', s.element_tr, ' teması kişinin nasıl beslendiğini, nasıl yorulduğunu ve kriz anında neye ihtiyaç duyduğunu anlatır. Bu yüzden uyum, iki kişinin aynı olması değil, birbirinin ritmini okuyabilmesi anlamına gelir. ',
      'GoldMoodAstro burç sayfaları hem kullanıcıların kendi kendine keşif yapması hem de danışman görüşmesine hazırlıklı gelmesi için hazırlanır. Bu profili okurken sadece sana uyan cümleleri seçmek yerine, seni rahatsız eden başlıklara da dikkat etmek faydalıdır. Çoğu zaman gelişim alanı, ilk bakışta savunmaya geçtiğimiz yerde saklıdır. ', s.label_tr, ' enerjisi bilinçli çalışıldığında kişinin sınırlarını, arzularını, korkularını ve gerçek motivasyonunu daha net görmesine yardım eder. Günlük yorumlar geçici atmosferi gösterirken, bu rehber karakterin tekrar eden kalıplarını anlamak için daha kalıcı bir zemin sunar. ',
      'Profilin pratik kullanımı için ayda bir kez bu sayfaya dönmek yararlı olabilir. Önce güçlü yanları, sonra zorlandığın ilişki ve iş kalıplarını işaretle. Ardından son dört haftada hangi davranışların tekrar ettiğini, hangi durumlarda daha canlı hissettiğini ve hangi sınırların ihmal edildiğini not et. Bu küçük çalışma ', s.label_tr, ' sembolünü soyut bir astroloji bilgisinden çıkarıp gündelik yaşamda karar vermeye destek olan kişisel bir haritaya dönüştürür. ',
      'Bu metin genel güneş burcu yorumu olarak okunmalıdır. En doğru değerlendirme yükselen burç, Ay burcu, gezegen yerleşimleri, evler ve açılarla birlikte yapılır. GoldMoodAstro danışmanları ', s.label_tr, ' temasını kişisel haritanla birleştirerek ilişki, kariyer, duygu düzenleme ve yaşam yönü gibi başlıklarda daha kişisel bir çerçeve sunabilir.'
    )
    WHEN 'de' THEN CONCAT(
      s.label_de, ' beschreibt das Grundmuster von Menschen, die zwischen ', s.date_de, ' geboren sind. Das Element ', s.element_de, ', die Qualität ', s.modality_de, ' und der Herrscher ', s.ruler_de, ' geben diesem Zeichen seinen besonderen Rhythmus. Im GoldMoodAstro Ansatz ist ', s.label_de, ' nicht nur ein kurzes Sternzeichen, sondern eine symbolische Sprache für Entscheidungen, Beziehungen, Motivation und innere Selbstfürsorge. Dieser Leitfaden geht über ein Tageshoroskop hinaus und bietet eine stabile Grundlage, bevor eine persönliche Geburtskarte gelesen wird. ',
      s.core_de, ' Von außen wirkt diese Energie manchmal wie eine einzelne Eigenschaft, doch darunter arbeiten Sicherheit, Richtung, Ausdruck, Zugehörigkeit und Sinn zusammen. In reifer Form erkennt ', s.label_de, ' die eigene innere Stimme, wählt Reaktionen bewusster und nutzt Stärken nicht als Druckmittel, sondern als Quelle von Lebendigkeit. ',
      'In Beziehungen braucht ', s.label_de, ' ehrliche Kommunikation und emotionale Klarheit. Die Liebessprache zeigt sich besonders durch ', s.love_de, '. Wenn andere dieses Zeichen nicht in eine feste Rolle pressen, entsteht Vertrauen. Im Schatten können ', s.shadow_de, ' sichtbar werden. Wird dieser Schatten verstanden, ist er kein Fehler, sondern ein Hinweis auf reifere Nähe. ',
      'Beruflich sammelt ', s.label_de, ' Energie durch ', s.career_de, '. In der passenden Umgebung lernt dieses Zeichen schnell, macht Fähigkeiten sichtbar und bringt konkrete Ergebnisse hervor. Wenn Arbeit nur aus Wiederholung besteht oder gegen innere Werte läuft, zerstreut sich die Kraft. Deshalb helfen klare Etappen, ein realistischer Körperrhythmus und gesunde Anerkennung. ',
      'Für Alltag und Spiritualität lautet die wichtigste Frage: Wo fühle ich mich heute echter? Atemübungen, kurze Reflexionen, Mondzyklen und die Verbindung mit Aszendent und Mondzeichen vertiefen das Profil. ', s.wellness_de, ' Solche Routinen sind keine Flucht, sondern ein Weg, Verhalten zu bemerken und den eigenen Handlungsspielraum zu erweitern. ',
      'Beim Thema Kompatibilität sollte ', s.label_de, ' nie auf einfache Listen von guten oder schwierigen Paarungen reduziert werden. Elementfluss, Venus und Mars, das siebte Haus, das Mondzeichen und die Beziehungserfahrung beider Menschen gehören zusammen. Zeichen aus demselben Element fühlen sich oft vertraut an, während andere Elemente Wachstum und neue Perspektiven öffnen. Das Thema ', s.element_de, ' zeigt, wie jemand Kraft sammelt, wie Ermüdung entsteht und was in Krisen gebraucht wird. Kompatibilität bedeutet deshalb nicht Gleichheit, sondern die Fähigkeit, den Rhythmus des anderen zu lesen. ',
      'GoldMoodAstro Sternzeichen Seiten sind für Selbstreflexion und als Vorbereitung auf eine Beratung gedacht. Beim Lesen lohnt es sich, nicht nur die angenehmen Sätze auszuwählen, sondern auch die Punkte zu beachten, die Widerstand auslösen. Häufig liegt Entwicklung genau dort, wo zuerst Verteidigung entsteht. Bewusst gelebt hilft die ', s.label_de, ' Energie, Grenzen, Wünsche, Ängste und echte Motivation klarer zu sehen. Tageshoroskope zeigen eine vorübergehende Stimmung, dieser Leitfaden bietet dagegen einen stabileren Rahmen für wiederkehrende Muster. ',
      'Für die praktische Nutzung kann es hilfreich sein, einmal im Monat zu dieser Seite zurückzukehren. Markiere zuerst die Stärken, dann die wiederkehrenden Muster in Beziehung und Arbeit. Notiere anschließend, welche Reaktionen in den letzten vier Wochen öfter erschienen sind, wann du dich lebendiger gefühlt hast und welche Grenzen zu wenig beachtet wurden. So wird das Symbol ', s.label_de, ' von abstraktem Wissen zu einer persönlichen Karte für Entscheidungen im Alltag. ',
      'Dieser Text ist als allgemeines Sonnenzeichenprofil gedacht. Die präziseste Deutung entsteht mit Aszendent, Mond, Häusern und Aspekten. GoldMoodAstro Beraterinnen und Berater verbinden das ', s.label_de, ' Thema mit deiner persönlichen Karte und geben Orientierung für Liebe, Arbeit, emotionale Balance und Lebensrichtung.'
    )
    ELSE CONCAT(
      s.label_en, ' describes the core archetype of people born between ', s.date_en, '. The ', s.element_en, ' element, ', s.modality_en, ' modality and ', s.ruler_en, ' rulership give this sign its particular rhythm. In the GoldMoodAstro approach, ', s.label_en, ' is not just a short zodiac label, but a symbolic language for understanding decisions, relationships, motivation and emotional care. This guide offers a durable profile beyond a daily horoscope and creates a grounded starting point before moving into a personal birth chart reading. ',
      s.core_en, ' From the outside this energy may look like one simple trait, yet underneath it several needs are moving at once: safety, direction, expression, belonging and meaning. At its best, ', s.label_en, ' notices the inner voice, chooses responses with more awareness and uses strengths to bring life forward rather than to pressure others. ',
      'In relationships, ', s.label_en, ' is nourished by honest communication and emotional clarity. Its love language is often expressed through ', s.love_en, '. Trust grows when the other person listens without forcing this sign into a fixed role. The shadow side may show up as ', s.shadow_en, '. When this shadow is named with care, it becomes a guide toward more mature intimacy instead of a flaw to hide. ',
      'In work and creative life, ', s.label_en, ' gathers motivation through ', s.career_en, '. In the right environment this sign learns quickly, makes its talent visible and produces concrete results. Repetition without meaning, or a pace that conflicts with personal values, can scatter its energy. Clear milestones, a realistic body rhythm and healthy recognition keep the gift alive. ',
      'For spiritual and everyday self-care, the key question is: where do I feel most authentic today? Breathwork, short journaling, lunar tracking and reading the Sun sign together with the Moon and rising sign deepen the profile. ', s.wellness_en, ' These practices are less about escaping reality and more about noticing behavior, widening choice and returning to the self with kindness. ',
      'Compatibility should not reduce ', s.label_en, ' to a simple list of easy or difficult matches. Element flow, Venus and Mars placements, the seventh house, the Moon sign and each persons relationship history all matter. Signs from the same element often create a sense of familiarity, while different elements can open development and perspective. The ', s.element_en, ' theme shows how someone gathers strength, how fatigue appears and what is needed in moments of pressure. Compatibility is therefore not sameness, but the ability to read and respect another rhythm. ',
      'GoldMoodAstro zodiac pages are written for self-discovery and for preparing a more focused consultation. While reading, it helps to notice not only the sentences that feel flattering, but also the ones that create resistance. Growth often appears exactly where the first defense rises. When lived consciously, ', s.label_en, ' energy helps a person see boundaries, desires, fears and true motivation more clearly. Daily horoscopes describe a temporary atmosphere, while this guide offers a more stable framework for understanding repeated patterns. ',
      'For practical use, return to this page once a month. Mark the strengths first, then the repeating patterns in relationships and work. Write down which reactions appeared more than once during the last four weeks, when you felt more alive and which boundaries were ignored. This small practice turns the symbol of ', s.label_en, ' from abstract astrology knowledge into a personal map that supports decisions in everyday life. ',
      'This is a general Sun sign interpretation. The most accurate reading includes the rising sign, Moon sign, houses, planets and aspects. GoldMoodAstro consultants can connect the ', s.label_en, ' theme with your personal chart and offer more specific guidance for relationships, career, emotional regulation and life direction.'
    )
  END,
  CASE l.locale
    WHEN 'tr' THEN CONCAT(s.label_tr, ' burcu için element, ilişki, kariyer ve ruhsal bakım odağında kapsamlı GoldMoodAstro rehberi.')
    WHEN 'de' THEN CONCAT('Ein ausführlicher GoldMoodAstro Leitfaden für ', s.label_de, ' mit Element, Liebe, Beruf und Selbstfürsorge.')
    ELSE CONCAT('A complete GoldMoodAstro guide to ', s.label_en, ' covering element, love, career and self-care.')
  END,
  'warm',
  'GoldMoodAstro Editorial',
  'GoldMoodAstro Editorial Team',
  CONCAT('/uploads/zodiac/', s.sign_key, '.png'),
  1
FROM (
  SELECT 'aries' sign_key, 'Koç' label_tr, 'Aries' label_en, 'Widder' label_de, '21 Mart - 19 Nisan' date_tr, 'March 21 - April 19' date_en, '21. März - 19. April' date_de, 'Ateş' element_tr, 'Fire' element_en, 'Feuer' element_de, 'öncü' modality_tr, 'cardinal' modality_en, 'kardinal' modality_de, 'Mars' ruler_tr, 'Mars' ruler_en, 'Mars' ruler_de, 'Koç cesaret, başlangıç ve doğrudan eylem arzusuyla çalışır.' core_tr, 'Aries works through courage, beginnings and direct action.' core_en, 'Widder wirkt durch Mut, Anfangskraft und direkte Handlung.' core_de, 'heyecanı açıkça paylaşmak ve birlikte yeni deneyimler başlatmak' love_tr, 'clear enthusiasm and shared new experiences' love_en, 'klare Begeisterung und gemeinsame neue Erfahrungen' love_de, 'sabırsızlık, acele kararlar ve kontrolsüz rekabet' shadow_tr, 'impatience, rushed decisions and unmanaged competition' shadow_en, 'Ungeduld, vorschnelle Entscheidungen und unbewusster Wettbewerb' shadow_de, 'liderlik, girişimcilik, kriz çözme ve hareket isteyen görevler' career_tr, 'leadership, entrepreneurship, crisis solving and active roles' career_en, 'Führung, Unternehmertum, Krisenlösung und aktive Aufgaben' career_de, 'Düzenli hareket, bedende biriken ateşi temizler ve kararları berraklaştırır.' wellness_tr, 'Regular movement clears stored fire from the body and sharpens decisions.' wellness_en, 'Regelmäßige Bewegung klärt gespeicherte Feuerkraft und Entscheidungen.' wellness_de
  UNION ALL SELECT 'taurus','Boğa','Taurus','Stier','20 Nisan - 20 Mayıs','April 20 - May 20','20. April - 20. Mai','Toprak','Earth','Erde','sabit','fixed','fix','Venüs','Venus','Venus','Boğa istikrar, duyular, güven ve somut değerler üzerinden büyür.','Taurus grows through stability, senses, trust and tangible value.','Stier wächst durch Stabilität, Sinne, Vertrauen und greifbare Werte.','sadakat, dokunma, sakin zaman ve güvenilir sözler','loyalty, touch, calm time and reliable words','Loyalität, Berührung, ruhige Zeit und verlässliche Worte','inat, değişime direnç ve konfor alanına aşırı tutunma','stubbornness, resistance to change and overattachment to comfort','Sturheit, Widerstand gegen Wandel und Festhalten am Komfort','finans, tasarım, doğa, zanaat ve uzun vadeli üretim','finance, design, nature, craft and long-term production','Finanzen, Design, Natur, Handwerk und langfristige Arbeit','Yavaş yemek, doğa yürüyüşü ve bedensel farkındalık sinir sistemini düzenler.','Slow meals, nature walks and body awareness regulate the nervous system.','Langsames Essen, Naturgänge und Körperbewusstsein regulieren das Nervensystem.'
  UNION ALL SELECT 'gemini','İkizler','Gemini','Zwillinge','21 Mayıs - 20 Haziran','May 21 - June 20','21. Mai - 20. Juni','Hava','Air','Luft','değişken','mutable','beweglich','Merkür','Mercury','Merkur','İkizler merak, bağlantı, öğrenme ve hızlı zihinsel geçişlerle canlı kalır.','Gemini stays alive through curiosity, connection, learning and mental agility.','Zwillinge leben durch Neugier, Verbindung, Lernen und geistige Beweglichkeit.','sohbet, mizah, zihinsel oyun ve çeşitlilik','conversation, humor, mental play and variety','Gespräch, Humor, geistiges Spiel und Vielfalt','dağınıklık, yüzeysellik ve duygudan kaçmak için konuşmak','scattered focus, surface living and talking to avoid feeling','Zerstreuung, Oberflächlichkeit und Reden statt Fühlen','iletişim, eğitim, medya, satış ve çoklu proje yönetimi','communication, teaching, media, sales and multi-project work','Kommunikation, Bildung, Medien, Verkauf und mehrere Projekte','Ekran molaları ve düşünce boşaltma notları zihnin hızını yumuşatır.','Screen breaks and brain-dump notes soften the speed of the mind.','Bildschirmpausen und Gedankenlisten beruhigen das schnelle Denken.'
  UNION ALL SELECT 'cancer','Yengeç','Cancer','Krebs','21 Haziran - 22 Temmuz','June 21 - July 22','21. Juni - 22. Juli','Su','Water','Wasser','öncü','cardinal','kardinal','Ay','Moon','Mond','Yengeç hafıza, şefkat, aidiyet ve duygusal güvenlik ihtiyacıyla yön bulur.','Cancer navigates through memory, care, belonging and emotional safety.','Krebs orientiert sich durch Erinnerung, Fürsorge, Zugehörigkeit und emotionale Sicherheit.','korunmak, hatırlanmak, ev hissi ve içten ilgi','protection, remembrance, home feeling and sincere care','Schutz, Erinnerung, Heimatgefühl und echte Fürsorge','alınganlık, kabuğa çekilme ve geçmişe fazla tutunma','sensitivity, retreating into the shell and holding the past too tightly','Empfindlichkeit, Rückzug und zu starkes Festhalten an der Vergangenheit','bakım, danışmanlık, konaklama, aile işleri ve hafıza isteyen alanlar','care, counseling, hospitality, family work and memory-rich roles','Pflege, Beratung, Gastlichkeit, Familienarbeit und erinnerungsreiche Aufgaben','Su ritüelleri, güvenli alan düzeni ve duygu günlüğü iç dünyayı sakinleştirir.','Water rituals, safe spaces and emotion journaling calm the inner world.','Wasserrituale, sichere Räume und Gefühlstagebuch beruhigen die Innenwelt.'
  UNION ALL SELECT 'leo','Aslan','Leo','Löwe','23 Temmuz - 22 Ağustos','July 23 - August 22','23. Juli - 22. August','Ateş','Fire','Feuer','sabit','fixed','fix','Güneş','Sun','Sonne','Aslan yaratıcı ifade, kalp açıklığı, görünürlük ve onurlu liderlik ister.','Leo seeks creative expression, open-heartedness, visibility and noble leadership.','Löwe sucht kreativen Ausdruck, Herzenswärme, Sichtbarkeit und würdevolle Führung.','takdir, oyun, romantik jestler ve kalpten sadakat','appreciation, play, romantic gestures and heartfelt loyalty','Wertschätzung, Spiel, romantische Gesten und herzliche Treue','gurur, dramatizasyon ve ilgi eksikliğini kişisel almak','pride, dramatization and taking lack of attention personally','Stolz, Dramatisierung und fehlende Aufmerksamkeit persönlich nehmen','sahne, yönetim, yaratıcı üretim, çocuklar ve marka temsili','stage, management, creative production, children and brand representation','Bühne, Management, Kreativität, Kinder und Markenvertretung','Yaratıcı oyun ve kalp merkezli nefes özgüveni dengeler.','Creative play and heart-centered breathing balance confidence.','Kreatives Spiel und herzorientierter Atem balancieren Selbstvertrauen.'
  UNION ALL SELECT 'virgo','Başak','Virgo','Jungfrau','23 Ağustos - 22 Eylül','August 23 - September 22','23. August - 22. September','Toprak','Earth','Erde','değişken','mutable','beweglich','Merkür','Mercury','Merkur','Başak hizmet, düzen, analiz ve küçük iyileştirmelerin büyük etkisiyle parlar.','Virgo shines through service, order, analysis and meaningful small improvements.','Jungfrau strahlt durch Dienst, Ordnung, Analyse und sinnvolle kleine Verbesserungen.','güvenilirlik, yardım etmek, detay fark etmek ve gündelik emek','reliability, helping, noticing detail and daily devotion','Verlässlichkeit, Helfen, Detailblick und tägliche Hingabe','aşırı eleştiri, kaygı ve kusursuzluk baskısı','overcriticism, anxiety and pressure to be perfect','Überkritik, Sorge und Perfektionsdruck','analiz, sağlık, editörlük, operasyon, veri ve hizmet sistemleri','analysis, health, editing, operations, data and service systems','Analyse, Gesundheit, Redaktion, Betrieb, Daten und Dienstleistung','Esneme, sade rutin ve yapılacakları azaltmak zihinsel yükü hafifletir.','Stretching, simple routine and fewer tasks lighten the mental load.','Dehnung, einfache Routine und weniger Aufgaben erleichtern die mentale Last.'
  UNION ALL SELECT 'libra','Terazi','Libra','Waage','23 Eylül - 22 Ekim','September 23 - October 22','23. September - 22. Oktober','Hava','Air','Luft','öncü','cardinal','kardinal','Venüs','Venus','Venus','Terazi denge, estetik, ilişki bilinci ve adil seçimlerle anlam bulur.','Libra finds meaning through balance, aesthetics, relational awareness and fair choice.','Waage findet Sinn durch Balance, Ästhetik, Beziehungsbewusstsein und faire Wahl.','zarafet, ortak karar, nazik söz ve birlikte güzellik kurmak','grace, shared decisions, kind words and creating beauty together','Anmut, gemeinsame Entscheidungen, freundliche Worte und Schönheit','kararsızlık, memnun etme çabası ve çatışmadan kaçmak','indecision, people pleasing and avoiding conflict','Unentschlossenheit, Gefallenwollen und Konfliktvermeidung','hukuk, tasarım, arabuluculuk, sanat ve ilişki yönetimi','law, design, mediation, art and relationship management','Recht, Design, Vermittlung, Kunst und Beziehungsarbeit','Karar pratiği ve estetik düzenleme iç dengeyi güçlendirir.','Decision practice and aesthetic order strengthen inner balance.','Entscheidungspraxis und ästhetische Ordnung stärken innere Balance.'
  UNION ALL SELECT 'scorpio','Akrep','Scorpio','Skorpion','23 Ekim - 21 Kasım','October 23 - November 21','23. Oktober - 21. November','Su','Water','Wasser','sabit','fixed','fix','Mars ve Plüton','Mars and Pluto','Mars und Pluto','Akrep yoğunluk, dönüşüm, sezgi ve saklı olanı görme cesaretiyle derinleşir.','Scorpio deepens through intensity, transformation, intuition and courage to see what is hidden.','Skorpion vertieft sich durch Intensität, Wandlung, Intuition und Mut zum Verborgenen.','tam güven, tutku, sır paylaşımı ve duygusal dürüstlük','total trust, passion, shared secrets and emotional honesty','volles Vertrauen, Leidenschaft, geteilte Geheimnisse und Ehrlichkeit','kontrol, kıskançlık ve güvensizlikten doğan sınamalar','control, jealousy and tests born from mistrust','Kontrolle, Eifersucht und Prüfungen aus Misstrauen','psikoloji, araştırma, finansal kriz, şifa ve strateji','psychology, research, financial crisis, healing and strategy','Psychologie, Forschung, Finanzkrisen, Heilung und Strategie','Derin nefes, gölge çalışması ve güvenli paylaşım yoğunluğu arındırır.','Deep breathing, shadow work and safe sharing cleanse intensity.','Tiefer Atem, Schattenarbeit und sicheres Teilen reinigen Intensität.'
  UNION ALL SELECT 'sagittarius','Yay','Sagittarius','Schütze','22 Kasım - 21 Aralık','November 22 - December 21','22. November - 21. Dezember','Ateş','Fire','Feuer','değişken','mutable','beweglich','Jüpiter','Jupiter','Jupiter','Yay özgürlük, inanç, keşif ve geniş ufuklar aracılığıyla büyür.','Sagittarius grows through freedom, faith, discovery and wide horizons.','Schütze wächst durch Freiheit, Glaube, Entdeckung und weite Horizonte.','dürüstlük, macera, ortak öğrenme ve geniş alan','honesty, adventure, shared learning and spaciousness','Ehrlichkeit, Abenteuer, gemeinsames Lernen und Weite','patavatsızlık, bağlanma korkusu ve ayrıntıları küçümsemek','bluntness, fear of commitment and dismissing details','Direktheit, Bindungsangst und Geringschätzung von Details','eğitim, seyahat, yayıncılık, hukuk, rehberlik ve vizyon işleri','education, travel, publishing, law, guidance and vision work','Bildung, Reisen, Publizieren, Recht, Führung und Vision','Açık hava, anlam soruları ve şükran pratiği enerjiyi toplar.','Open air, meaning questions and gratitude practice gather energy.','Frische Luft, Sinnfragen und Dankbarkeit sammeln Energie.'
  UNION ALL SELECT 'capricorn','Oğlak','Capricorn','Steinbock','22 Aralık - 19 Ocak','December 22 - January 19','22. Dezember - 19. Januar','Toprak','Earth','Erde','öncü','cardinal','kardinal','Satürn','Saturn','Saturn','Oğlak sorumluluk, yapı, sabır ve zamanla büyüyen başarı üzerinden ilerler.','Capricorn advances through responsibility, structure, patience and success built over time.','Steinbock geht durch Verantwortung, Struktur, Geduld und langfristigen Erfolg voran.','saygı, emek, güvenilir plan ve uzun vadeli bağlılık','respect, effort, reliable plans and long-term devotion','Respekt, Einsatz, verlässliche Pläne und langfristige Bindung','katılık, duyguyu ertelemek ve başarıyla değer ölçmek','rigidity, postponing feelings and measuring worth by success','Härte, Gefühlaufschub und Selbstwert durch Leistung','yönetim, finans, mühendislik, strateji, kurumsal yapı ve planlama','management, finance, engineering, strategy, institutions and planning','Management, Finanzen, Technik, Strategie, Institutionen und Planung','Dinlenmeyi takvime almak ve bedene yumuşaklık vermek dayanıklılığı artırır.','Scheduling rest and softening the body increase endurance.','Geplante Ruhe und körperliche Weichheit stärken Ausdauer.'
  UNION ALL SELECT 'aquarius','Kova','Aquarius','Wassermann','20 Ocak - 18 Şubat','January 20 - February 18','20. Januar - 18. Februar','Hava','Air','Luft','sabit','fixed','fix','Satürn ve Uranüs','Saturn and Uranus','Saturn und Uranus','Kova özgünlük, gelecek vizyonu, topluluk ve zihinsel bağımsızlıkla hareket eder.','Aquarius moves through originality, future vision, community and mental independence.','Wassermann bewegt sich durch Originalität, Zukunftsblick, Gemeinschaft und geistige Freiheit.','arkadaşlık, zihinsel alan, ortak ideal ve özgünlüğe saygı','friendship, mental space, shared ideals and respect for originality','Freundschaft, Denkraum, gemeinsame Ideale und Respekt','duygusal mesafe, ters köşe olma ihtiyacı ve kopukluk','emotional distance, the need to be contrary and detachment','emotionale Distanz, Widerspruchsdrang und Abkopplung','teknoloji, sosyal etki, bilim, ekip sistemleri ve inovasyon','technology, social impact, science, team systems and innovation','Technologie, soziale Wirkung, Wissenschaft, Teamsysteme und Innovation','Toplulukla temas ve bedene dönüş pratikleri zihni insanileştirir.','Community contact and body-return practices humanize the mind.','Kontakt mit Gemeinschaft und Rückkehr zum Körper erden den Geist.'
  UNION ALL SELECT 'pisces','Balık','Pisces','Fische','19 Şubat - 20 Mart','February 19 - March 20','19. Februar - 20. März','Su','Water','Wasser','değişken','mutable','beweglich','Jüpiter ve Neptün','Jupiter and Neptune','Jupiter und Neptun','Balık sezgi, merhamet, hayal gücü ve görünmeyen bağları hissetme yeteneğiyle akar.','Pisces flows through intuition, compassion, imagination and sensing invisible bonds.','Fische fließen durch Intuition, Mitgefühl, Fantasie und unsichtbare Verbindungen.','şefkat, hayal paylaşımı, ruhsal yakınlık ve yumuşaklık','compassion, shared dreams, spiritual closeness and tenderness','Mitgefühl, geteilte Träume, spirituelle Nähe und Zartheit','sınır kaybı, kaçış ve başkalarının yükünü taşımak','loss of boundaries, escapism and carrying others burdens','Grenzverlust, Flucht und fremde Lasten tragen','sanat, şifa, müzik, danışmanlık, yardım ve yaratıcı akış','art, healing, music, counseling, care and creative flow','Kunst, Heilung, Musik, Beratung, Hilfe und kreativer Fluss','Sınır ritüelleri, müzik ve suyla temas sezgiyi dengeler.','Boundary rituals, music and water contact balance intuition.','Grenzrituale, Musik und Wasser balancieren Intuition.'
) s
CROSS JOIN (
  SELECT 'tr' locale UNION ALL SELECT 'en' UNION ALL SELECT 'de'
) l;

INSERT INTO astrology_kb (
  id, kind, key1, key2, key3, locale, title, content, short_summary, tone, source, author, image_url, is_active
)
SELECT
  UUID(),
  'sign_section',
  s.sign_key,
  t.topic_key,
  NULL,
  l.locale,
  CASE l.locale
    WHEN 'tr' THEN CONCAT(s.label_tr, ' Burcu ', t.title_tr)
    WHEN 'de' THEN CONCAT(s.label_de, ' und ', t.title_de)
    ELSE CONCAT(s.label_en, ' and ', t.title_en)
  END,
  CASE l.locale
    WHEN 'tr' THEN CONCAT(s.label_tr, ' için ', t.title_tr, ' başlığı ', t.focus_tr, ' üzerinden okunur. ', s.core_tr, ' Bu nedenle bu alanda en iyi sonuç, burcun doğal ritmini bastırmadan onu bilinçli bir seçime dönüştürmekle gelir. ', t.practice_tr, ' Gölge tarafta ', s.shadow_tr, ' bu konuyu zorlaştırabilir. Farkındalık arttıkça aynı enerji daha şefkatli, daha tutarlı ve daha üretken şekilde kullanılabilir.')
    WHEN 'de' THEN CONCAT('Für ', s.label_de, ' wird ', t.title_de, ' über ', t.focus_de, ' verstanden. ', s.core_de, ' Die besten Ergebnisse entstehen, wenn der natürliche Rhythmus nicht unterdrückt, sondern bewusst geführt wird. ', t.practice_de, ' Im Schatten können ', s.shadow_de, ' das Thema erschweren. Mit Bewusstsein wird dieselbe Energie freundlicher, klarer und produktiver.')
    ELSE CONCAT('For ', s.label_en, ', ', t.title_en, ' is understood through ', t.focus_en, '. ', s.core_en, ' The best results come when the natural rhythm is not suppressed but guided with awareness. ', t.practice_en, ' On the shadow side, ', s.shadow_en, ' can complicate this theme. With awareness, the same energy becomes kinder, clearer and more productive.')
  END,
  CASE l.locale
    WHEN 'tr' THEN CONCAT(s.label_tr, ' burcunun ', LOWER(t.title_tr), ' alanındaki temel dinamiği.')
    WHEN 'de' THEN CONCAT('Die zentrale Dynamik von ', s.label_de, ' in ', t.title_de, '.')
    ELSE CONCAT('The core ', t.title_en, ' dynamic for ', s.label_en, '.')
  END,
  'warm',
  'GoldMoodAstro Editorial',
  'GoldMoodAstro Editorial Team',
  NULL,
  1
FROM (
  SELECT 'aries' sign_key, 'Koç' label_tr, 'Aries' label_en, 'Widder' label_de, 'Koç cesaret, başlangıç ve doğrudan eylem arzusuyla çalışır.' core_tr, 'Aries works through courage, beginnings and direct action.' core_en, 'Widder wirkt durch Mut, Anfangskraft und direkte Handlung.' core_de, 'sabırsızlık, acele kararlar ve kontrolsüz rekabet' shadow_tr, 'impatience, rushed decisions and unmanaged competition' shadow_en, 'Ungeduld, vorschnelle Entscheidungen und unbewusster Wettbewerb' shadow_de
  UNION ALL SELECT 'taurus','Boğa','Taurus','Stier','Boğa istikrar, duyular, güven ve somut değerler üzerinden büyür.','Taurus grows through stability, senses, trust and tangible value.','Stier wächst durch Stabilität, Sinne, Vertrauen und greifbare Werte.','inat, değişime direnç ve konfor alanına aşırı tutunma','stubbornness, resistance to change and overattachment to comfort','Sturheit, Widerstand gegen Wandel und Festhalten am Komfort'
  UNION ALL SELECT 'gemini','İkizler','Gemini','Zwillinge','İkizler merak, bağlantı, öğrenme ve hızlı zihinsel geçişlerle canlı kalır.','Gemini stays alive through curiosity, connection, learning and mental agility.','Zwillinge leben durch Neugier, Verbindung, Lernen und geistige Beweglichkeit.','dağınıklık, yüzeysellik ve duygudan kaçmak için konuşmak','scattered focus, surface living and talking to avoid feeling','Zerstreuung, Oberflächlichkeit und Reden statt Fühlen'
  UNION ALL SELECT 'cancer','Yengeç','Cancer','Krebs','Yengeç hafıza, şefkat, aidiyet ve duygusal güvenlik ihtiyacıyla yön bulur.','Cancer navigates through memory, care, belonging and emotional safety.','Krebs orientiert sich durch Erinnerung, Fürsorge, Zugehörigkeit und emotionale Sicherheit.','alınganlık, kabuğa çekilme ve geçmişe fazla tutunma','sensitivity, retreating into the shell and holding the past too tightly','Empfindlichkeit, Rückzug und zu starkes Festhalten an der Vergangenheit'
  UNION ALL SELECT 'leo','Aslan','Leo','Löwe','Aslan yaratıcı ifade, kalp açıklığı, görünürlük ve onurlu liderlik ister.','Leo seeks creative expression, open-heartedness, visibility and noble leadership.','Löwe sucht kreativen Ausdruck, Herzenswärme, Sichtbarkeit und würdevolle Führung.','gurur, dramatizasyon ve ilgi eksikliğini kişisel almak','pride, dramatization and taking lack of attention personally','Stolz, Dramatisierung und fehlende Aufmerksamkeit persönlich nehmen'
  UNION ALL SELECT 'virgo','Başak','Virgo','Jungfrau','Başak hizmet, düzen, analiz ve küçük iyileştirmelerin büyük etkisiyle parlar.','Virgo shines through service, order, analysis and meaningful small improvements.','Jungfrau strahlt durch Dienst, Ordnung, Analyse und sinnvolle kleine Verbesserungen.','aşırı eleştiri, kaygı ve kusursuzluk baskısı','overcriticism, anxiety and pressure to be perfect','Überkritik, Sorge und Perfektionsdruck'
  UNION ALL SELECT 'libra','Terazi','Libra','Waage','Terazi denge, estetik, ilişki bilinci ve adil seçimlerle anlam bulur.','Libra finds meaning through balance, aesthetics, relational awareness and fair choice.','Waage findet Sinn durch Balance, Ästhetik, Beziehungsbewusstsein und faire Wahl.','kararsızlık, memnun etme çabası ve çatışmadan kaçmak','indecision, people pleasing and avoiding conflict','Unentschlossenheit, Gefallenwollen und Konfliktvermeidung'
  UNION ALL SELECT 'scorpio','Akrep','Scorpio','Skorpion','Akrep yoğunluk, dönüşüm, sezgi ve saklı olanı görme cesaretiyle derinleşir.','Scorpio deepens through intensity, transformation, intuition and courage to see what is hidden.','Skorpion vertieft sich durch Intensität, Wandlung, Intuition und Mut zum Verborgenen.','kontrol, kıskançlık ve güvensizlikten doğan sınamalar','control, jealousy and tests born from mistrust','Kontrolle, Eifersucht und Prüfungen aus Misstrauen'
  UNION ALL SELECT 'sagittarius','Yay','Sagittarius','Schütze','Yay özgürlük, inanç, keşif ve geniş ufuklar aracılığıyla büyür.','Sagittarius grows through freedom, faith, discovery and wide horizons.','Schütze wächst durch Freiheit, Glaube, Entdeckung und weite Horizonte.','patavatsızlık, bağlanma korkusu ve ayrıntıları küçümsemek','bluntness, fear of commitment and dismissing details','Direktheit, Bindungsangst und Geringschätzung von Details'
  UNION ALL SELECT 'capricorn','Oğlak','Capricorn','Steinbock','Oğlak sorumluluk, yapı, sabır ve zamanla büyüyen başarı üzerinden ilerler.','Capricorn advances through responsibility, structure, patience and success built over time.','Steinbock geht durch Verantwortung, Struktur, Geduld und langfristigen Erfolg voran.','katılık, duyguyu ertelemek ve başarıyla değer ölçmek','rigidity, postponing feelings and measuring worth by success','Härte, Gefühlaufschub und Selbstwert durch Leistung'
  UNION ALL SELECT 'aquarius','Kova','Aquarius','Wassermann','Kova özgünlük, gelecek vizyonu, topluluk ve zihinsel bağımsızlıkla hareket eder.','Aquarius moves through originality, future vision, community and mental independence.','Wassermann bewegt sich durch Originalität, Zukunftsblick, Gemeinschaft und geistige Freiheit.','duygusal mesafe, ters köşe olma ihtiyacı ve kopukluk','emotional distance, the need to be contrary and detachment','emotionale Distanz, Widerspruchsdrang und Abkopplung'
  UNION ALL SELECT 'pisces','Balık','Pisces','Fische','Balık sezgi, merhamet, hayal gücü ve görünmeyen bağları hissetme yeteneğiyle akar.','Pisces flows through intuition, compassion, imagination and sensing invisible bonds.','Fische fließen durch Intuition, Mitgefühl, Fantasie und unsichtbare Verbindungen.','sınır kaybı, kaçış ve başkalarının yükünü taşımak','loss of boundaries, escapism and carrying others burdens','Grenzverlust, Flucht und fremde Lasten tragen'
) s
CROSS JOIN (
  SELECT 'tr' locale UNION ALL SELECT 'en' UNION ALL SELECT 'de'
) l
CROSS JOIN (
  SELECT 'personality' topic_key, 'Kişilik' title_tr, 'Personality' title_en, 'Persönlichkeit' title_de, 'gündelik davranış, refleksler ve benlik algısı' focus_tr, 'daily behavior, reflexes and self-image' focus_en, 'Alltagsverhalten, Reflexe und Selbstbild' focus_de, 'Kısa gözlem notları ve düzenli geri bildirim bu alanı güçlendirir.' practice_tr, 'Short observation notes and regular feedback strengthen this area.' practice_en, 'Kurze Beobachtungsnotizen und regelmäßiges Feedback stärken diesen Bereich.' practice_de
  UNION ALL SELECT 'love','Aşk','Love','Liebe','yakınlık, güven, çekim ve sevgi dili','intimacy, trust, attraction and love language','Nähe, Vertrauen, Anziehung und Liebessprache','İhtiyacı açık söylemek ve karşı tarafı gerçekten dinlemek bağı derinleştirir.','Naming needs clearly and listening deeply strengthen the bond.','Klare Bedürfnisse und echtes Zuhören vertiefen die Bindung.'
  UNION ALL SELECT 'career','Kariyer','Career','Beruf','motivasyon, üretim tarzı ve görünür başarı','motivation, work style and visible success','Motivation, Arbeitsstil und sichtbarer Erfolg','Hedefi küçük aşamalara bölmek ve ilerlemeyi ölçmek yön duygusu verir.','Breaking goals into milestones and measuring progress creates direction.','Ziele in Etappen zu teilen und Fortschritt zu messen schafft Richtung.'
  UNION ALL SELECT 'wellness','Ruhsal Bakım','Wellness','Selbstfürsorge','beden ritmi, duygu düzenleme ve içsel merkez','body rhythm, emotional regulation and inner center','Körperrhythmus, emotionale Regulation und innere Mitte','Nefes, hareket ve günlük tutma burcun enerjisini dengede tutar.','Breath, movement and journaling keep the sign energy balanced.','Atem, Bewegung und Schreiben halten die Zeichenenergie im Gleichgewicht.'
) t;
