-- backend/src/db/sql/183_coffee_seed.sql
-- FAZ 22 — Kahve Falı Sembolleri (50+ Sembol)

INSERT IGNORE INTO coffee_symbols (id, slug, name_tr, meaning, category) VALUES
(UUID(), 'bird', 'Kuş', 'Haber, müjde, sevinçli bir gelişme.', '["haber", "genel"]'),
(UUID(), 'road', 'Yol', 'Yolculuk, yeni bir başlangıç, uzun bir süreç.', '["kariyer", "genel"]'),
(UUID(), 'heart', 'Kalp', 'Aşk, sevgi, duygusal bağlılık.', '["aşk"]'),
(UUID(), 'ring', 'Yüzük', 'Evlilik, nişan, sözleşme, bağlılık.', '["aşk", "sosyal"]'),
(UUID(), 'moon', 'Ay', 'Huzur, duygusal derinlik, gizli sırlar.', '["genel", "duygu"]'),
(UUID(), 'sun', 'Güneş', 'Başarı, aydınlanma, her şeyin yoluna girmesi.', '["kariyer", "genel"]'),
(UUID(), 'mountain', 'Dağ', 'Zorluk, engel, sabır gerektiren durum.', '["kariyer", "engel"]'),
(UUID(), 'fish', 'Balık', 'Kısmet, rızık, maddi bolluk.', '["para"]'),
(UUID(), 'snake', 'Yılan', 'Düşman, haset, gizli tehlike.', '["engel", "sosyal"]'),
(UUID(), 'eye', 'Göz', 'Nazar, izlenme, birinin dikkati üzerinizde.', '["sosyal", "nazar"]'),
(UUID(), 'key', 'Anahtar', 'Çözüm, yeni bir kapı açılması, mülk edinme.', '["para", "genel"]'),
(UUID(), 'tree', 'Ağaç', 'Aile, köklü değişim, sağlık, uzun ömür.', '["sağlık", "aile"]'),
(UUID(), 'horse', 'At', 'Murat, asalet, hızlı gerçekleşecek istek.', '["genel", "başarı"]'),
(UUID(), 'camel', 'Deve', 'Zenginlik, yük taşıma, büyük kısmet.', '["para"]'),
(UUID(), 'butterfly', 'Kelebek', 'Kısa süreli sevinç, değişim, flört.', '["aşk", "genel"]'),
(UUID(), 'ship', 'Gemi', 'Uzaklardan gelecek kısmet, deniz aşırı yolculuk.', '["genel", "haber"]'),
(UUID(), 'anchor', 'Çapa', 'Güven, yerleşik düzen, sağlam temel.', '["genel", "kariyer"]'),
(UUID(), 'bell', 'Çan', 'Önemli bir haber, duyuru, dikkat çekme.', '["haber"]'),
(UUID(), 'bridge', 'Köprü', 'Zor bir dönemi atlatma, bağlantı kurma.', '["genel", "sosyal"]'),
(UUID(), 'candle', 'Mum', 'Dileklerin kabulü, aydınlanma, umut.', '["genel"]'),
(UUID(), 'cross', 'Haç', 'Fedakarlık, inanç, zor bir sınav.', '["genel"]'),
(UUID(), 'cup', 'Kupa', 'Kutlama, başarı, sosyal başarı.', '["sosyal", "başarı"]'),
(UUID(), 'dog', 'Köpek', 'Sadık dost, koruma, güven.', '["sosyal"]'),
(UUID(), 'cat', 'Kedi', 'Nankörlük, kurnazlık, sezgi.', '["sosyal", "sezgi"]'),
(UUID(), 'eagle', 'Kartal', 'Güç, zafer, yüksek hedefler.', '["kariyer", "başarı"]'),
(UUID(), 'elephant', 'Fil', 'Şans, güç, bilge bir kişi.', '["genel", "şans"]'),
(UUID(), 'flower', 'Çiçek', 'Mutluluk, hediye, nezaket.', '["genel", "aşk"]'),
(UUID(), 'gate', 'Kapı', 'Fırsat, yeni bir hayat, geçiş.', '["genel", "kariyer"]'),
(UUID(), 'hammer', 'Çekiç', 'Çalışma, inşa etme, zor bir işin üstesinden gelme.', '["kariyer"]'),
(UUID(), 'hand', 'El', 'Yardım, destek, birinden gelecek el.', '["sosyal"]'),
(UUID(), 'ladder', 'Merdiven', 'Yükseliş, terfi, gelişim.', '["kariyer"]'),
(UUID(), 'lamp', 'Lamba', 'Fikir, çözüm, karanlığın bitişi.', '["genel"]'),
(UUID(), 'leaf', 'Yaprak', 'Şans, yenilenme, mevsimsel değişim.', '["genel"]'),
(UUID(), 'lion', 'Aslan', 'Cesaret, liderlik, prestij.', '["kariyer", "başarı"]'),
(UUID(), 'mouse', 'Fare', 'Küçük kayıp, hırsızlık, kemiren düşünceler.', '["para", "engel"]'),
(UUID(), 'owl', 'Baykuş', 'Bilgelik, gece haberi, gizem.', '["sezgi", "haber"]'),
(UUID(), 'peacock', 'Tavuskuşu', 'Gösteriş, gurur, miras.', '["para", "sosyal"]'),
(UUID(), 'rabbit', 'Tavşan', 'Hız, korku, bereket.', '["genel"]'),
(UUID(), 'scissors', 'Makas', 'Ayrılık, keskin karar, tartışma.', '["sosyal", "aşk"]'),
(UUID(), 'star', 'Yıldız', 'Şöhret, ilham, büyük şans.', '["başarı", "şans"]'),
(UUID(), 'swan', 'Kuğu', 'Zarafet, sadık eş, huzur.', '["aşk"]'),
(UUID(), 'sword', 'Kılıç', 'Mücadele, keskin zeka, zafer.', '["kariyer", "başarı"]'),
(UUID(), 'umbrella', 'Şemsiye', 'Korunma, sığınma, geçici kalkan.', '["genel"]'),
(UUID(), 'vase', 'Vazo', 'Mülk, birikim, estetik değer.', '["para"]'),
(UUID(), 'wall', 'Duvar', 'Engel, iletişim kopukluğu, sınır.', '["engel"]'),
(UUID(), 'window', 'Pencere', 'Bakış açısı, merak, dış dünyadan haber.', '["haber", "genel"]'),
(UUID(), 'wing', 'Kanat', 'Özgürlük, koruyucu melek, manevi destek.', '["genel"]'),
(UUID(), 'wolf', 'Kurt', 'Bağımsızlık, sadakat, strateji.', '["sosyal", "kariyer"]'),
(UUID(), 'box', 'Kutu', 'Sürpriz, gizli bir sır, hediye.', '["genel", "haber"]'),
(UUID(), 'crown', 'Taç', 'Onur, rütbe, itibar kazanma.', '["başarı", "kariyer"]');
