-- backend/src/db/sql/185_dream_seed.sql
-- FAZ 23 — Rüya Sembolleri (100+ Sembol)

INSERT IGNORE INTO dream_symbols (id, slug, name_tr, meaning, category) VALUES
(UUID(), 'water', 'Su', 'Duygusal durum, saflık, yenilenme veya belirsizlik.', '["genel", "duygu"]'),
(UUID(), 'snake', 'Yılan', 'Düşman, haset, şifa veya dönüşüm.', '["uyarı", "dönüşüm"]'),
(UUID(), 'flying', 'Uçmak', 'Özgürlük, kontrol kaybı veya yüksek hedefler.', '["genel", "psikolojik"]'),
(UUID(), 'falling', 'Düşmek', 'Kontrol kaybı, güvensizlik, başarısızlık korkusu.', '["uyarı", "psikolojik"]'),
(UUID(), 'teeth_falling', 'Diş Dökülmesi', 'Güç kaybı, yaşlanma korkusu veya sözlerin ağırlığı.', '["uyarı", "sağlık"]'),
(UUID(), 'fire', 'Ateş', 'Tutku, öfke, yıkım veya arınma.', '["duygu", "uyarı"]'),
(UUID(), 'death', 'Ölüm', 'Bir dönemin bitişi, yeni başlangıçlar, değişim.', '["dönüşüm", "genel"]'),
(UUID(), 'baby', 'Bebek', 'Yeni fikirler, masumiyet, korunmaya muhtaç durum.', '["müjde", "genel"]'),
(UUID(), 'money', 'Para', 'Özdeğer, güç, fırsatlar veya maddi kaygı.', '["para", "psikolojik"]'),
(UUID(), 'dog', 'Köpek', 'Sadakat, koruma, arkadaşlık veya içgüdüler.', '["sosyal", "genel"]'),
(UUID(), 'cat', 'Kedi', 'Bağımsızlık, sezgi, nankörlük veya gizem.', '["sezgi", "sosyal"]'),
(UUID(), 'house', 'Ev', 'Benlik, zihin, aile veya güvenlik.', '["aile", "psikolojik"]'),
(UUID(), 'mountain', 'Dağ', 'Büyük hedefler, zorluklar, başarı veya engel.', '["başarı", "engel"]'),
(UUID(), 'sea', 'Deniz', 'Bilinçaltı, sonsuzluk, huzur veya fırtına.', '["duygu", "genel"]'),
(UUID(), 'rain', 'Yağmur', 'Arınma, hüzün, bereket veya duygusal boşalım.', '["müjde", "duygu"]'),
(UUID(), 'sun', 'Güneş', 'Aydınlanma, enerji, yaşam gücü, başarı.', '["müjde", "başarı"]'),
(UUID(), 'moon', 'Ay', 'Dişil enerji, döngüler, gizli sırlar, sezgiler.', '["sezgi", "genel"]'),
(UUID(), 'stars', 'Yıldızlar', 'Umut, rehberlik, kader, ilham.', '["müjde", "genel"]'),
(UUID(), 'bridge', 'Köprü', 'Geçiş dönemi, bağlantı, karar anı.', '["dönüşüm", "genel"]'),
(UUID(), 'road', 'Yol', 'Yaşam yolu, yön seçimi, süreç.', '["kariyer", "genel"]'),
(UUID(), 'door', 'Kapı', 'Yeni fırsatlar, sırlar, engeller veya geçiş.', '["müjde", "genel"]'),
(UUID(), 'key', 'Anahtar', 'Çözüm, yetki, gizli bilgi, mülk.', '["başarı", "genel"]'),
(UUID(), 'forest', 'Orman', 'Bilinçaltının derinlikleri, kafa karışıklığı veya büyüme.', '["psikolojik", "genel"]'),
(UUID(), 'flower', 'Çiçek', 'Güzellik, gelişim, kısa süreli mutluluk.', '["genel", "duygu"]'),
(UUID(), 'tree', 'Ağaç', 'Soy, büyüme, sağlamlık, uzun ömür.', '["aile", "sağlık"]'),
(UUID(), 'bird', 'Kuş', 'Maneviyat, özgürlük, haber, ruh.', '["müjde", "haber"]'),
(UUID(), 'lion', 'Aslan', 'Cesaret, liderlik, saldırganlık veya güç.', '["kariyer", "başarı"]'),
(UUID(), 'wolf', 'Kurt', 'Yalnızlık, sadakat, vahşi doğa, strateji.', '["sosyal", "genel"]'),
(UUID(), 'horse', 'At', 'Enerji, dürtüler, zafer, asalet.', '["başarı", "genel"]'),
(UUID(), 'spider', 'Örümcek', 'Manipülasyon, yaratıcılık, tuzak veya sabır.', '["uyarı", "genel"]'),
(UUID(), 'bee', 'Arı', 'Çalışkanlık, topluluk, tatlı sonuçlar.', '["kariyer", "müjde"]'),
(UUID(), 'butterfly', 'Kelebek', 'Dönüşüm, kırılganlık, ruhsal gelişim.', '["dönüşüm", "genel"]'),
(UUID(), 'fish', 'Balık', 'Bereket, bilinçaltı mesajları, kısmet.', '["müjde", "para"]'),
(UUID(), 'car', 'Araba', 'Yaşamın kontrolü, motivasyon, sosyal statü.', '["kariyer", "psikolojik"]'),
(UUID(), 'plane', 'Uçak', 'Hızlı değişim, yüksekten bakış, kaçış.', '["genel", "kariyer"]'),
(UUID(), 'train', 'Tren', 'Kader yolu, toplumsal akış, kaçırılan fırsatlar.', '["genel", "uyarı"]'),
(UUID(), 'ship', 'Gemi', 'Duygusal yolculuk, uzaklar, ticari işler.', '["genel", "para"]'),
(UUID(), 'wedding', 'Düğün', 'Birlik, taahhüt, yeni bir evre veya kaygı.', '["sosyal", "aşk"]'),
(UUID(), 'ring', 'Yüzük', 'Sonsuzluk, bağlılık, söz verme.', '["aşk", "sosyal"]'),
(UUID(), 'mirror', 'Ayna', 'Öz-yüzleşme, gerçekler, narsizm.', '["psikolojik", "genel"]'),
(UUID(), 'clock', 'Saat', 'Zaman baskısı, ömür, geç kalma korkusu.', '["uyarı", "psikolojik"]'),
(UUID(), 'ladder', 'Merdiven', 'Yükseliş, çaba, sosyal basamaklar.', '["kariyer", "başarı"]'),
(UUID(), 'wall', 'Duvar', 'Sınırlar, koruma, engellenmiş hissetme.', '["engel", "genel"]'),
(UUID(), 'window', 'Pencere', 'Dış dünyaya bakış, umut, fırsat kollama.', '["genel", "haber"]'),
(UUID(), 'knife', 'Bıçak', 'Keskin kararlar, saldırganlık, ayrılık.', '["uyarı", "sosyal"]'),
(UUID(), 'blood', 'Kan', 'Yaşam gücü, acı, fedakarlık, soy.', '["sağlık", "duygu"]'),
(UUID(), 'gold', 'Altın', 'Değerli olan, manevi zenginlik, başarı.', '["başarı", "para"]'),
(UUID(), 'bread', 'Ekmek', 'Temel ihtiyaçlar, rızık, paylaşım.', '["müjde", "aile"]'),
(UUID(), 'shoes', 'Ayakkabı', 'Yolculuk hazırlığı, duruş, hazırlık.', '["genel", "kariyer"]'),
(UUID(), 'hat', 'Şapka', 'Düşünceler, gizleme, statü.', '["psikolojik", "sosyal"]'),
(UUID(), 'nakedness', 'Çıplaklık', 'Savunmasızlık, utanç veya gerçek benlik.', '["psikolojik", "uyarı"]'),
(UUID(), 'chase', 'Kovalanmak', 'Kaçılan gerçekler, stres, tehdit altındaki his.', '["uyarı", "psikolojik"]'),
(UUID(), 'test', 'Sınava Girmek', 'Yetersizlik korkusu, hazırlıksız hissetme.', '["psikolojik", "kariyer"]'),
(UUID(), 'being_lost', 'Kaybolmak', 'Yön kaybı, kafa karışıklığı, belirsizlik.', '["uyarı", "psikolojik"]'),
(UUID(), 'pregnant', 'Hamilelik', 'Potansiyel, yeni bir projenin doğuşu, büyüme.', '["müjde", "dönüşüm"]'),
(UUID(), 'tears', 'Gözyaşı', 'Duygusal boşalım, şifa, hüzün.', '["duygu", "sağlık"]'),
(UUID(), 'smile', 'Gülümsemek', 'Huzur, kabul, olumlu süreç.', '["müjde", "duygu"]'),
(UUID(), 'crowd', 'Kalabalık', 'Toplum baskısı, yalnızlık korkusu, kargaşa.', '["sosyal", "psikolojik"]'),
(UUID(), 'tunnel', 'Tünel', 'Zor bir geçiş, daralma, tünelin sonundaki ışık.', '["dönüşüm", "genel"]'),
(UUID(), 'elevator', 'Asansör', 'Hızlı iniş çıkışlar, kontrolsüz değişim.', '["kariyer", "psikolojik"]'),
(UUID(), 'crying', 'Ağlamak', 'İçsel rahatlama, dertlerin bitişi.', '["müjde", "duygu"]'),
(UUID(), 'storm', 'Fırtına', 'Kaos, öfke, büyük değişim dalgası.', '["uyarı", "genel"]'),
(UUID(), 'snow', 'Kar', 'Saflık, duygusal soğukluk, örtülen sırlar.', '["genel", "duygu"]'),
(UUID(), 'ice', 'Buz', 'Donmuş duygular, durağanlık, risk.', '["uyarı", "duygu"]'),
(UUID(), 'desert', 'Çöl', 'Yalnızlık, kuraklık, manevi susuzluk.', '["psikolojik", "genel"]'),
(UUID(), 'island', 'Ada', 'Tecrit, huzur, kendine yetme.', '["psikolojik", "genel"]'),
(UUID(), 'bridge_collapsing', 'Köprü Yıkılması', 'Kesilen bağlantılar, tehlikeli geçiş.', '["uyarı", "sosyal"]'),
(UUID(), 'falling_stars', 'Yıldız Kayması', 'Dileklerin kabulü, büyük değişim, mucize.', '["müjde", "genel"]'),
(UUID(), 'earthquake', 'Deprem', 'Temellerin sarsılması, ani değişim, şok.', '["uyarı", "dönüşüm"]'),
(UUID(), 'flood', 'Sel', 'Kontrol edilemeyen duygular, her şeyi silip süpürme.', '["uyarı", "duygu"]'),
(UUID(), 'rainbow', 'Gökkuşağı', 'Fırtına sonrası huzur, barış, umut.', '["müjde", "genel"]'),
(UUID(), 'black_color', 'Siyah', 'Bilinmezlik, yas, güç veya gizem.', '["genel", "psikolojik"]'),
(UUID(), 'white_color', 'Beyaz', 'Saflık, başlangıç, netlik.', '["genel", "müjde"]'),
(UUID(), 'red_color', 'Kırmızı', 'Tutku, öfke, enerji veya tehlike.', '["duygu", "uyarı"]'),
(UUID(), 'green_color', 'Yeşil', 'Şifa, büyüme, kıskançlık veya denge.', '["sağlık", "genel"]'),
(UUID(), 'blue_color', 'Mavi', 'Huzur, iletişim, ruhsallık.', '["genel", "duygu"]'),
(UUID(), 'yellow_color', 'Sarı', 'Zeka, hastalık, dikkat veya neşe.', '["genel", "sağlık"]'),
(UUID(), 'old_person', 'Yaşlı Kişi', 'Bilgelik, geçmiş, deneyim.', '["sezgi", "genel"]'),
(UUID(), 'priest_imam', 'Din Görevlisi', 'Manevi rehberlik, vicdan, toplumsal kurallar.', '["sezgi", "sosyal"]'),
(UUID(), 'teacher', 'Öğretmen', 'Öğrenilmesi gereken ders, otorite, rehber.', '["kariyer", "genel"]'),
(UUID(), 'king_queen', 'Kral/Kraliçe', 'Otorite, başarı, ego veya sorumluluk.', '["kariyer", "başarı"]'),
(UUID(), 'thief', 'Hırsız', 'Enerji emen durum, kayıp korkusu, gizli düşman.', '["uyarı", "para"]'),
(UUID(), 'prison', 'Hapishane', 'Sıkışmışlık, suçluluk, kısıtlama.', '["psikolojik", "uyarı"]'),
(UUID(), 'hospital', 'Hastane', 'Şifa ihtiyacı, bakım, zayıflık.', '["sağlık", "genel"]'),
(UUID(), 'school', 'Okul', 'Hayat dersleri, sosyal kaygılar, gelişim.', '["psikolojik", "sosyal"]'),
(UUID(), 'war', 'Savaş', 'İçsel çatışma, kaos, büyük mücadele.', '["uyarı", "psikolojik"]'),
(UUID(), 'flying_carpet', 'Uçan Halı', 'Manevi yükseliş, hayal gücü, kolaylık.', '["müjde", "genel"]'),
(UUID(), 'giant', 'Dev', 'Büyük sorunlar veya ezici güç.', '["engel", "uyarı"]'),
(UUID(), 'dwarf', 'Cüce', 'Küçümsenmiş hisler, detaylar, kurnazlık.', '["psikolojik", "genel"]'),
(UUID(), 'ghost', 'Hayalet', 'Geçmişin izleri, bitmemiş işler, korkular.', '["psikolojik", "uyarı"]'),
(UUID(), 'angel', 'Melek', 'Korunma, ilahi mesaj, yüksek bilinç.', '["müjde", "sezgi"]'),
(UUID(), 'devil', 'Şeytan', 'Nefis, gölge yanlar, ayartılma.', '["uyarı", "psikolojik"]'),
(UUID(), 'snake_biting', 'Yılan Isırması', 'Beklenmedik darbe, ihanet, ani uyanış.', '["uyarı", "sosyal"]'),
(UUID(), 'running_away', 'Kaçmak', 'Sorumluluktan kaçış, korkuyla yüzleşememe.', '["psikolojik", "uyarı"]'),
(UUID(), 'singing', 'Şarkı Söylemek', 'Kendini ifade, neşe, uyum.', '["genel", "duygu"]'),
(UUID(), 'dancing', 'Dans Etmek', 'Yaşam enerjisi, kutlama, akışta olma.', '["genel", "duygu"]'),
(UUID(), 'fighting', 'Kavga Etmek', 'Öfke birikimi, zıt fikirler, savunma.', '["uyarı", "sosyal"]'),
(UUID(), 'killing', 'Öldürmek', 'Bir huyu veya alışkanlığı bitirme, öfke.', '["dönüşüm", "uyarı"]'),
(UUID(), 'saving_someone', 'Birini Kurtarmak', 'Yardımseverlik, sorumluluk, öz-kahramanlık.', '["sosyal", "genel"]'),
(UUID(), 'laughing', 'Gülmek', 'Hafifleme, sorunların çözümü.', '["müjde", "duygu"]'),
(UUID(), 'climbing', 'Tırmanmak', 'Zahmetli başarı, gelişim çabası.', '["kariyer", "başarı"]');
