-- =============================================================
-- FILE: 199_blog_posts_seed.sql
-- GoldMoodAstro editorial blog seeds
-- =============================================================

INSERT INTO custom_pages (
  id, module_key, is_published, featured, featured_image, display_order, order_num, created_at, updated_at
) VALUES
  ('b1000000-0000-4000-8000-000000000001', 'blog', 1, 1, '/img/natal_chart.png', 101, 101, NOW(3), NOW(3)),
  ('b1000000-0000-4000-8000-000000000002', 'blog', 1, 1, '/img/synastry_chart.png', 102, 102, NOW(3), NOW(3)),
  ('b1000000-0000-4000-8000-000000000003', 'blog', 1, 1, '/img/daily_reading.png', 103, 103, NOW(3), NOW(3)),
  ('b1000000-0000-4000-8000-000000000004', 'blog', 1, 0, '/img/natal_chart.png', 104, 104, NOW(3), NOW(3)),
  ('b1000000-0000-4000-8000-000000000005', 'blog', 1, 0, '/img/daily_reading.png', 105, 105, NOW(3), NOW(3)),
  ('b1000000-0000-4000-8000-000000000006', 'blog', 1, 0, '/img/synastry_chart.png', 106, 106, NOW(3), NOW(3)),
  ('b1000000-0000-4000-8000-000000000007', 'blog', 1, 0, '/support_ai.webp', 107, 107, NOW(3), NOW(3)),
  ('b1000000-0000-4000-8000-000000000008', 'blog', 1, 0, '/img/daily_reading.png', 108, 108, NOW(3), NOW(3))
ON DUPLICATE KEY UPDATE
  module_key = VALUES(module_key),
  is_published = VALUES(is_published),
  featured = VALUES(featured),
  featured_image = VALUES(featured_image),
  display_order = VALUES(display_order),
  order_num = VALUES(order_num),
  updated_at = NOW(3);

INSERT INTO custom_pages_i18n (
  id, custom_page_id, locale, title, slug, content, summary, featured_image_alt, meta_title, meta_description, tags, created_at, updated_at
) VALUES
  ('b1tr0000-0000-4000-8000-000000000001', 'b1000000-0000-4000-8000-000000000001', 'tr', 'Doğum Haritası Nedir, İlk Bakışta Neler Anlatır?', 'dogum-haritasi-nedir', '{"html":"<h2>Doğum haritası nedir?</h2><p>Doğum haritası, doğduğunuz anda gezegenlerin gökyüzündeki konumunu sembolik bir dil olarak okur. Güneş burcu genel yönünüzü, Ay burcu duygusal ihtiyacınızı, yükselen burç ise hayata yaklaşım biçiminizi gösterir.</p><h3>İlk okumada nelere bakılır?</h3><p>GoldMoodAstro danışmanları haritayı tek bir burca indirgemeden evler, açılar ve element dengesiyle birlikte değerlendirir. Bu yaklaşım ilişki, kariyer, karar alma ve içsel döngüler hakkında daha dengeli bir rehberlik sağlar.</p>"}', 'Doğum haritasının temel anlamını ve ilk danışmanlıkta hangi göstergelerin birlikte okunduğunu öğrenin.', 'Mor ve altın tonlarında doğum haritası görseli', 'Doğum Haritası Nedir? Astrolojik Harita Rehberi', 'Doğum haritası ne anlatır, Güneş, Ay ve yükselen burç nasıl birlikte yorumlanır, GoldMoodAstro rehberi.', 'astroloji,dogum haritasi,yukselen burc', NOW(3), NOW(3)),
  ('b1en0000-0000-4000-8000-000000000001', 'b1000000-0000-4000-8000-000000000001', 'en', 'What Is a Birth Chart and What Does It Reveal First?', 'what-is-a-birth-chart', '{"html":"<h2>What is a birth chart?</h2><p>A birth chart maps the symbolic sky at the moment you were born. Your Sun sign describes your core direction, the Moon sign reflects emotional needs, and the rising sign shows how you meet life.</p><h3>What is reviewed first?</h3><p>GoldMoodAstro consultants read the chart as a whole, combining houses, aspects, and elemental balance. This makes the session useful for relationships, career questions, timing, and personal reflection.</p>"}', 'A practical introduction to birth charts and the first indicators reviewed in an astrology session.', 'Purple and gold birth chart illustration', 'What Is a Birth Chart? Astrology Guide', 'Learn what a birth chart reveals and how Sun, Moon, rising sign, houses, and aspects work together.', 'astrology,birth chart,rising sign', NOW(3), NOW(3)),
  ('b1de0000-0000-4000-8000-000000000001', 'b1000000-0000-4000-8000-000000000001', 'de', 'Was ist ein Geburtshoroskop und was zeigt es zuerst?', 'was-ist-ein-geburtshoroskop', '{"html":"<h2>Was ist ein Geburtshoroskop?</h2><p>Ein Geburtshoroskop beschreibt den symbolischen Himmel zum Zeitpunkt der Geburt. Das Sonnenzeichen zeigt die Grundrichtung, der Mond emotionale Bedürfnisse und der Aszendent die Art, wie Sie dem Leben begegnen.</p><h3>Was wird zuerst betrachtet?</h3><p>GoldMoodAstro Beraterinnen und Berater lesen Häuser, Aspekte und Elementverteilung gemeinsam. So entsteht eine Orientierung für Beziehungen, Beruf, Entscheidungen und persönliche Entwicklung.</p>"}', 'Eine klare Einführung in Geburtshoroskope und die ersten Faktoren einer astrologischen Beratung.', 'Violette und goldene Geburtshoroskop Illustration', 'Was ist ein Geburtshoroskop? Astrologie Guide', 'Erfahren Sie, was ein Geburtshoroskop zeigt und wie Sonne, Mond, Aszendent, Häuser und Aspekte zusammenspielen.', 'astrologie,geburtshoroskop,aszendent', NOW(3), NOW(3)),

  ('b1tr0000-0000-4000-8000-000000000002', 'b1000000-0000-4000-8000-000000000002', 'tr', 'Sinastri Uyumu Nasıl Okunur?', 'sinastri-uyumu-nasil-okunur', '{"html":"<h2>Sinastri neyi karşılaştırır?</h2><p>Sinastri, iki kişinin doğum haritasını yan yana okuyarak ilişkinin akışını anlamaya çalışır. Venüs ve Mars çekimi, Ay güven ihtiyacını, Merkür ise iletişim ritmini gösterir.</p><h3>Uyum tek bir skor değildir</h3><p>Sağlıklı bir sinastri yorumu sadece kolay açılara bakmaz. Zorlayıcı açılar da farkındalık, sınır ve büyüme alanlarını gösterebilir. Bu yüzden danışmanlıkta ilişkinin gerçek dinamiği, beklenti ve zamanlama birlikte ele alınır.</p>"}', 'Sinastri haritasında ilişki uyumu, çekim, iletişim ve duygusal güven göstergeleri nasıl okunur?', 'İki haritanın yan yana gösterildiği sinastri görseli', 'Sinastri Uyumu Nasıl Okunur?', 'Sinastri haritası ilişki uyumu, Venüs, Mars, Ay ve Merkür göstergeleriyle nasıl yorumlanır?', 'sinastri,iliski uyumu,astroloji', NOW(3), NOW(3)),
  ('b1en0000-0000-4000-8000-000000000002', 'b1000000-0000-4000-8000-000000000002', 'en', 'How to Read Synastry Compatibility', 'how-to-read-synastry-compatibility', '{"html":"<h2>What does synastry compare?</h2><p>Synastry places two birth charts side by side to understand relationship dynamics. Venus and Mars describe attraction, the Moon shows emotional safety, and Mercury reveals communication rhythm.</p><h3>Compatibility is not one score</h3><p>A useful synastry reading considers supportive and challenging aspects together. Tension can reveal boundaries, growth points, and timing questions, especially when the relationship is already important in real life.</p>"}', 'A guide to relationship compatibility through synastry, attraction, communication, and emotional safety.', 'Two astrology charts side by side for synastry', 'How to Read Synastry Compatibility', 'Learn how synastry uses Venus, Mars, Moon, and Mercury to interpret relationship dynamics.', 'synastry,relationship compatibility,astrology', NOW(3), NOW(3)),
  ('b1de0000-0000-4000-8000-000000000002', 'b1000000-0000-4000-8000-000000000002', 'de', 'Synastrie richtig lesen', 'synastrie-richtig-lesen', '{"html":"<h2>Was vergleicht Synastrie?</h2><p>Synastrie legt zwei Geburtshoroskope nebeneinander, um Beziehungsdynamiken zu verstehen. Venus und Mars zeigen Anziehung, der Mond emotionale Sicherheit und Merkur den Kommunikationsrhythmus.</p><h3>Kompatibilität ist keine einzelne Zahl</h3><p>Eine hilfreiche Synastrie betrachtet harmonische und herausfordernde Aspekte gemeinsam. Spannung kann Grenzen, Wachstum und Timing sichtbar machen, besonders wenn die Beziehung im Alltag bereits Bedeutung hat.</p>"}', 'Ein Leitfaden zu Synastrie, Beziehungskompatibilität, Anziehung, Kommunikation und emotionaler Sicherheit.', 'Zwei Horoskope nebeneinander als Synastrie Bild', 'Synastrie richtig lesen', 'Erfahren Sie, wie Synastrie mit Venus, Mars, Mond und Merkur Beziehungsdynamiken deutet.', 'synastrie,beziehung,astrologie', NOW(3), NOW(3)),

  ('b1tr0000-0000-4000-8000-000000000003', 'b1000000-0000-4000-8000-000000000003', 'tr', 'Tarot Açılımında Daha İyi Soru Nasıl Sorulur?', 'tarot-acilimi-soru-sorma-rehberi', '{"html":"<h2>Tarot sorusu neden önemlidir?</h2><p>Tarot danışmanlığında soru ne kadar netse, açılım da o kadar uygulanabilir olur. Evet veya hayır yerine süreç, seçenek ve içgörü odaklı sorular daha fazla rehberlik sağlar.</p><h3>İyi soru örnekleri</h3><p>Bu ilişki bana ne öğretiyor, kariyer kararımda hangi dinamiği görmeliyim, bu ay enerjimi nasıl daha iyi yönetirim gibi sorular kartların sembolik dilini günlük hayata taşır.</p>"}', 'Tarot açılımına girmeden önce daha net, etik ve uygulanabilir sorular hazırlamak için kısa rehber.', 'Tarot kartları ve günlük not defteri görseli', 'Tarot Açılımı İçin Soru Sorma Rehberi', 'Tarot danışmanlığında daha iyi soru nasıl sorulur, hangi soru tipleri daha anlamlı yanıt üretir?', 'tarot,tarot sorulari,ruhsal danismanlik', NOW(3), NOW(3)),
  ('b1en0000-0000-4000-8000-000000000003', 'b1000000-0000-4000-8000-000000000003', 'en', 'How to Ask Better Tarot Questions', 'how-to-ask-better-tarot-questions', '{"html":"<h2>Why does the question matter?</h2><p>In a tarot session, a clearer question leads to a more useful spread. Instead of yes or no, process based questions often reveal options, patterns, and practical next steps.</p><h3>Helpful examples</h3><p>What is this relationship teaching me, what dynamic should I notice in my career decision, and how can I manage my energy this month are questions that bring symbolism into daily life.</p>"}', 'A short guide to clearer, ethical, and more useful questions before a tarot reading.', 'Tarot cards with a journal', 'How to Ask Better Tarot Questions', 'Learn how to frame tarot questions that invite insight, choices, and practical reflection.', 'tarot,tarot questions,spiritual guidance', NOW(3), NOW(3)),
  ('b1de0000-0000-4000-8000-000000000003', 'b1000000-0000-4000-8000-000000000003', 'de', 'Bessere Tarot-Fragen stellen', 'bessere-tarot-fragen-stellen', '{"html":"<h2>Warum ist die Frage wichtig?</h2><p>In einer Tarot Beratung führt eine klare Frage zu einer hilfreicheren Legung. Statt Ja oder Nein bringen prozessorientierte Fragen oft Optionen, Muster und nächste Schritte hervor.</p><h3>Hilfreiche Beispiele</h3><p>Was lehrt mich diese Beziehung, welche Dynamik sollte ich bei meiner beruflichen Entscheidung beachten, und wie kann ich meine Energie diesen Monat besser führen, sind alltagstaugliche Fragen.</p>"}', 'Ein kurzer Leitfaden für klare, ethische und nützliche Fragen vor einer Tarot Beratung.', 'Tarotkarten mit Notizbuch', 'Bessere Tarot-Fragen stellen', 'Lernen Sie, Tarot Fragen so zu formulieren, dass sie Einsicht, Optionen und Reflexion ermöglichen.', 'tarot,tarot fragen,spirituelle beratung', NOW(3), NOW(3)),

  ('b1tr0000-0000-4000-8000-000000000004', 'b1000000-0000-4000-8000-000000000004', 'tr', 'Numerolojide Hayat Yolu Sayısı Ne Anlatır?', 'numeroloji-hayat-yolu-sayisi', '{"html":"<h2>Hayat yolu sayısı nedir?</h2><p>Hayat yolu sayısı, doğum tarihindeki rakamların sadeleştirilmesiyle hesaplanan temel numeroloji göstergesidir. Kişinin öğrenme biçimi, motivasyonu ve tekrar eden yaşam temaları hakkında sembolik bir çerçeve sunar.</p><h3>Nasıl yorumlanır?</h3><p>Tek başına kader hükmü değildir. Doğum haritası, kişisel yıl döngüsü ve danışanın gerçek hedefleriyle birlikte ele alındığında karar süreçlerine yumuşak bir farkındalık kazandırır.</p>"}', 'Hayat yolu sayısının numerolojideki yerini, nasıl hesaplandığını ve danışmanlıkta nasıl kullanıldığını öğrenin.', 'Numeroloji sayıları ve altın çizgiler', 'Numerolojide Hayat Yolu Sayısı', 'Hayat yolu sayısı nedir, nasıl hesaplanır ve numeroloji danışmanlığında nasıl yorumlanır?', 'numeroloji,hayat yolu sayisi,kisisel gelisim', NOW(3), NOW(3)),
  ('b1en0000-0000-4000-8000-000000000004', 'b1000000-0000-4000-8000-000000000004', 'en', 'Life Path Number in Numerology', 'life-path-number-in-numerology', '{"html":"<h2>What is a life path number?</h2><p>The life path number is a core numerology indicator calculated from the date of birth. It offers a symbolic frame for learning style, motivation, and recurring life themes.</p><h3>How is it interpreted?</h3><p>It is not a fixed verdict. When read with current cycles, personal goals, and lived context, it can support gentler self awareness during decisions and transitions.</p>"}', 'Understand what the life path number means, how it is calculated, and how it is used in guidance.', 'Numerology numbers with gold lines', 'Life Path Number in Numerology', 'What is a life path number, how is it calculated, and how can numerology readings use it?', 'numerology,life path number,self awareness', NOW(3), NOW(3)),
  ('b1de0000-0000-4000-8000-000000000004', 'b1000000-0000-4000-8000-000000000004', 'de', 'Lebenswegzahl in der Numerologie', 'lebenswegzahl-numerologie', '{"html":"<h2>Was ist die Lebenswegzahl?</h2><p>Die Lebenswegzahl ist ein zentraler numerologischer Hinweis, der aus dem Geburtsdatum berechnet wird. Sie bietet einen symbolischen Rahmen für Lernstil, Motivation und wiederkehrende Lebensthemen.</p><h3>Wie wird sie gedeutet?</h3><p>Sie ist kein festes Urteil. Zusammen mit aktuellen Zyklen, persönlichen Zielen und realem Kontext kann sie Entscheidungen und Übergänge bewusster machen.</p>"}', 'Erfahren Sie, was die Lebenswegzahl bedeutet, wie sie berechnet wird und wie sie in Beratungen genutzt wird.', 'Numerologische Zahlen mit goldenen Linien', 'Lebenswegzahl in der Numerologie', 'Was ist die Lebenswegzahl, wie wird sie berechnet und wie wird sie in der Numerologie gedeutet?', 'numerologie,lebenswegzahl,selbstreflexion', NOW(3), NOW(3)),

  ('b1tr0000-0000-4000-8000-000000000005', 'b1000000-0000-4000-8000-000000000005', 'tr', 'Ay Burcu Duygusal İhtiyaçları Nasıl Gösterir?', 'ay-burcu-duygusal-ihtiyaclar', '{"html":"<h2>Ay burcu neden özeldir?</h2><p>Ay burcu, kişinin güvende hissetme biçimini, duygusal reflekslerini ve yakın ilişkilerde ihtiyaç duyduğu ritmi anlatır. Bu yüzden sadece romantik ilişkilerde değil, aile ve iç dünya okumalarında da önemlidir.</p><h3>Danışmanlıkta nasıl kullanılır?</h3><p>Ay burcunun elementi, evi ve aldığı açılar birlikte değerlendirildiğinde kişinin kendini nasıl yatıştırdığı, hangi ortamlarda beslendiği ve nerede sınır koyması gerektiği daha net görünür.</p>"}', 'Ay burcunun duygusal güven, ilişki ritmi ve içsel ihtiyaçlarla bağlantısını keşfedin.', 'Ay fazları ve mor gökyüzü', 'Ay Burcu ve Duygusal İhtiyaçlar', 'Ay burcu neyi anlatır, duygusal güven ve ilişki ihtiyaçları astrolojide nasıl yorumlanır?', 'ay burcu,duygular,astroloji', NOW(3), NOW(3)),
  ('b1en0000-0000-4000-8000-000000000005', 'b1000000-0000-4000-8000-000000000005', 'en', 'Moon Sign and Emotional Needs', 'moon-sign-and-emotional-needs', '{"html":"<h2>Why is the Moon sign important?</h2><p>The Moon sign describes how someone feels safe, reacts emotionally, and seeks rhythm in close relationships. It matters in romance, family themes, and inner world reflection.</p><h3>How is it used in a session?</h3><p>The Moon element, house, and aspects reveal how a person self soothes, what environments nourish them, and where clearer boundaries may be helpful.</p>"}', 'Explore how the Moon sign relates to emotional safety, relationship rhythm, and inner needs.', 'Moon phases over a purple sky', 'Moon Sign and Emotional Needs', 'What does the Moon sign reveal about emotional safety and relationship needs in astrology?', 'moon sign,emotions,astrology', NOW(3), NOW(3)),
  ('b1de0000-0000-4000-8000-000000000005', 'b1000000-0000-4000-8000-000000000005', 'de', 'Mondzeichen und emotionale Bedürfnisse', 'mondzeichen-und-emotionale-beduerfnisse', '{"html":"<h2>Warum ist das Mondzeichen wichtig?</h2><p>Das Mondzeichen beschreibt, wie jemand Sicherheit empfindet, emotional reagiert und in nahen Beziehungen Rhythmus sucht. Es ist für Liebe, Familie und innere Reflexion bedeutsam.</p><h3>Wie wird es in einer Beratung genutzt?</h3><p>Element, Haus und Aspekte des Mondes zeigen, wie ein Mensch sich beruhigt, welche Umgebungen nähren und wo klarere Grenzen hilfreich sein können.</p>"}', 'Entdecken Sie, wie das Mondzeichen mit emotionaler Sicherheit, Beziehungsrhythmus und inneren Bedürfnissen verbunden ist.', 'Mondphasen über violettem Himmel', 'Mondzeichen und emotionale Bedürfnisse', 'Was zeigt das Mondzeichen über emotionale Sicherheit und Bedürfnisse in Beziehungen?', 'mondzeichen,emotionen,astrologie', NOW(3), NOW(3)),

  ('b1tr0000-0000-4000-8000-000000000006', 'b1000000-0000-4000-8000-000000000006', 'tr', 'Retro Dönemlerinde Karar Almak', 'retro-donemlerinde-karar-almak', '{"html":"<h2>Retro dönemleri ne anlatır?</h2><p>Retro dönemleri gökyüzünde geri hareket gibi görünen gezegen döngüleridir. Astrolojik dilde bu dönemler yeniden değerlendirme, yavaşlama ve eksik kalan konuları tamamlama teması taşır.</p><h3>Karar alırken ne yapılabilir?</h3><p>Her şeyi durdurmak gerekmez. Sözleşme, ilişki, taşınma veya iş değişikliği gibi başlıklarda acele yerine kontrol listesi, ikinci görüş ve zamanlama farkındalığı kullanılabilir.</p>"}', 'Retro dönemlerinde kararları ertelemeden ama daha bilinçli ele almak için pratik astroloji rehberi.', 'Retro gezegen hareketi çizimi', 'Retro Dönemlerinde Karar Almak', 'Merkür ve diğer retro dönemlerinde karar alırken nelere dikkat edilmeli?', 'retro,merkur retrosu,astroloji', NOW(3), NOW(3)),
  ('b1en0000-0000-4000-8000-000000000006', 'b1000000-0000-4000-8000-000000000006', 'en', 'Making Decisions During Retrogrades', 'making-decisions-during-retrogrades', '{"html":"<h2>What do retrogrades represent?</h2><p>Retrogrades are planetary cycles that appear to move backward from Earth. In astrology, they often point to review, slowing down, and returning to unfinished matters.</p><h3>How can decisions be handled?</h3><p>You do not have to stop everything. For contracts, relationships, moving, or job changes, use checklists, second opinions, and timing awareness instead of rushing.</p>"}', 'A practical astrology guide for making decisions during retrograde periods with more awareness.', 'Retrograde planet movement illustration', 'Making Decisions During Retrogrades', 'What should you consider during Mercury and other retrograde periods before making decisions?', 'retrograde,mercury retrograde,astrology', NOW(3), NOW(3)),
  ('b1de0000-0000-4000-8000-000000000006', 'b1000000-0000-4000-8000-000000000006', 'de', 'Entscheidungen in rückläufigen Phasen', 'entscheidungen-in-ruecklaeufigen-phasen', '{"html":"<h2>Was bedeuten rückläufige Phasen?</h2><p>Rückläufigkeiten sind planetare Zyklen, die von der Erde aus wie eine Rückwärtsbewegung erscheinen. Astrologisch stehen sie oft für Prüfung, Verlangsamung und offene Themen.</p><h3>Wie geht man mit Entscheidungen um?</h3><p>Es muss nicht alles gestoppt werden. Bei Verträgen, Beziehungen, Umzug oder Jobwechsel helfen Checklisten, zweite Meinungen und ein bewussteres Timing.</p>"}', 'Ein praktischer Astrologie Leitfaden für bewusstere Entscheidungen während rückläufiger Phasen.', 'Illustration einer rückläufigen Planetenbewegung', 'Entscheidungen in rückläufigen Phasen', 'Worauf sollte man bei Merkur und anderen rückläufigen Phasen vor Entscheidungen achten?', 'ruecklaeufig,merkur retrograd,astrologie', NOW(3), NOW(3)),

  ('b1tr0000-0000-4000-8000-000000000007', 'b1000000-0000-4000-8000-000000000007', 'tr', 'Ruhsal Danışman Seçerken Nelere Bakılmalı?', 'ruhsal-danisman-secme-rehberi', '{"html":"<h2>İyi danışmanlık nasıl anlaşılır?</h2><p>Ruhsal danışmanlıkta güven, sınır ve açıklık en az teknik bilgi kadar önemlidir. Danışmanın uzmanlığı, yorum dili, etik yaklaşımı ve seans sonrası uygulanabilir önerileri birlikte değerlendirilmelidir.</p><h3>Seçim yaparken kontrol listesi</h3><p>Uzmanlık alanı, kullanıcı yorumları, seans süresi, fiyat şeffaflığı ve danışmanın sorunu tıbbi veya hukuki iddia gibi sunmaması temel göstergelerdir. GoldMoodAstro profilleri bu bilgileri daha görünür hale getirir.</p>"}', 'Astroloji, tarot veya numeroloji danışmanı seçerken güven, uzmanlık ve etik sınırları değerlendirme rehberi.', 'Sesli danışmanlık oturumu görseli', 'Ruhsal Danışman Seçme Rehberi', 'Ruhsal danışman seçerken uzmanlık, yorum dili, etik sınırlar ve kullanıcı yorumları nasıl değerlendirilir?', 'danisman secimi,ruhsal danismanlik,astroloji', NOW(3), NOW(3)),
  ('b1en0000-0000-4000-8000-000000000007', 'b1000000-0000-4000-8000-000000000007', 'en', 'How to Choose a Spiritual Consultant', 'how-to-choose-a-spiritual-consultant', '{"html":"<h2>What makes guidance trustworthy?</h2><p>In spiritual guidance, trust, boundaries, and clarity matter as much as technical knowledge. Review the consultant expertise, language, ethical stance, and whether the session leaves you with practical reflection.</p><h3>A simple checklist</h3><p>Specialty, user reviews, session length, transparent pricing, and avoiding medical or legal claims are key signals. GoldMoodAstro profiles make these details easier to compare.</p>"}', 'A guide to evaluating trust, expertise, and ethical boundaries when choosing an astrology, tarot, or numerology consultant.', 'Voice consultation session illustration', 'How to Choose a Spiritual Consultant', 'How to evaluate expertise, communication style, ethical boundaries, and reviews before choosing a consultant.', 'spiritual consultant,astrology consultant,tarot reading', NOW(3), NOW(3)),
  ('b1de0000-0000-4000-8000-000000000007', 'b1000000-0000-4000-8000-000000000007', 'de', 'Spirituelle Beratung wählen', 'spirituelle-beratung-waehlen', '{"html":"<h2>Woran erkennt man vertrauensvolle Beratung?</h2><p>In spiritueller Beratung zählen Vertrauen, Grenzen und Klarheit ebenso wie Fachwissen. Achten Sie auf Expertise, Sprache, ethische Haltung und darauf, ob die Sitzung praktische Reflexion ermöglicht.</p><h3>Eine einfache Checkliste</h3><p>Spezialisierung, Bewertungen, Sitzungsdauer, transparente Preise und keine medizinischen oder rechtlichen Versprechen sind wichtige Signale. GoldMoodAstro Profile machen diese Punkte vergleichbar.</p>"}', 'Ein Leitfaden zu Vertrauen, Expertise und ethischen Grenzen bei Astrologie, Tarot oder Numerologie Beratung.', 'Illustration einer Audio Beratung', 'Spirituelle Beratung wählen', 'Wie bewertet man Expertise, Kommunikationsstil, ethische Grenzen und Rezensionen vor der Beratung?', 'spirituelle beratung,astrologie beratung,tarot', NOW(3), NOW(3)),

  ('b1tr0000-0000-4000-8000-000000000008', 'b1000000-0000-4000-8000-000000000008', 'tr', 'Günlük Ritüel: Astroloji ve Tarot ile Kısa Check-in', 'gunluk-rituel-astroloji-tarot', '{"html":"<h2>Günlük check-in neden işe yarar?</h2><p>Kısa bir ritüel, günün temposuna başlamadan önce dikkati toparlamaya yardımcı olur. Ay fazı, günün burç etkisi ve tek kart tarot çekimi birlikte kullanıldığında duygu, niyet ve eylem daha net ayrışır.</p><h3>Beş dakikalık akış</h3><p>Önce bugünkü ana duyguyu yazın, sonra tek kart çekip sembolün size hatırlattığı davranışı not alın. Son adımda gün için küçük ve uygulanabilir bir niyet belirleyin.</p>"}', 'Astroloji ve tarotla beş dakikalık günlük farkındalık ritüeli oluşturmak için uygulanabilir rehber.', 'Günlük ritüel defteri ve tarot kartı', 'Astroloji ve Tarot ile Günlük Ritüel', 'Günlük astroloji ve tarot check-in ritüeli nasıl yapılır, niyet ve farkındalık nasıl belirlenir?', 'gunluk rituel,tarot,astroloji', NOW(3), NOW(3)),
  ('b1en0000-0000-4000-8000-000000000008', 'b1000000-0000-4000-8000-000000000008', 'en', 'Daily Ritual with Astrology and Tarot', 'daily-ritual-with-astrology-and-tarot', '{"html":"<h2>Why does a daily check-in help?</h2><p>A short ritual can gather attention before the day accelerates. Combining the Moon phase, the day astrology, and a one card tarot pull separates feeling, intention, and action.</p><h3>A five minute flow</h3><p>Write the main feeling of the day, pull one card, and note the behavior the symbol suggests. Finish with one small and realistic intention for the day.</p>"}', 'A practical five minute awareness ritual using astrology and tarot for daily intention setting.', 'Daily ritual journal with tarot card', 'Daily Ritual with Astrology and Tarot', 'How to create a daily astrology and tarot check-in ritual for intention and self awareness.', 'daily ritual,tarot,astrology', NOW(3), NOW(3)),
  ('b1de0000-0000-4000-8000-000000000008', 'b1000000-0000-4000-8000-000000000008', 'de', 'Tägliches Ritual mit Astrologie und Tarot', 'taegliches-ritual-astrologie-tarot', '{"html":"<h2>Warum hilft ein täglicher Check-in?</h2><p>Ein kurzes Ritual sammelt Aufmerksamkeit, bevor der Tag schneller wird. Mondphase, Tagesastrologie und eine einzelne Tarotkarte helfen, Gefühl, Absicht und Handlung zu unterscheiden.</p><h3>Ein Ablauf in fünf Minuten</h3><p>Notieren Sie das wichtigste Gefühl des Tages, ziehen Sie eine Karte und schreiben Sie auf, welches Verhalten das Symbol anregt. Abschließend setzen Sie eine kleine realistische Absicht.</p>"}', 'Ein praktisches Fünf Minuten Ritual mit Astrologie und Tarot für tägliche Ausrichtung.', 'Tagebuch mit Tarotkarte für tägliches Ritual', 'Tägliches Ritual mit Astrologie und Tarot', 'Wie erstellt man einen täglichen Astrologie und Tarot Check-in für Absicht und Selbstwahrnehmung?', 'taegliches ritual,tarot,astrologie', NOW(3), NOW(3))
ON DUPLICATE KEY UPDATE
  title = VALUES(title),
  slug = VALUES(slug),
  content = VALUES(content),
  summary = VALUES(summary),
  featured_image_alt = VALUES(featured_image_alt),
  meta_title = VALUES(meta_title),
  meta_description = VALUES(meta_description),
  tags = VALUES(tags),
  updated_at = NOW(3);
