CREATE TABLE IF NOT EXISTS seo_quality_scores (
  id            CHAR(36)     NOT NULL PRIMARY KEY,
  entity_type   VARCHAR(24)  NOT NULL,
  entity_id     VARCHAR(191) NOT NULL,
  locale        VARCHAR(8)   NOT NULL,
  url           VARCHAR(512) NULL,
  meta_score    TINYINT UNSIGNED NOT NULL DEFAULT 0,
  content_score TINYINT UNSIGNED NOT NULL DEFAULT 0,
  heading_score TINYINT UNSIGNED NOT NULL DEFAULT 0,
  media_score   TINYINT UNSIGNED NOT NULL DEFAULT 0,
  schema_score  TINYINT UNSIGNED NOT NULL DEFAULT 0,
  link_score    TINYINT UNSIGNED NOT NULL DEFAULT 0,
  overall_score TINYINT UNSIGNED NOT NULL DEFAULT 0,
  word_count    INT UNSIGNED NOT NULL DEFAULT 0,
  heading_count INT UNSIGNED NOT NULL DEFAULT 0,
  image_count   INT UNSIGNED NOT NULL DEFAULT 0,
  has_meta_title       TINYINT(1) NOT NULL DEFAULT 0,
  has_meta_description TINYINT(1) NOT NULL DEFAULT 0,
  has_h1               TINYINT(1) NOT NULL DEFAULT 0,
  has_schema           TINYINT(1) NOT NULL DEFAULT 0,
  is_thin_content      TINYINT(1) NOT NULL DEFAULT 0,
  adsense_ready        TINYINT(1) NOT NULL DEFAULT 0,
  index_ready          TINYINT(1) NOT NULL DEFAULT 0,
  breakdown     JSON NULL,
  calculated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at    DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  UNIQUE KEY seo_quality_entity_uq (entity_type, entity_id, locale),
  KEY seo_quality_overall_idx (overall_score),
  KEY seo_quality_type_idx (entity_type),
  KEY seo_quality_adsense_idx (adsense_ready)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
