-- Ekosistem sosyal medya modulleri — Faz 3 (FB/IG/X + gonderiler + sablonlar) tablolari.
-- Kaynak: ekosistem-sosyal-medya schema.ts. De-tenant: tenant_key/sub_type kolonlari korunur,
-- daima 'goldmoodastro'. ALTER yok; CREATE TABLE IF NOT EXISTS (idempotent).

CREATE TABLE IF NOT EXISTS content_templates (
  id INT AUTO_INCREMENT PRIMARY KEY,
  uuid CHAR(36) NOT NULL,
  tenant_key VARCHAR(100),
  name VARCHAR(255) NOT NULL,
  post_type ENUM('haber','etkilesim','ilan','nostalji','tanitim','kampanya') NOT NULL,
  platform ENUM('facebook','instagram','both','linkedin','x','telegram','all','youtube') NOT NULL DEFAULT 'both',
  caption_template TEXT NOT NULL,
  hashtags VARCHAR(500),
  image_prompt VARCHAR(500),
  variables JSON,
  is_active TINYINT DEFAULT 1,
  usage_count INT DEFAULT 0,
  last_used_at DATETIME,
  created_at DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  UNIQUE KEY content_templates_uuid_unique (uuid),
  KEY idx_ct_post_type (post_type),
  KEY idx_ct_active (is_active),
  KEY idx_ct_tenant (tenant_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS social_posts (
  id INT AUTO_INCREMENT PRIMARY KEY,
  uuid CHAR(36) NOT NULL,
  post_type ENUM('haber','etkilesim','ilan','nostalji','tanitim','kampanya') NOT NULL,
  sub_type VARCHAR(50),
  title VARCHAR(255),
  caption TEXT NOT NULL,
  hashtags VARCHAR(500),
  image_url VARCHAR(1000),
  image_local VARCHAR(500),
  link_url VARCHAR(1000),
  link_text VARCHAR(255),
  platform ENUM('facebook','instagram','both','linkedin','x','telegram','all','youtube') NOT NULL DEFAULT 'both',
  fb_page_id VARCHAR(100),
  ig_account_id VARCHAR(100),
  scheduled_at DATETIME,
  posted_at DATETIME,
  status ENUM('draft','scheduled','publishing','manual_pending','posted','failed','cancelled') NOT NULL DEFAULT 'draft',
  error_message VARCHAR(1000),
  fb_post_id VARCHAR(255),
  ig_media_id VARCHAR(255),
  x_tweet_id VARCHAR(64),
  youtube_video_id VARCHAR(64),
  postproxy_post_id VARCHAR(64),
  x_thread_group CHAR(36),
  x_thread_order INT,
  x_reply_to_tweet_id VARCHAR(64),
  media_urls JSON,
  auto_edit_job_id VARCHAR(64),
  auto_edit_status ENUM('queued','processing','done','failed','approved'),
  auto_edit_transcript TEXT,
  auto_edit_segments JSON,
  auto_edit_error TEXT,
  source_type ENUM('manual','news','ai','template') NOT NULL DEFAULT 'manual',
  source_ref VARCHAR(255),
  ai_generated TINYINT DEFAULT 0,
  ai_model VARCHAR(100),
  ai_prompt_used TEXT,
  created_by VARCHAR(100) DEFAULT 'system',
  notes TEXT,
  created_at DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  UNIQUE KEY social_posts_uuid_unique (uuid),
  KEY idx_sp_status (status),
  KEY idx_sp_scheduled (scheduled_at),
  KEY idx_sp_platform (platform),
  KEY idx_sp_post_type (post_type),
  KEY idx_sp_source (source_type),
  KEY idx_sp_youtube (youtube_video_id),
  KEY idx_sp_x_thread (x_thread_group),
  KEY idx_sp_subtype (sub_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS platform_accounts (
  id INT AUTO_INCREMENT PRIMARY KEY,
  uuid CHAR(36) NOT NULL,
  platform ENUM('facebook','instagram','telegram','linkedin','x','youtube') NOT NULL,
  tenant_key VARCHAR(100) NOT NULL DEFAULT 'goldmoodastro',
  account_name VARCHAR(255) NOT NULL,
  account_id VARCHAR(255),
  access_token TEXT,
  token_expires DATETIME,
  refresh_token TEXT,
  page_id VARCHAR(255),
  page_token TEXT,
  is_active TINYINT DEFAULT 1,
  last_post_at DATETIME,
  error_count INT DEFAULT 0,
  last_error VARCHAR(500),
  meta JSON,
  created_at DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  UNIQUE KEY platform_accounts_uuid_unique (uuid),
  KEY idx_pa_platform (platform),
  KEY idx_pa_active (is_active),
  KEY idx_pa_tenant (tenant_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS tenant_oauth_clients (
  id INT AUTO_INCREMENT PRIMARY KEY,
  uuid CHAR(36) NOT NULL,
  tenant_key VARCHAR(100) NOT NULL,
  platform ENUM('youtube','google','facebook','instagram','linkedin','x') NOT NULL,
  client_id VARCHAR(255) NOT NULL,
  client_secret_encrypted TEXT NOT NULL,
  redirect_uri VARCHAR(500) NOT NULL,
  is_active TINYINT DEFAULT 1,
  created_at DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  UNIQUE KEY tenant_oauth_clients_uuid_unique (uuid),
  UNIQUE KEY uk_toc_tenant_platform (tenant_key, platform),
  KEY idx_toc_tenant (tenant_key),
  KEY idx_toc_platform (platform)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS post_comments (
  id INT AUTO_INCREMENT PRIMARY KEY,
  uuid CHAR(36) NOT NULL,
  post_id INT NOT NULL,
  platform ENUM('facebook','instagram','x') NOT NULL,
  external_comment_id VARCHAR(255) NOT NULL,
  parent_comment_id VARCHAR(255),
  author_name VARCHAR(255),
  author_id VARCHAR(255),
  message TEXT NOT NULL,
  ai_reply_draft TEXT,
  ai_reply_status ENUM('pending','approved','rejected','sent'),
  ai_reply_model VARCHAR(100),
  ai_reply_provider VARCHAR(100),
  ai_replied_tweet_id VARCHAR(64),
  like_count INT DEFAULT 0,
  created_time DATETIME(3),
  fetched_at DATETIME(3) NOT NULL,
  created_at DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  UNIQUE KEY post_comments_uuid_unique (uuid),
  UNIQUE KEY uk_pc_post_platform_ext (post_id, platform, external_comment_id),
  KEY idx_pc_post (post_id),
  CONSTRAINT fk_pc_post FOREIGN KEY (post_id) REFERENCES social_posts(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS post_analytics (
  id INT AUTO_INCREMENT PRIMARY KEY,
  post_id INT NOT NULL,
  platform ENUM('facebook','instagram','x','youtube') NOT NULL,
  likes INT DEFAULT 0,
  comments INT DEFAULT 0,
  shares INT DEFAULT 0,
  saves INT DEFAULT 0,
  reach INT DEFAULT 0,
  impressions INT DEFAULT 0,
  clicks INT DEFAULT 0,
  engagement_rate DECIMAL(5,2) DEFAULT '0',
  fetched_at DATETIME(3) NOT NULL,
  KEY idx_pan_post (post_id),
  KEY idx_pan_platform (platform),
  KEY idx_pan_fetched (fetched_at),
  CONSTRAINT fk_pan_post FOREIGN KEY (post_id) REFERENCES social_posts(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS campaign_calendar (
  id INT AUTO_INCREMENT PRIMARY KEY,
  uuid CHAR(36) NOT NULL,
  tenant_key VARCHAR(100) NOT NULL DEFAULT 'goldmoodastro',
  date DATE NOT NULL,
  time_slot ENUM('morning','afternoon','evening') NOT NULL DEFAULT 'morning',
  post_type ENUM('haber','etkilesim','ilan','nostalji','tanitim','kampanya') NOT NULL,
  platform ENUM('facebook','instagram','both','linkedin','x','telegram','all','youtube') NOT NULL DEFAULT 'both',
  notes TEXT,
  template_id INT,
  post_id INT,
  status ENUM('planned','content_ready','scheduled','published','skipped') DEFAULT 'planned',
  created_at DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  UNIQUE KEY campaign_calendar_uuid_unique (uuid),
  UNIQUE KEY uk_cc_slot (tenant_key, date, time_slot, platform),
  CONSTRAINT fk_cc_template FOREIGN KEY (template_id) REFERENCES content_templates(id) ON DELETE SET NULL,
  CONSTRAINT fk_cc_post FOREIGN KEY (post_id) REFERENCES social_posts(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS x_api_usage (
  id INT AUTO_INCREMENT PRIMARY KEY,
  usage_month CHAR(7) NOT NULL,
  operation ENUM('write','read') NOT NULL,
  count INT NOT NULL DEFAULT 0,
  created_at DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  UNIQUE KEY uk_xau_month_op (usage_month, operation)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
