import { readFileSync, writeFileSync } from 'fs';
import { join } from 'path';

function generateThemeSnapshot() {
  const sqlPath = join(process.cwd(), 'backend/src/db/sql/010_site_settings.sql');
  const sql = readFileSync(sqlPath, 'utf8');

  // Match the design_tokens line
  const regex = /'design_tokens',\s*'\*',\s*'({[\s\S]*?})'\)/;
  const match = sql.match(regex);
  if (!match) {
    console.error('Could not find design_tokens JSON in site_settings SQL seed');
    process.exit(1);
  }

  let jsonStr = match[1];
  // Replace double single quotes with single quotes if any escaped quotes exist
  jsonStr = jsonStr.replace(/''/g, "'");

  let tokens;
  try {
    tokens = JSON.parse(jsonStr);
  } catch (err) {
    console.error('Failed to parse design_tokens JSON:', err);
    console.error('JSON content:', jsonStr);
    process.exit(1);
  }

  const codeContent = `import type { DesignTokens } from './types';

// WARNING: This file is generated automatically from site settings seed.
// DO NOT EDIT THIS FILE MANUALLY. Use bun run gen:theme-snapshot instead.
export const DEFAULT_TOKENS: DesignTokens = ${JSON.stringify(tokens, null, 2)};
`;

  const outputPath = join(process.cwd(), 'frontend/src/lib/tokens/defaults.ts');
  writeFileSync(outputPath, codeContent, 'utf8');
  console.log('Successfully generated theme snapshot at frontend/src/lib/tokens/defaults.ts');
}

generateThemeSnapshot();
